### ISSUE TITLE
New Chrome User Data Directories

### ISSUE THREAD

**Issue by mikhaelkh** [MoscaDotTo/Winapp2#103]
https://blog.chromium.org/2017/08/run-multiple-versions-of-chrome-side-by.html
Now different channels of Chrome can be installed side-by-side and have separate installation and user data directories. For example, for Chrome Beta user data dir now is `%LOCALAPPDATA%\Google\Chrome Beta\User Data\`. Some entries like `SetupMetrics*` or `Browser Exit Codes*` or `Chrome Temps*` doesn't reflect that change. Also, DET_CHROME doesn't detect Chrome Beta.

**Comment by TZocker** [comment]
thx, we can hope that piriform fix this with the det_chrome until this we can add the regkey like the chrome derivate like chromium.

greets

**Comment by ROCKNROLLKID** [comment]
If you know the exact directories and files and you have tested it thoroughly, please open a ticket with the entries.

The detect is a issue with CCleaner and needs to be brought up to them.
