### ISSUE TITLE
Some Chrome Extensions fails to save settings

### ISSUE THREAD

**Issue by Buddle** [MoscaDotTo/Winapp2#104]
This occurs on Chrome Stable 61+
Please add it into Chrome logs section

```
[Logs*]
 +ExcludeKey41=PATH|%LocalAppData%\Google\Chrome*\User Data\*\Local Storage\leveldb|*.*
```

**Comment by ROCKNROLLKID** [comment]
Fixed https://github.com/MoscaDotTo/Winapp2/commit/8bad31c6acc7dc68a587a55088ed3921d08cdad4
