### ISSUE TITLE
Zemana Anti-Malware

### ISSUE THREAD

**Issue by ShaneGowland** [MoscaDotTo/Winapp2#105]
This was reported by one of our users. These files look quite important and probably shouldn't be targeted by winapp2.ini

See screenshot: https://vgy.me/S8LUWZ.png

**Comment by ROCKNROLLKID** [comment]
Fixed in https://github.com/MoscaDotTo/Winapp2/commit/b023587788b7c549ad8dae360df9ba4b27c5bf13
