### ISSUE TITLE
ExcludeKey missing FILE in SeaMonkey More

### ISSUE THREAD

**Issue by az0** [MoscaDotTo/Winapp2#113]
Problem line
`ExcludeKey1=%AppData%\Mozilla\SeaMonkey\Profiles\*\storage\default\moz-extension*`

Shouldn't it have FILE?

**Comment by ROCKNROLLKID** [comment]
what entry is this for? I looked at all the SeaMonkey and Mozilla entries but couldn't find the specific line you were looking for.

**Comment by ROCKNROLLKID** [comment]
Actually it should be PATH as it is pointing to a folder and not a specific file.

Corrected in last commit.
