### ISSUE TITLE
What to do with recent additions on forums

### ISSUE THREAD

**Issue by ROCKNROLLKID** [MoscaDotTo/Winapp2#12]
Just wondering what you will do with all the additions everyone has posted for the past 2 weeks on the forums? Are you going to add them here yourself or shall we re-post them here as pull requests?

**Comment by winapp2** [comment]
Sorry for disturbing you, but in case you belive I'm winapp2. I'm not him. Just had this name, will delete my account later after my changes have been in.

**Comment by ROCKNROLLKID** [comment]
Commit https://github.com/MoscaDotTo/Winapp2/commit/ce8dc52f37c14d9a0a406b253c103072babd1011

Closing ticket.
