### ISSUE TITLE
Enabled By Default

### ISSUE THREAD

**Issue by zero77** [MoscaDotTo/Winapp2#134]
Can you please enable by default all of the entries that do not have a warning and thus are not likely to cause a problem.

Because, after the Winapp2 file has been added to CCleaner for the first time, it takes a long time to tick every box and un-tick the boxes that have warnings and may cause problems.
Thanks

**Comment by MoscaDotTo** [comment]
All entries are disabled by default to put the onus on the user to select the options and prevent any unexpected deletions. Since CCleaner is very "set and forget" in this regard, it should only need to be done once.

**Comment by zero77** [comment]
You raise a good point "set and forget in this regard, it should only need to be done once". 
Although, it still takes a while when needing to be done after a reinstall or on a new device.

**Comment by ROCKNROLLKID** [comment]
If you click on the names of each section in CCleaner, it will auto select each entry in that section. If you are asking for a select all option, that will need to be brought up to the CCleaner developers. For safety reasons, we keep all entries Default=False.

**Comment by MoscaDotTo** [comment]
[http://www.piriform.com/docs/ccleaner/ccleaner-settings/changing-advanced-settings](these) two [http://www.piriform.com/docs/ccleaner/advanced-usage/ccleaner-ini-files/using-ccleanerini-to-modify-how-ccleaner-runs](links) may prove helpful if you're looking to migrate CCleaner settings between machines.

**Comment by CSGalloway** [comment]
The first link goes to http://these and the 2nd one goes to http://links -
both incorrect....

http://www.facebook.com/CSGalloway

**Comment by ROCKNROLLKID** [comment]
They work find for me, but here are the 2 links if they don't work for you:

http://www.piriform.com/docs/ccleaner/ccleaner-settings/changing-advanced-settings

http://www.piriform.com/docs/ccleaner/advanced-usage/ccleaner-ini-files/using-ccleanerini-to-modify-how-ccleaner-runs

**Comment by zero77** [comment]
I see your point, and thanks for the links I will have a look at them.

Although, as a safer counter solution, could you add two stars or an exclamation mark next to the entry’s that have warnings so, it is easier to see at a glance the.

Thanks
