### ISSUE TITLE
Waterfox support broken?

### ISSUE THREAD

**Issue by MoscaDotTo** [MoscaDotTo/Winapp2#137]
https://twitter.com/_natr0n_/status/921272035749388288

someone tweeted this to me a while back. Figured I'd put it on file 👍

**Comment by ROCKNROLLKID** [comment]
This is mostly due to the change back in Waterfox 55 when they decided to use their own profile, instead of Firefoxs. https://www.waterfoxproject.org/blog/waterfox-55.0-release-download

I don't know if I know how to solve this.

**Comment by MoscaDotTo** [comment]
This will be fixed by #138
