### ISSUE TITLE
[Off Topic] Mobile Version piriform-Forum doesn't work.

### ISSUE THREAD

**Issue by winapp2** [MoscaDotTo/Winapp2#14]
Mobile Version piriform-Forum doesn't work. Please could this be fixed or at least be told to devs. I don't use the tapatalk app and I'm not going to. I use normal chrome app.

**Comment by winapp2** [comment]
![_20160825_100710](https://cloud.githubusercontent.com/assets/21228820/17961420/e9835904-6aab-11e6-96f7-f4a84d5cd268.JPG)


This is really how it looks like and you can't do anything. This is annoying.

**Comment by TZocker** [comment]
switch to desktop version and it works ....

**Comment by winapp2** [comment]
Wow, nice idea, but it's an annoyance. How about fixing it Piriform?

**Comment by ROCKNROLLKID** [comment]
This isn't the place to ask this. You need to go to Piriform forums to ask that. This is just for Winapp2. Please note that Piriform doesn't own winapp2 and that it is maintained by community members.

**Comment by winapp2** [comment]
I know, but could you or another one please report this annoying bug, because winapp2.ini is maintained in both github and forum.
