### ISSUE TITLE
Make sure Virtualstore\Program Files* is supplmented with a *

### ISSUE THREAD

**Issue by ROCKNROLLKID** [MoscaDotTo/Winapp2#142]
Copy/pasted from BleachBit respo:

For example:

%LocalAppData%\VirtualStore\Program Files*

The program Files must be supplemented with a asterisk, other the entry will not have its full potential cleaning rule. So my suggestion would be to look for this specific directory and make sure it has a asterisk. I suppose you could also make it check to make sure this entry is spelled correctly, as this is the only place where VirtualStore is.

Related: https://forum.piriform.com/index.php?showtopic=32310&p=288008

**Comment by MoscaDotTo** [comment]
https://github.com/MoscaDotTo/Winapp2/commit/fd2b6307685bce460890610fea4bc3d205f412d5
