### ISSUE TITLE
Determine if CCDump is still needed.

### ISSUE THREAD

**Issue by ROCKNROLLKID** [MoscaDotTo/Winapp2#143]
It has been brought up in the past that CCleaner already does what CCDump does. Is this tool still useful?

**Comment by ROCKNROLLKID** [comment]
I guess the benefit of CCDump is that it can extract winapp.ini, winreg.ini, and winsys.ini in 1 click, vs having to extract each of them manually with cmd. In my opinion, I think it is still useful.

@MoscaDotTo What do you think?

**Comment by MoscaDotTo** [comment]
@ShaneGowland would know best

**Comment by ShaneGowland** [comment]
I still use it because /EXPORT takes 10 extra seconds.

**Comment by ROCKNROLLKID** [comment]
Yes, I feel like it still has it uses, so going to close this issue then.
