### ISSUE TITLE
Readme for Winappparser?

### ISSUE THREAD

**Issue by ROCKNROLLKID** [MoscaDotTo/Winapp2#147]
I'll be honest, I am not sure what this tool is actually suppose to do. Every time I use it, nothing really happens.

**Comment by MoscaDotTo** [comment]
I don't think this is necessary. At a glance, the parser seems to be from an old version of System Ninja and the majority of its functionality has been replicated in some form or another in winapp2ool. I will probably deprecate winappparser alongside winappdebug and ccinidebug (standalone)
