### ISSUE TITLE
Avira no longer uses Winapp2?

### ISSUE THREAD

**Issue by ROCKNROLLKID** [MoscaDotTo/Winapp2#148]
@MoscaDotTo I just checked the most recent version of Avira System Speedup and noticed they don't have the Winapp2 setting anymore. I do not see any Winapp2 file anymore in any Avira folder. Do you know if they are still using it or not? I tested free version or did they move it for pro users only?

**Comment by MoscaDotTo** [comment]
I don't see any reference to it in the program either. Unclear to me whether or not the functionality still exists in some form, but I don't see any reference to it being removed on their changelog page: https://answers.avira.com/en/question/changelog-9977

**Comment by ROCKNROLLKID** [comment]
There is a section under Device Optimizer (where the winapp2 option was) that can only be revealed to pro users. I wonder if they moved it there. Does any have Avira System Speedup pro to confirm if it is there?

**Comment by ROCKNROLLKID** [comment]
@MoscaDotTo I tried several contact methods, but so far so reply from Avira. Have you had any luck on your end?

**Comment by MoscaDotTo** [comment]
I asked on Twitter and they said it is still included in the product.

https://twitter.com/AskAvira/status/959325959974473728

**Comment by ROCKNROLLKID** [comment]
Thank you Robert. They sure don't have easy support, haha. Glad they are still using Winapp2 though.
