### ISSUE TITLE
[WinappDebug] Ignore non-CCleaner copy of Winapp2

### ISSUE THREAD

**Issue by ROCKNROLLKID** [MoscaDotTo/Winapp2#160]
We should make WinappDebug not run for the non-CCleaner copy of Winapp2 because it is designed for the CCleaner version and several errors get detected due to the additional entries in the non-CCleaner when they are not errors. We should add a message that states something like: "You are trying to run WinappDebug for the non-CCleaner version of Winapp2. WinappDebug should only be used for the CCleaner version as the non-CCleaner version has several changes that are different from the CCleaner version and WinappDebug might detect these changes as errors."

**Comment by dvdbane** [comment]
i disagree with this
imo, non-ccleaner or other winapp2.ini should follow official winapp2.ini template so WinappDebug can be run on any winapp2.ini
even if other winapp2.ini don't follow official winap2.ini template and run WinappDebug, just show warning that some error might not accurate

**Comment by MoscaDotTo** [comment]
I will modify WinappDebug to ignore entries below the line `; These entries are the exact same ones located in the Removed entries files`  which should fix the alphabetization issues (in a similar way that it currently ignores alphabetization within the browser/thunderbird sections) 

I think the removed entries should have their names corrected to follow the new " *" naming scheme

Beyond that, any errors still present in the output are probably actual errors, but I would think there shouldn't be many if we're actively updating the "upper" part of the file to be in-line with the CCleaner winapp2.ini's contents

**Comment by MoscaDotTo** [comment]
This work is done. 

WinappDebug fixed in https://github.com/MoscaDotTo/Winapp2/commit/75754900bc1cc834dd6e6a2d6ce728272fc366b6

removed entries fixed in https://github.com/MoscaDotTo/Winapp2/commit/2e054acd6cb6eb329c2204e61c40e44a3fba7b4f

and non cc winapp2 in https://github.com/MoscaDotTo/Winapp2/commit/f7d1673fe89c639cae0dec607e26c5f62b4f91fd
