### ISSUE TITLE
[Winapp2ool] Allow automatically downloading the latest Winapp2

### ISSUE THREAD

**Issue by ROCKNROLLKID** [MoscaDotTo/Winapp2#173]
This will benefit us all in 2 ways:

1. We can create a user-friendly program with Winapp2ool and allow users to download the latest Winapp2, then have options to run trim and Winappdebug.

2. With that being added, we will have a official all-in-one tool, so users will not need to download 3 or more tools (CCenhancer, trim.bat, Winappdebug, etc). 

Also, @ShaneGowland will no longer need to maintain CCenhancer, meaning he can focus more on System Ninja and his other tools (saying this as a good thing). I suppose if he is also up to it, he can either open-source CCenhancer or combine that tool with our new tool. This is of course entirely up to him.

**Comment by TZocker** [comment]
`@echo off
:: Programms:
:: http://gnuwin32.sourceforge.net/packages/wget.htm
:: https://curl.haxx.se/download.html
:: http://waterlan.home.xs4all.nl/dos2unix.html
echo Download winapp2.ini from Github
ping /n 1 raw.githubusercontent.com
if errorlevel 1 goto NOC
echo online

del winapp2.ini
::curl.exe -o Winapp2.ini -A "Mozilla/5.0 (iPhone; U; CPU like Mac OS X; en) AppleWebKit/420+ (KHTML, like Gecko) Version/3.0 Mobile/1A543a Safari/419.3" -G "https://raw.githubusercontent.com/MoscaDotTo/Winapp2/master/Winapp2.ini"

wget.exe -c --output-document=Winapp2.ini "https://raw.githubusercontent.com/MoscaDotTo/Winapp2/master/Winapp2.ini"

unix2dos.exe winapp2.ini

goto end
:NOC
echo no connection

:end
ccleaner.exe

`


use this ^^

**Comment by MoscaDotTo** [comment]
This work is finished in https://github.com/MoscaDotTo/Winapp2/commit/619e41f9cdd3670ce637cc8fb812aa34fd460b0a
