### ISSUE TITLE
[Winapp2ool] Move non-CCleaner download to a different folder

### ISSUE THREAD

**Issue by ROCKNROLLKID** [MoscaDotTo/Winapp2#175]
Currently, if you try to download both Winapp2 and the non-ccleaner, one will overwrite the other. Let's download the non-CCleaner Winapp2 into a folder called Non-CCleaner, so they do not overwrite each other anymore.

**Comment by MoscaDotTo** [comment]
the downloader now prompts for a rename / confirm overwrite when a file already exists
