### ISSUE TITLE
[Non-CCleaner] Overhaul removed entries

### ISSUE THREAD

**Issue by ROCKNROLLKID** [MoscaDotTo/Winapp2#179]
In the near future, I will be doing a overhaul of the removed entries, comparing it with CCleaners winapp and removing some of the really old ones that are no longer necessary, like tag&rename 3.7, which is a really outdated version and has already seen several updated versions.

**Comment by CSGalloway** [comment]
Has there been a dropped program/application?  One that does not include any version updates ....?

**Comment by ROCKNROLLKID** [comment]
A few during the 2nd overhaul and some I may have missed overtime.

**Comment by ROCKNROLLKID** [comment]
For the record, I started the overhaul, but it is going to be a kind of on and off thing since I am kind of busy with life. I will work on bits of it during my free time. IT should not take as long as overhauling Winapp2 since there are only ~55 entries.

**Comment by ROCKNROLLKID** [comment]
Done. I finished sooner then I expected. A change log can be found here: https://github.com/MoscaDotTo/Winapp2/commit/be9cad619e8cf7db1562e41543240e7bc63448bf
