### ISSUE TITLE
Windows 10 last used start menu programs?

### ISSUE THREAD

**Issue by winapp2** [MoscaDotTo/Winapp2#18]
Windows 10 last used start menu programs?

We should find the place of these programs and these to winapp2.ini

**Comment by ROCKNROLLKID** [comment]
These are already cleaned in CCleaner and BleachBit, as far as I am concerned.

**Comment by winapp2** [comment]
No, I'm using latest CCleaner and winapp2.ini and the most last used start menu programs appear in the start menu list as the first entries.

**Comment by winapp2** [comment]
Perhaps it's this entry:

HKEY_CURRENT_USER\SOFTWARE\Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppModel\SystemAppData\Microsoft.Windows.ShellExperienceHost_cw5n1h2txyewy\PersistedStorageItemTable\MostRecentlyUsed

**Comment by winapp2** [comment]
http://www.tenforums.com/tutorials/6460-start-menu-most-used-apps-add-remove-windows-10-a.html
