### ISSUE TITLE
[WinappDebug] Issue with last entry

### ISSUE THREAD

**Issue by APMichael** [MoscaDotTo/Winapp2#181]
WinappDebug doesn't find alphabetization errors in the last entry of a winapp2.ini file if there are not at least 2 new lines after the last entry.

**Comment by ROCKNROLLKID** [comment]
Does this also happen with the WinappDebug in Winapp2ool?

**Comment by APMichael** [comment]
I'm sorry, I don't know. I didn't try Winapp2ool until now.

**Comment by MoscaDotTo** [comment]
Testing on my end suggests that this isn't a problem in winapp2ool

**Comment by APMichael** [comment]
Ok, thanks for testing. Then I will switch to the new Winapp2ool.

**Comment by MoscaDotTo** [comment]
FWIW the WinappDebug module in Winapp2ool does have other bugs. I have a variety of them addressed in a build that will be out soon.

**Comment by MoscaDotTo** [comment]
I've updated Winapp2ool to include a wide variety of fixes across all modules, I'm going to close this for now since this doesn't seem to be an issue with the WinappDebug module
