### ISSUE TITLE
Windows Installation Files

### ISSUE THREAD

**Issue by winapp2** [MoscaDotTo/Winapp2#19]
We should add Windows old installation files:

1.) "$Windows.~BT"

2.) "$windows. ws"

These both can store up to a few gigabytes and most people don't know of their existence. They seem to be in cleanmanager of windows too sometimes, but sometimes it even doesn't recognize it.

**Comment by ROCKNROLLKID** [comment]
Agreed. I actually suggested this over to BleachBit, so I think they are going to add it in their own program. Perhaps maybe the other cleaners can do the same.

Do you know where these are actually kept?

**Comment by winapp2** [comment]
These both are kept in Root directory "C:" 

Or let's call it "%SystemDrive%"

**Comment by ROCKNROLLKID** [comment]
Ah, you mean Windows.old, like after you upgrade. I noticed on my system, Windows doesn't let you delete these files. You need to use Windows build in cleaner to remove them, at least that's the only way I been able to.

**Comment by winapp2** [comment]
CCleaner does somehow have these privileges too.

**Comment by ROCKNROLLKID** [comment]
So CCleaner already has this entry in it? If so, we can add this to the other Winapp2 file for other cleaners to use. BleachBit and System Ninja currently don't clean these files out.

**Comment by winapp2** [comment]
No CCleaner doesn't have this entries, but as far as I know it has system level permissions for deleting such folders. It's very strange, how this is even possible. You might try to make these two entries and try it for yourself, as you have these folders.

**Comment by winapp2** [comment]
%SystemDrive%/

**Comment by winapp2** [comment]
%SystemDrive%\$Windows.~BT

%SystemDrive%\$Windows.~WS

**Comment by ROCKNROLLKID** [comment]
No I don't have these files anymore. As I said, I have to use Windows built in cleaner to get rid of them.

Mine was just called C:\Windows.old. Did you have more then one drive when you upgraded?

**Comment by winapp2** [comment]
Windows.old is different folder. 

These two folders are created only if you upgrade your windows by ISO or Media creation tool without formating your drive. 

We should add Windows.old too for other cleaners, perhaps it's in Winsys2.ini as far as I recall.
