### ISSUE TITLE
[Bug] In-File Cleaning not supported

### ISSUE THREAD

**Issue by winapp2** [MoscaDotTo/Winapp2#2]
In-File Cleaning not supported now. Perhaps other cleaners will support it for Winapp2.ini

**Comment by CSGalloway** [comment]
Not sure what is meant by "In-File cleaning" ?

http://www.facebook.com/CSGalloway

**Comment by winapp2** [comment]
In-File-Cleaning means, that you can delete a content from a file without the need to delete the whole file.

**Comment by winapp2** [comment]
CCleaner doesn't support it, but other cleaners could be easily be able to clean.

**Comment by winapp2** [comment]
Really, this is needed for IrfanView and Vlc Player Mru. Hope Bleachbit or others will support this.

**Comment by CSGalloway** [comment]
Such as an entry in a INI file?

http://www.facebook.com/CSGalloway

**Comment by winapp2** [comment]
Yes something like this for example:


[VLC Media Player - Recently Used Files*]
LangSecRef=3023
Detect=HKLM\Software\VideoLAN\VLC
Default=False
FileKey1=%AppData%\vlc\vlc-qt-interface.ini|[RecentsMRL]

"...
[RecentsMRL]
list=file:///XYZ FILE, file:///XYZ File
..."

**Comment by ROCKNROLLKID** [comment]
BleachBit and System Ninja do this, but they don't communicate this through Winapp2, so updates would need to be made for both anyways. I am not aware if Avira System Speed does this or not. As you said CCleaner doesn't do this, so this will just have to wait until they do support this.

Closing issue.

**Comment by winapp2** [comment]
Let's have a System For deleting such entries.
