### ISSUE TITLE
Windows 10 retail demo 

### ISSUE THREAD

**Issue by winapp2** [MoscaDotTo/Winapp2#20]
http://www.askvg.com/tip-hidden-secret-retail-demo-mode-in-windows-10/

This will take about 200 mb. I think we should add it here:

As a detect key we could take one of  this:

HKEY_CLASSES_ROOT\AppID\{ac793c1d-eb2f-4ffd-b1ec-7af1aaaf3325}
HKEY_CLASSES_ROOT\CLSID\{1e46246f-b2ad-4a86-9e08-d0f9e01ee05d}
HKEY_CLASSES_ROOT\ms-retaildemo-launchstart
HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\RetailDemo

But these entries don't indicate anything, because they are there even if the retaildemo isn't there.
We should normally use this regkey for all kind of windows stuff:

**HKEY_CURRENT_USER\SOFTWARE\Microsoft**

Here is it stored:
C:\ProgramData\Microsoft\Windows\RetailDemo\
C:\Windows\SystemApps\Microsoft.Windows.CloudExperienceHost_xx\RetailDemo\

**Comment by ROCKNROLLKID** [comment]
I don't seem to have Retail Demo on my system.

FileKey2 would have to be a wildcard, as it is different for each system. Such as mine is Microsoft.Windows.CloudExperienceHost_cw5n1h2txyewy

By the way, you can make pull requests yourself, too.

**Comment by winapp2** [comment]
The retaildemo stuff appears on different windows 10 builds. I don't know what's triggering it's installation, but it was on mine pc with windows 10 installed too. Now it's not. I'm going to add it sometimes.

**Comment by winapp2** [comment]
Pull request sent. Closing this.

PS:
C:\Windows\SystemApps\Microsoft.Windows.CloudExperienceHost_xx\RetailDemo\

This folder should be staying in windows. Therefore this isn't getting deleted.
