### ISSUE TITLE
[Winapp2ool] Support downloading of Removed Entries.ini

### ISSUE THREAD

**Issue by ROCKNROLLKID** [MoscaDotTo/Winapp2#204]
The only thing Winapp2ool doesn't download, yet, is the Removed Entries.ini for non-CCleaner users. So let's make Winapp2ool do this.

**Comment by MoscaDotTo** [comment]
this is fixed in https://github.com/MoscaDotTo/Winapp2/commit/b74a74319f6da5f550870c6a41283c710be2e293
