### ISSUE TITLE
Remove sticky note cleaning

### ISSUE THREAD

**Issue by MoscaDotTo** [MoscaDotTo/Winapp2#218]
Sticky Notes aren't junk, and there's presumably no/very few situations in which the user wouldn't manually delete unwanted notes themselves.

**Comment by ROCKNROLLKID** [comment]
Sticky noted was removed in this commit: https://github.com/MoscaDotTo/Winapp2/commit/d417dd4c8329b0094126c1f91e4c221b70d87ebf

Closing ticket.
