### ISSUE TITLE
[Winapp2ool/Trim] Support checing against Winapp.ini

### ISSUE THREAD

**Issue by ROCKNROLLKID** [MoscaDotTo/Winapp2#221]
I am not 100% sure if the tool does this already, but I will try to explain it. Currently we keep 2 separate files, 1 for CCleaner and 1 for other cleaners, however, 2 files might not be needed anymore, due to our new naming system. There is still the issue with duplicate cleaners showing up, though. So it would be nice if we can make trim also detect against Winapp1 changes and remove duplicate cleaners from Winapp2.

This would allow us to merge the 2 files together and have 1 global file for everyone, while still keeping the removed entries.

**Comment by MoscaDotTo** [comment]
I think the two files are still needed so that the proper version of winapp2.ini can be downloaded by people not using the winapp2ool.

**Comment by ROCKNROLLKID** [comment]
Yes, you are probably right and it wouldn't be right to make users to additional steps if they don't want/need to.
