### ISSUE TITLE
winapp2ool documentation

### ISSUE THREAD

**Issue by MoscaDotTo** [MoscaDotTo/Winapp2#224]
tracking readme.md work here

**Comment by TZocker** [comment]
Pls choose a Licensing for it. Its new so you have free choice....
greetz

**Comment by ROCKNROLLKID** [comment]
Yes, we are free to license all the winapp2 tool we use here. GNU GPL v3 is probably what we will use.

**Comment by MoscaDotTo** [comment]
I actually think constructing a wiki for both winapp2.ini and winapp2ool is a better approach than individual readme files
