### ISSUE TITLE
Language files

### ISSUE THREAD

**Issue by MoscaDotTo** [MoscaDotTo/Winapp2#226]
It has long been requested (and partially maintained for a small amount of time IIRC) that winapp2.ini support deleting language files. 

Though this will never be the case with the master ini file (for obvious* reasons), I don't see any reason why this shouldn't be an option for people who would like it. A major limitation of language file cleaning has always been the infeasbility of properly maintaining an ini for each language and program. 

This is where winapp2ool.exe comes into play! The underlying components of winapp2ool are object oriented, and this opens up the ability to create a "meta" ini file, and use that file to generate winapp2.ini entries. 

So I have this idea that would allow us to curate an ini file, written in a hybrid winapp2ool/winapp2.ini syntax, that would automatically generate winapp2.ini files that contain entries for a specific language's cleaning.

A rough idea of what I'm thinking (I haven't put any of this to code yet because I just thought of it about half an hour ago and want to query the community before manifesting it) would be something like this:

```
[SomeApplication Language Files *] 
ENGLISHUS=en_us
SPANISH=es
JAPANESE=ja
...

Detect=...
Default=...
FileKey1=%ProgramFiles%\SomeApp|en_US;es;ja|*.*|RECURSE
```

Then using this format for the ini, an application would take in the name of a language and this meta ini and generate winapp2.ini entries for that language. 

eg, the above ini entry and englishus as a language parameter would generate 

```
[SomeApplication Language Files *]
Detect=...
Default=...
FileKey1=%ProgramFiles%\SomeApp|es|*.*|RECURSE
FileKey2=%ProgramFiles%\SomeApp|ja|*.*|RECURSE
``` 

or another way could be through use of ExcludeKeys, for which a similar syntax could be used. (Both could be implemented for maximum flexibility) 

The basic (naive) implementation I envision is that a meta ini is maintained here on the GitHub (by someone who isn't me!) and winapp2ool uses that meta ini to generate custom lang.ini on a per-language basis (if an language isn't specified in a meta entry, it will simply be omitted from the generated set of entries). Those lang.ini files could then be merged with winapp2.ini 

If there's someone(s) in the community who would be interested in maintaining such an ini, I don't think that making this module would be very difficult, and I could probably have it finished rather quickly. If not, I'll just close this bug for now. :)

*because this sort of entry is volatile and could break programs for people who don't closely examine what winapp2.ini is doing

**Comment by MoscaDotTo** [comment]
[babel_TEST.zip](https://github.com/MoscaDotTo/Winapp2/files/1846313/babel_TEST.zip)

**Comment by ROCKNROLLKID** [comment]
It's not a bad idea, but I think it would be better to make another Winapp2 for advanced/more dangerous rules instead. I user long time ago posted an old winsys.ini file with a huge list of rejected/dangerous entries here. I could try digging that up and using that as a base. There has been other entries that have been suggested throughout winapp2, such as cleaning software distribution folder. Lots of installers these days usually let you select the languages you want or automatically detects the language you are and uses that, so I don't really see this tool being used a whole lot.
