### ISSUE TITLE
File name

### ISSUE THREAD

**Issue by Coffee4Joe** [MoscaDotTo/Winapp2#23]
Can "Winapp2.ini (for CCleaner)" be renamed to something like "CCleaner-Winapp2.ini"?

I grab it with powershell's Invoke-WebRequest/Wget and for whatever reason it doesn't like the spaces once put into a .bat

**Comment by ROCKNROLLKID** [comment]
Can you try it now and see if it works.

I renamed it to this because the other Winapp2 file is in the pull request right now for the other cleaners.

**Comment by Coffee4Joe** [comment]
Thanks, It works now.

**Comment by winapp2** [comment]
Perhaps we should make an folder in github for other cleaners winapp2.ini and let the file's have the same name. Because most other cleaners could only recognize Winapp2.ini, if it's actual name is "Winapp2.ini"

**Comment by Coffee4Joe** [comment]
That might be a better option. 

When I grab it with powershell I have it output as  winapp2.ini but if someone's grabbing it off the site they might not know/remember to change it.

**Comment by ROCKNROLLKID** [comment]
Great idea. I renamed it back to Winapp2 and when I publish the other one, I'll put it into a folder.

**Comment by ROCKNROLLKID** [comment]
Closing issue as this has been resolved.
