### ISSUE TITLE
[Winapp2ool] Support Winapp3

### ISSUE THREAD

**Issue by ROCKNROLLKID** [MoscaDotTo/Winapp2#237]
Well Winapp3 is official, however, it is using a different procedure then Winapp2 is. We need to make Winapp2ool compatible with Winapp3 without needing to make special adjustments (like renaming the file). Also, currently Winapp2ool assumes the section of browsers from Winapp2, but this is not needed for Winapp3 (at least not now). Currently, the only section in Winapp3 is language entries for cleaning languages.

**Comment by ROCKNROLLKID** [comment]
Ok, Winapp3 is out of beta now and is stable. There are 2 sections in Winapp3, one for language entries and 1 for entries that take a long time to analyze. This will most likely not be changing, so lets support these sectioning for Winapp3.

**Comment by MoscaDotTo** [comment]
This work is complete and will be in the next winapp2ool update
