### ISSUE TITLE
[Winapp2ool] Support downloading of Winapp3

### ISSUE THREAD

**Issue by ROCKNROLLKID** [MoscaDotTo/Winapp2#238]
Winapp3 is now officially part of Winapp2 community, but Winapp2ool currently does not download Winapp3 automatically.

This should probably wait until Winapp3 is out of beta as the directory will be changed then (currently it's in a folder called beta, but will be moved out once it reaches "stable").

**Comment by MoscaDotTo** [comment]
this work is complete and will be available in the next version of winapp2ool
