### ISSUE TITLE
[Polarity Favicon*] entry issue

### ISSUE THREAD

**Issue by ROCKNROLLKID** [MoscaDotTo/Winapp2#24]
I seen this was once in Winapp2, but was removed due to no FileKeys. Does anyone know what it was suppose to do and maybe can correct it? Below is what it was: 

[Polarity Favicon*]
LangSecRef=3022
DetectFile=%ProgramFiles%\Polarity
Default=False

**Comment by CSGalloway** [comment]
Not sure whart the entry was for -

A few choices from https://www.google.com/#q=polarity%20software

http://www.facebook.com/CSGalloway

**Comment by ROCKNROLLKID** [comment]
Ya, I know it is a web browser, I just don't what this specific entry was suppose to do for it.

Maybe it was just put their by accident.

**Comment by winapp2** [comment]
I have sent this entry to Roberts email, but it seems that there was a bug. If I've time, I'm going to fix it.

**Comment by MoscaDotTo** [comment]
Seems like it's a fork of Chromium, my best guess would be that we're looking for something along these lines in a polarity folder

User Data\*|Favicons;Favicons-journal

**Comment by winapp2** [comment]
No it's not a Chromium based browser, it's a poor browser, it's like ie8.

**Comment by ROCKNROLLKID** [comment]
According to the Sourceforge page, "Polarity is a dual engine browser powered by both Chromium and Trident that focuses on system efficiency by bringing low RAM and low CPU usage."

**Comment by winapp2** [comment]
Might be, but I have used it and it feels like ie8 somehow.

**Comment by ROCKNROLLKID** [comment]
That must be the Trident side of things, since that's the engine for Internet Explorer.

**Comment by winapp2** [comment]
fixed, you can close.
