### ISSUE TITLE
Detect wrong slashes

### ISSUE THREAD

**Issue by ROCKNROLLKID** [MoscaDotTo/Winapp2#249]
A rare occasion, but let's see if we can make Winapp2ool debugger detect wrong slashes being used in FileKeys, RegKeys, Detects, ExcludeKeys, etc. Names can be ignored, since it's not important there.

An example of a entry being used wrong is here: https://github.com/MoscaDotTo/Winapp2/pull/241

**Comment by MoscaDotTo** [comment]
I've completed this work and it'll be available in the next build
