### ISSUE TITLE
Windows Store or Games

### ISSUE THREAD

**Issue by APMichael** [MoscaDotTo/Winapp2#253]
Just a quick question. Following entries are Windows App Store games. Should we use "LangSecRef=3031" (= Windows Store) or "Section=Games" for them?
 
[Angry Birds Space \*]
[Angry Birds Star Wars \*]
[Gravity Guy \*]
[Halo Spartan Assault \*]
[Microsoft Ultimate Word Games \*]
[QuizUp \*]
[Reckless Racing \*]
[Shark Dash \*]
[Shuffle Party \*]
[Team Crossword \*]

**Comment by MoscaDotTo** [comment]
I think we should keep them in Games. There are no existing video game entries in CCleaner, so I feel like it's fine to simply categorize all the games in winapp2.ini as games. To split the ones that fall into this category feels somewhat disorganized from that standpoint.

**Comment by APMichael** [comment]
Thanks for your reply. I fixed the category of those game entries (#254).
