### ISSUE TITLE
Winapp cleaners reset to default programs for no (apparent) reason

### ISSUE THREAD

**Issue by WilliamBeltranC** [MoscaDotTo/Winapp2#262]
I've been using Winapp2 in BleachBit for several years, but recently I noticed after using it, it reset all my files to default and I have to set again all of them. Sadly I don't know which of them are causing this issue, since I've looked over every single warning at checking the options and I couldn't found something related. 

I use BleachBit (current last CI version) in Windows 8.1 64 bits.

Thank you

**Comment by ROCKNROLLKID** [comment]
Have you tried checking entries one at a time to pinpoint where it may be caused? Does this happen with any other cleaner that uses Winapp2 (like CCleaner or System Ninja)?

**Comment by WilliamBeltranC** [comment]
Indeed 'Cached File Extensions' was causing the issue. I don't know if this should happen or it is a bug, but I'd suggest a warning before cleaning since I find it a little annoying to set again all programs for every file (mp3, txt, rar, etc.).

Thanks (to both of you).

**Comment by APMichael** [comment]
Thanks for your reply. Do you automatically or manually import the Winapp2.ini file?

Because the entry was revised 2017: [Piriform Community Forums](https://forum.piriform.com/topic/32310-winapp2ini-additions/?page=248&tab=comments#comment-282387).

**Comment by APMichael** [comment]
Interesting! I checked the registry only and the removed RegKey doesn't even exist on my Windows 10 (1709). That's why I thought that the entry could be dangerous.

Maybe we should add the old warning: "Can cause issues on Windows 8.1"? Or something like: "This possibly clears the default program association of all file types."?

**Comment by ROCKNROLLKID** [comment]
Yes, this must be an issue with Windows 8.1 as I am not seeing this issue on my win10 or win7 drive. Maybe a warning stating this will reset default programs back to default on Windows 8.

**Comment by APMichael** [comment]
Thanks. I added the Warning (#265).
