### ISSUE TITLE
Revise documentation to point to winapp2ool's trim module instead of trim.bat

### ISSUE THREAD

**Issue by MoscaDotTo** [MoscaDotTo/Winapp2#263]
The trim module in winapp2ool is definitely developed enough to replace trim.bat, less confusing, and doesn't rely on CCleaner. Pointing users towards it instead of trim.bat will be less confusing, and transition users towards a product whose code I wrote (Alan_B on the Piriform Forums wrote trim.bat in 2012 or so and I don't personally understand how it works) 

I think for now we can simply change the wording in the file and on the readme to point towards winapp2ool, and specifically to the Trim module's documentation once it exists.

**Comment by ROCKNROLLKID** [comment]
I was kind of waiting until Winapp2ool was out of beta phase before suggesting users to start using it, but I am alright with this if you think trim in Winapp2ool is stable and stuff.

**Comment by MoscaDotTo** [comment]
Trim's basic functionality has been at parity with trim.bat for a long time (and doesn't contain a strange trim.bat bug that results in small numbers of false positives sometimes). The more recent options to download the latest file and trim it in one go make it feel like the better option for users to me, especially given how technical trim.bat appears to be.

0.85b is just a few small bits short of where I'd like to be before considering winapp2ool not-beta, so I think  it's okay to begin directing users towards it now, at least for this purpose.

**Comment by ROCKNROLLKID** [comment]
Ok. I will be working on doing that this week.

After Winapp2ool hits stable, I think we can remove the older tools from GitHub (except for CCDump) as they will no longer be needed.

**Comment by ROCKNROLLKID** [comment]
Closing as the documentation points to Winapp2ool now.
