### ISSUE TITLE
New Items

### ISSUE THREAD

**Issue by gameb0y** [MoscaDotTo/Winapp2#272]
Can you add into cleaning list?
https://raw.githubusercontent.com/MoscaDotTo/Winapp2/master/Winapp2.ini

Cent Browser
www.centbrowser.com

Epic Privacy Browser
www.epicbrowser.com

Recently Connected Disks
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\MountPoints2\CPC\Volume

WDI Diagnostics Logs
C:\Windows\System32\wdi\*.*
C:\Windows\SysWOW64\wdi\*.*

Cached Applications Compatibility Information
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\AppCompatCache
HKEY_LOCAL_MACHINE\SYSTEM\ControlSet002\Control\Session Manager\AppCompatCache

Reliability Monitoring Traces
C:\ProgramData\Microsoft\RAC\*.*

USB history
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Enum\USB
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Enum\USBSTOR

C:\Users\USERNAME\AppData\Local\Microsoft\Windows\WebCache\*.*

C:\ProgramData\Microsoft\Diagnosis\ETLLogs\*.*

Recently accessed application files and actions
C:\Users\USERNAME\AppData\Roaming\Microsoft\Windows\Recent\CustomDestinations
C:\Users\USERNAME\AppData\Roaming\Microsoft\Windows\Recent\AutomaticDestinations

DRM Traces
C:\ProgramData\Microsoft\Windows\DRM\Cache

BITS Logs
C:\ProgramData\Microsoft\Network\Downloader\qmgr0.dat
C:\ProgramData\Microsoft\Network\Downloader\qmgr1.dat

WinSAT Shader Cache
C:\Windows\Performance\WinSAT\ShaderCache.ps_2_0
C:\Windows\Performance\WinSAT\ShaderCache.vs_1_1
C:\Windows\Performance\WinSAT\ShaderCache10.ps_4_0
C:\Windows\Performance\WinSAT\ShaderCache10.vs_4_0

Windows Explorer Thumb Cache
C:\Users\USERNAME\AppData\Local\Microsoft\Windows\Explorer\*.db

SoftwareDistribution Logs
C:\Windows\SoftwareDistribution\DataStore\Logs\*.chk
C:\Windows\SoftwareDistribution\DataStore\Logs\*.log
C:\Windows\SoftwareDistribution\DataStore\Logs\*.jrs
C:\Windows\SoftwareDistribution\DataStore\DataStore.edb
C:\Windows\SoftwareDistribution\ReportingEvents.log

Startup File Renaming Log
C:\Windows\PFRO.log

Cryptographic Services Traces
C:\Windows\System32\catroot2\*.log
C:\Windows\System32\catroot2\*.jrs
C:\Windows\System32\catroot2\*.edb
C:\Windows\System32\catroot2\*.chk
C:\Windows\System32\catroot2\dberr.txt

C:\Windows\System32\wfp\wfpdiag.etl
C:\Users\USERNAME\AppData\Local\Microsoft\Windows\Explorer\ExplorerStartupLog.etl
C:\Users\USERNAME\AppData\Local\Microsoft\Windows\Explorer\ExplorerStartupLog_RunOnce.etl
C:\Windows\System32\umstartup.etl
C:\Windows\System32\LogFiles\WMI\RtBackup\EtwRTEventLog-Application.etl
C:\Windows\System32\LogFiles\WMI\RtBackup\EtwRTEventlog-Security.etl
C:\Windows\System32\LogFiles\WMI\RtBackup\EtwRTEventLog-System.etl
C:\Windows\System32\LogFiles\WMI\RtBackup\EtwRTUBPM.etl
C:\Windows\Prefetch\ReadyBoot\ReadyBoot.etl
C:\Windows\WindowsUpdate.log
C:\Users\USERNAME\AppData\Local\Microsoft\Windows\UsrClass.dat.LOG1
C:\Users\USERNAME\AppData\Local\Microsoft\Windows\UsrClass.dat.LOG2

C:\Users\USERNAME\AppData\Local\IconCache.db
C:\Users\USERNAME\AppData\Local\GDIPFONTCACHEV1.DAT

C:\Windows\System32\winevt\Logs\*.*

C:\ProgramData\Microsoft\Windows\Caches\*.*
C:\ProgramData\Microsoft\Windows\DeviceMetadataStore\*.*
C:\ProgramData\Microsoft\Windows\Power Efficiency Diagnostics\*.*
C:\ProgramData\Microsoft\Windows\Sqm\*.*

Elevated Diagnostics Information
C:\Users\USERNAME\AppData\Local\ElevatedDiagnostics\*.*

C:\Windows\AppCompat\Programs\*.*
C:\Windows\winsxs\ManifestCache\*.*
C:\Windows\Panther\*.*

Performance Logs and Alerts (PLA)
C:\Windows\PLA\*.*

C:\Users\USERNAME\AppData\Local\Microsoft\Windows\Caches\*.*

HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\MuiCache\*.*

HKEY_CURRENT_USER\Software\Classes\Local Settings\MuiCache\*.*

HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\BagMRU\*.*

HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\Bags\*.*

HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\RunMRU\*.*

HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\ComDlg32\*.*

HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\RecentDocs\*.*

HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\UserAssist\*.*

HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Applets\Regedit LastKey

HKEY_CURRENT_USER\Software\Microsoft\Search Assistant\ACMru\*.*

HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\TypedPaths\*.*

HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Map Network Drive MRU\*.*

HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\PrnPortsMRU\*.*

HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\StreamMRU\*.*

HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\FindComputerMRU\*.*

HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Doc Find Spec MRU\*.*

HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Applets\Paint\Recent File List\*.*

HKEY_CURRENT_USER\Software\Microsoft\DirectInput\*.*

HKEY_CURRENT_USER\Software\Microsoft\Direct3D\*.*

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\*.*

HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers\*.*

**Comment by APMichael** [comment]
Thanks for your suggestions. But please provide complete Winapp2 entries, not just the files and registry keys. And please check that the entries are not already included in Winapp2, Winapp3 or CCleaner and that the entries aren't dangerous! Also keep in mind that Windows recreates some files immediately after deletion or that Windows protects some files from deletion.

For example:
Recently Connected Disks - in Winapp3 already.
WDI Diagnostics Logs - in Winapp2 already.
Cached Applications Compatibility Information - in Winapp2 already.
Reliability Monitoring Traces - in Winapp2 already.
...Microsoft\Windows\WebCache\\*.\* - cleaned by CCleaner already.
Recently accessed application files and actions - in Winapp2 already.
DRM Traces - in Winapp2 already.
BITS Logs - in Winapp2 already.
WinSAT Shader Cache - in Winapp2 already.
... and so on.

**Something important:** GitHub uses "Styling with Markdown". Therefore, you have to escape some special characters with a backslash \\. The special characters are for example the asterisk \* and the backslash \\ itself (escaping: \\\* or \\\\). Without escaping many of your paths and keys are wrong and dangerous!
