### ISSUE TITLE
Adobe premiere media cache

### ISSUE THREAD

**Issue by Symbai** [MoscaDotTo/Winapp2#273]
Can you add the adobe media cache  folder? It can easily take 20-60GB and its currently not included in Adobe CC*

AppData\Roaming\Adobe\Common\Media Cache Files

**Comment by ROCKNROLLKID** [comment]
That is already included in Winapp3 under [Adobe Media Cache *].

It was remove because this: https://forum.piriform.com/topic/32310-winapp2ini-additions/?page=287&tab=comments#comment-293507
