### ISSUE TITLE
SpecialDetect (and Chrome/Chromium entries)

### ISSUE THREAD

**Issue by APMichael** [MoscaDotTo/Winapp2#274]
I noticed that entries using a SpecialDetect ignore additional Detect and DetectFile lines! Therefore, we can't use them together. The big problem is that all browser entries mix a SpecialDetect with Detect/DetectFile currently and that we need an idea how to split up them now. Or we have to tell the Winapp2 users that they need to install the corresponding "root browser" (Google Chrome, Mozilla Firefox) always.

We could make separate entries with the same name but with a suffix, like CBB (=Chromium-based browser). For example: [Local Storage CBB \*].

Does anybody know which browsers are detected by SpecialDetect=DET_CHROME? Google Chrome only?

Maybe we can separate the browsers that are primarily made for non-English users (7Star, 360Browser, Amigo, CocCoc) also? For example:  [Local Storage CBB-NE \*].

The browsers Flock and Rockmelt are officially discontinued. Shouldn't we remove them? Using an outdated browser is a massive security flaw. Coowon and ChromePlus/CoolNovo seems to be discontinued also.

**Comment by APMichael** [comment]
I tested CCleaner only. I noticed this behavior because in Windows 10 there is a "HKCU\Software\Chromium" registry key always, but CCleaner didn't show the Chrome/Chromium entries.

An alternative to fix it: We could just replace the SpecialDetect with the registry key of Google Chrome and Mozilla Firefox. (Or with the path of the profile folder.)

**Comment by ROCKNROLLKID** [comment]
Let's discuss if we should support outdated/discontinued software here: https://github.com/MoscaDotTo/Winapp2/issues/275

**Comment by MoscaDotTo** [comment]
Do the registry keys work if you place them before the specialdetect in the entry? CCleaner seems to read entries line-by-line when evaluating detections

**Comment by APMichael** [comment]
I tried this already. But unfortunately, it doesn't work also.

**Comment by MoscaDotTo** [comment]
Yes, I would think we should try to maintain the most recent paths for any softwares (particularly complex ones like browsers) that we wish to support.
