### ISSUE TITLE
T-Online Browser

### ISSUE THREAD

**Issue by winapp2** [MoscaDotTo/Winapp2#28]
http://www.chip.de/downloads/t-online.de-Browser-7-Telekom-Browser_69871151.html

Seems to be based on Chromium

**Comment by TZocker** [comment]
i read firefox xd

but where had installed so much spam.

**Comment by winapp2** [comment]
If it's Firefox or chrome we can easily make an entry through a Standart mask. Because of the gecko or webkit (blink) engine they use, these browsers have an Standart even for temporary files...
