### ISSUE TITLE
[Winapp2ool/Trim] DetectFile with wildcard

### ISSUE THREAD

**Issue by APMichael** [MoscaDotTo/Winapp2#281]
Report from **siliconman01** of the community:

"For some reason, the TRIM function of winapp2ool.exe (V0.8.0.0) does not recognize the DetectFile shown below for Chrome and it trims these all out.
DetectFile2=%LocalAppData%\\Google\\Chrome\*
If I change this to DetectFile2=%LocalAppData%\\Google\\Chrome, then they are not TRIMMED out."

I can confirm this behavior, too.

**Comment by MoscaDotTo** [comment]
This one was an easy fix! :) I will update winapp2ool soon with a major update that will include this.

**Comment by APMichael** [comment]
Good news! Thank you for your fast reply.

**Comment by APMichael** [comment]
Fixed! Thanks for the update!
