### ISSUE TITLE
[Winapp2ool] Update check and decimal point

### ISSUE THREAD

**Issue by APMichael** [MoscaDotTo/Winapp2#285]
Found a little bug caused by the decimal point on non-English systems: On many non-English systems the decimal point is a comma instead of a point. The update check seems to be confused by that comma and reports a new version.

![grafik](https://user-images.githubusercontent.com/33252157/41499680-51a8f6f2-7184-11e8-9d34-ed773ae05562.png)

**Comment by EvgenKo423** [comment]
Also here is what happens when running Winapp2ool.exe on a non-English OS for the first time (translated):
> Uncaught exception: System.InvalidCastException: String cast "0.85" to type "Double" is invalid. ---> System.FormatException: Input string had an invalid format.
>    in Microsoft.VisualBasic.CompilerServices.Conversions.ParseDouble(String Value, NumberFormatInfo NumberFormat)
>    in Microsoft.VisualBasic.CompilerServices.Conversions.ToDouble(String Value, NumberFormatInfo NumberFormat)
>    --- End trace of inner stack exceptions ---
>    in Microsoft.VisualBasic.CompilerServices.Conversions.ToDouble(String Value, NumberFormatInfo NumberFormat)
>    in winapp2ool.Winapp2ool.checkUpdates()
>    in winapp2ool.Winapp2ool.main()

Win 7 x64 Rus

**Comment by MoscaDotTo** [comment]
This should be addressed in the next version of winapp2ool.

**Comment by APMichael** [comment]
Seems to be fixed: Winapp2ool starts flawless now and doesn't report the new "comma" version anymore.
