### ISSUE TITLE
[Feature Request] winapp2 for Linux

### ISSUE THREAD

**Issue by zero77** [MoscaDotTo/Winapp2#293]
Can you please create a winapp2 for Linux.
Thanks

**Comment by APMichael** [comment]
The Winapp2.ini file uses the syntax/language of CCleaner. Therefore, I think that there is no cleaner for Linux available which supports the Winapp2.ini format.

Maybe you can ask the BleachBit for Linux community, if someone offers additional cleaning rules.

**Comment by zero77** [comment]
Yes good idea,  https://github.com/bleachbit/winapp2.ini/issues/13

**Comment by ROCKNROLLKID** [comment]
Unfortunately, creating a *nix port of Winapp2 would be starting all over. I no longer have a Linux system anymore, so I am unable to do it. Andrew (owner of BleachBit) already has something called CleanerML, where he makes his own cleaning rules. You can always contribute to that.

https://github.com/az0/cleanerml
