### ISSUE TITLE
[BlueStacks SharedFolder] should not be included

### ISSUE THREAD

**Issue by Austin-RR** [MoscaDotTo/Winapp2#295]
I believe the [BlueStacks SharedFolder] option should not be included in Winapp2.

The Bluestacks Shared Folder is a folder created for the purpose of sharing user files between the host O/S and the Bluestacks O/S.  Nearly every file in this folder is a file that has been deliberately placed there by the user.  It is not a folder created to contain only files automatically generated by the system or any program - which is what CCleaner is generally designed to clean.  I have a shortcut to this folder on my Desktop because I access it so many times to place files there.

I once had over 100 files in the folder that I deliberately placed there myself.  I was very fortunate to realize that CCleaner with Winapp2 was going to delete all the files I placed there before I initiated CCleaner to clean everything.

Thanks for the work on this project!

**Comment by APMichael** [comment]
Done! Thanks for your clarification.
