### ISSUE TITLE
[Enhancement] Adding back removed entries, which are in CCleaner now

### ISSUE THREAD

**Issue by winapp2** [MoscaDotTo/Winapp2#3]
[Enhancement] Adding back removed entries, which are in CCleaner now.

There should be combined entries for other cleaners.

**Comment by ROCKNROLLKID** [comment]
I sent you the modified file of Winapp2 that includes all the removed entries due to CCleaner (as late as 3 years ago, anything beyond that is/was out of my reach).

**Comment by winapp2** [comment]
Where do you sent?

**Comment by winapp2** [comment]
I'm not winapp2.ini aka Robert.

**Comment by winapp2** [comment]
This has been resolved by @ROCKNROLLKID
