### ISSUE TITLE
Winapp2-EXTRA GENERAL.txt

### ISSUE THREAD

**Issue by winapp2** [MoscaDotTo/Winapp2#30]
https://github.com/MoscaDotTo/Winapp2/issues/6/

This file contains a lot of entries we should add after my pulls are sent. There's much. Please can somebody check it later.

**Comment by TZocker** [comment]
OK  my opion:
e.g.
installation on systemres normal? c?
also delting install logs is hard, unstallation works ?

[EuroSYSTEMS CoCut Standart 2011*]

looks good but DEction over file? diffrence between standart and pro

some entries are ok but not the best way sometimes or more testin needed.

also cleaning files in installating folder (i make a discussing about it)

**Comment by ROCKNROLLKID** [comment]
Agreed. This needs more testing and tuning before I can merge it to the master branch.

**Comment by winapp2** [comment]
We should take the known entries. Like the check disk log entry. It's very good.
