### ISSUE TITLE
[Winapp2ool/TrimXP] Error when choosing save file directory

### ISSUE THREAD

**Issue by EvgenKo423** [MoscaDotTo/Winapp2#302]
**Reproduce steps:**
1. Run `TrimXP.exe`;
2. Choose `5`;
3. Choose `3`.

**Result (translated):**
> Uncaught exception: System.ArgumentException: You should call "Dir" function with "Pathname" argument first.
>    in Microsoft.VisualBasic.CompilerServices.IOUtils.FindNextFile(Assembly assem)
>    in Microsoft.VisualBasic.FileSystem.Dir()
>    in TrimXP.iniFileHandler.fileChooser(iniFile& someFile)
>    in TrimXP.TrimXP.changeFileParams(iniFile& someFile, Boolean& settingsChangedSetting)
>    in TrimXP.TrimXP.main()

**Comment by MoscaDotTo** [comment]
TrimXP is going to be deprecated in favor of a fully functional winapp2oolXP built from the same code as winapp2ool but with a lower .NET requirement, so I'm going to close this as I don't intend to fix it unless it's also an error in winapp2ool

**Comment by MoscaDotTo** [comment]
My advice in the meantime if you need this functionality is to place winapp2ool.exe in the folder you would normally have chosen using this option
