### ISSUE TITLE
Corsair ICue Logs

### ISSUE THREAD

**Issue by PlNG** [MoscaDotTo/Winapp2#303]
I found 3 files: Service_Trace.log, Service_Trace.0.log, Service_Trace.1.log
Each were almost 100Mb and ***millions*** of lines in size.

The logs are full of these pairs of lines.
`timestamp | \d\d | INFO: DevicesMonitor | TIME = \d\d\d\d(avg: \d\d\d\d\.\d\d) ms `
`timestamp | \d\d | INFO: DevicesMonitor | Devices: \d(\d+ sens.) `
I have no idea why it is polling and logging as debug output each second as a default setting.

Here's an entry:

[Corsair iCue Logs \*]
LangSecRef=3024
DetectFile=%CommonAppData%\Corsair\CUE\Service logs\\*.log
Default=False
FileKey1=%CommonAppData%\Corsair\CUE\Service logs|Service_Trace\*.log
Warning=You should turn off Debug Logging in iCue to prevent these files from reappearing.

**Comment by MoscaDotTo** [comment]
@APMichael I don't recall, does CCleaner support wildcard file parameterizations in the DetectFile key? 

Otherwise, I would tweak the warning to something less suggestive and more informative 

eg. Disabling 'Debug Logging' in iCue will prevent these files from being recreated. 

Thanks for the contribution :)

**Comment by APMichael** [comment]
Thank you for the new entry. I opened a new pull request.

@MoscaDotTo Yes, it should work.

**DetectFile and wildcard:**
It works very limited. A wildcard works only on the last foldername or filename of a path.

**Work:**  
DetectFile=%ProgramFiles%\\Test\*  
DetectFile=%ProgramFiles%\\Te\*t1  
DetectFile=%ProgramFiles%\\Test1\\program\*.exe

**Don't work:**  
DetectFile=%ProgramFiles%\\Test\*\\  
DetectFile=%ProgramFiles%\\Test\*\\program.exe  
DetectFile=%ProgramFiles%\\\*\\program.exe
