### ISSUE TITLE
Icon of the trash ...

### ISSUE THREAD

**Issue by PiliJ** [MoscaDotTo/Winapp2#310]
Hi,
Since some versions of Ccleaner (with both the exe version and the portable), I noticed that the icon of the trash did not become empty anymore. I am under Win 8.1.
After some research, it seems that the presence of the file winapp2.ini in the folder of Ccleaner would be responsible.
Is there a way to fix this?
Thank you

**Comment by APMichael** [comment]
I can guess only. There's one entry that could affect the Windows icons: [Icon Cache \*]. Please untick that entry.

If that doesn't help, you could untick all Winapp2.ini entries and then test them one by one until you found the culprit.

**Comment by PiliJ** [comment]
Problem solved ! Thanks again.

**Comment by APMichael** [comment]
Great! Thanks for your reply.
