### ISSUE TITLE
Secunia PSI is EOL and non-functional. Should the rule be removed or changed?

### ISSUE THREAD

**Issue by PlNG** [MoscaDotTo/Winapp2#312]
[Secunia PSI is EOL as of April 2018](https://www.flexera.com/products/software-vulnerability-management/personal-software-inspector.html)

Should the rule be removed or changed?

**Comment by APMichael** [comment]
Yes, I think we can remove the entry. The software is useless without the update servers.

Thanks for the tip!

**Comment by APMichael** [comment]
Done!
