### ISSUE TITLE
Add support for Wire Desktop app

### ISSUE THREAD

**Issue by tailHey** [MoscaDotTo/Winapp2#314]
Hello there!

Since Wire Desktop app is a web wrapper based on Electron, I wondered if there're removable local files (like cache) through Winapp2 without interfering with its functionalities (for instance, still being able to regenerate cache and chat history at app launch and so on).

Thanks in advance for considering this request, keep up the good work!

**Comment by APMichael** [comment]
Thank you for your suggestions. But please provide complete and tested Winapp2 entries. Unfortunately, we are not able to install and test new applications for you. Thank you for your understanding.
