### ISSUE TITLE
Add support for myTube! app

### ISSUE THREAD

**Issue by tailHey** [MoscaDotTo/Winapp2#315]
Hello there!

Among Microsoft Store apps that could benefit from cleaning some local files, myTube! is a good candidate. With a custom rule I'm using to clean Microsoft Store apps cache I guess I already got a workaround, but I wouldn't mind having a dedicated entry for it, and it could also benefit other Winapp2.ini users!

Thanks in advance for considering that feature request, and keep up the good work!

**Comment by APMichael** [comment]
Thank you for your suggestions. But please provide complete and tested Winapp2 entries. Unfortunately, we are not able to install and test new applications for you. Thank you for your understanding.
