### ISSUE TITLE
New Entry - Wire

### ISSUE THREAD

**Issue by tailHey** [MoscaDotTo/Winapp2#321]
Hello there.

This rule should clean cache files generated by Wire Desktop app:

```
[Wire *]
LangSecRef=3022
DetectFile=%LocalAppData%\wire
Default=False
FileKey1=%AppData%\Wire\Cache|*.*
FileKey2=%AppData%\Wire\GPUCache|*.*
```

Thanks in advance, keep up the good work!

**Comment by tailHey** [comment]
Some * disappeared in the copy-paste, will try to fix it

**Comment by APMichael** [comment]
Thank you for the new entry. I opened a new pull request.

**Comment by tailHey** [comment]
Hello there.

I'd like you to update Wire entry as following:

`[Wire *]
LangSecRef=3022
DetectFile=%LocalAppData%\wire
Default=False
FileKey1=%AppData%\Wire\Cache|*.*
FileKey2=%AppData%\Wire\GPUCache|*.*
FileKey3=%AppData%\Wire\Service Worker|*.*|REMOVESELF`

Thanks in advance, keep up the good work!

**Comment by APMichael** [comment]
Thank you for the revised entry. I will add it with the next update.
