### ISSUE TITLE
We are breaking Cortana 

### ISSUE THREAD

**Issue by MoscaDotTo** [MoscaDotTo/Winapp2#327]
I got this message on the piriform forums:

```
Cortana search is weakened/breaks ( finds shortcuts but not settings ) if cortana is checked in CCEnhancer.

Cortana database does not regenerate itself once deleted and the only way to restore is to create a new user and copy the cortana files over to the old user account.

Is that intentional?
```

It's not intentional, I wouldn't think. I don't use Cortana and wouldn't notice if she broke.

**Comment by APMichael** [comment]
Unfortunately, I also disabled Cortana. And I don't see any suspicious FileKey. The entry only cleans up the usual cache folders. (BTW FileKey9 isn't necessary because it's already covered by FileKey6.)

If he can't tell us which files to exclude, it's hard to fix.

**Comment by APMichael** [comment]
I think I found the culprit. The files in the folder "\LocalState\DeviceSearchCache" shouldn't be deleted. Especially the file "SettingsCache.txt" won't be rebuild, so the settings search is broken. The other files "AppCache###.txt" will be rebuild, but deleting these files will cause strange problems with the app search.
