### ISSUE TITLE
Chrome CrashpadMetrics TMP files

### ISSUE THREAD

**Issue by akaleeroy** [MoscaDotTo/Winapp2#328]
Found 204MB of `CrashpadMetrics.pma~RFe4e1f.TMP` files in `%LocalAppData%\Google\Chrome\User Data` (195 files 1,048,576 bytes each)

Maybe they should be included.

**Comment by APMichael** [comment]
Thanks for your information. But this is not necessary because CCleaner removes .tmp files already (Google Chrome - Internet Cache).

![grafik](https://user-images.githubusercontent.com/33252157/49886245-6bcd2e80-fe39-11e8-8b4a-3accc5db49d4.png)

**Comment by akaleeroy** [comment]
So it's just BleachBit that doesn't clean these apparently.

**Comment by APMichael** [comment]
Seems so. You can use the "Non-CCleaner" version of Winapp2.ini as a workaround:
https://github.com/MoscaDotTo/Winapp2/blob/master/Non-CCleaner/Winapp2.ini
This file contains many removed entries. The entry [Chrome Temp Files Extras *] is the one you need.
