### ISSUE TITLE
Readme file

### ISSUE THREAD

**Issue by winapp2** [MoscaDotTo/Winapp2#33]
You need to link to the important things in the readme file like winsys2.ini and the helping guide (which is currently in Pull request.)

**Comment by TZocker** [comment]
nice idear but winsys is a bit unofficial, its on my dropbox but we have to spent a bit mor time on it to make a suitible file.
but we have to diskuss that we start a seperrate github for it or not .

**Comment by winapp2** [comment]
We should drop from Dropbox and add here :D
