### ISSUE TITLE
6. Downloader suggestion

### ISSUE THREAD

**Issue by CSGalloway** [MoscaDotTo/Winapp2#333]
It is possible to download the same named file files (winapp2.ini) into the same folder.  Might be better if this was handled better.  Also can the "Change the Save Directory" be saved and restored between runs please?

**Comment by MoscaDotTo** [comment]
A prompt to overwrite or provide a new file name should be shown when downloading files that already exist in a directory 
![image](https://user-images.githubusercontent.com/529203/50048243-cb734600-0094-11e9-93e5-9d4358ebba14.png)

**Comment by MoscaDotTo** [comment]
Closing this for now. The prompt should prevent any accidental overwrites, saving settings between winapp2ool sessions isn't currently supported (would require either saving to the registry or to a file, I haven't yet considered the implementation of this) but will probably be a feature at a later date. 

FWIW anywhere you see `..` is actually short hand for your current directory, eg if you launched winapp2ool from `C:\winappool` then any instance of `C:\winapp2ool` will be truncated to `..` so the console doesn't get cluttered. If you intend to download to the current directory, you don't need to modify the save destination.
