### ISSUE TITLE
Download latest winaptool

### ISSUE THREAD

**Issue by CSGalloway** [MoscaDotTo/Winapp2#347]
The program keeps telling me i am using v181216 but that 181220 is available so I keep downloading the latest (6, then 3) so it does not seem to be downloading the latest?

**Comment by MoscaDotTo** [comment]
long form version numbers v181216 or v181220 are for winapp2.ini, the current version of winapp2ool is 1.0. 

A prompt should be displayed on the main menu when updates are available that negates the need to go into the Downloader to fetch updates.
