### ISSUE TITLE
Avira System Speedup

### ISSUE THREAD

**Issue by ROCKNROLLKID** [MoscaDotTo/Winapp2#35]
So, I notified System Ninja and BleachBit communities that Winapp2 is now on GitHub, but I can't seem to find a way to notify Avira System Speedup community. They seem to want you to pay in order to contact any of their staff. I also can't seem to find a forums or anything.

Does anyone own a Avira product or know of a way to contact them so we can inform them we moved to GitHub and to make sure they use the Non-CCleaner version of Winapp2 instead of the old one?

**Comment by TZocker** [comment]
I would send an email to  info@avira.de

but is very hard to find something...

**Comment by ROCKNROLLKID** [comment]
I go ahead and try that email, but I think that is just the information center email.

**Comment by MoscaDotTo** [comment]
Someone from Avira once e-mailed me, and I am a member of their beta program, I'll see if I can get in touch

**Comment by ROCKNROLLKID** [comment]
Still haven't gotten any reply on my end.

Any luck on your end, Robert?

**Comment by MoscaDotTo** [comment]
I've reached out to the person who contacted me and they said they forwarded the message on to the relevant parties

**Comment by ROCKNROLLKID** [comment]
That's good to hear. I'll go ahead and close this since we did all we could on our side. Now it's up to them.
