### ISSUE TITLE
Removing SteamVR Translations

### ISSUE THREAD

**Issue by Virakal** [MoscaDotTo/Winapp2#354]
Using winapp2.ini with CCleaner, the `Games - Steam *` entry is removing translations from SteamVR, resulting in the app using placeholders for every text entry. It can be fixed by verifying the local files for SteamVR through Steam.

I believe the offending line is `FileKey3=%ProgramFiles%\Steam|*.log;*log.last;connection_log_*.txt;*_log.txt;remote_connections.txt;vr*_*.txt|RECURSE`, which is hitting files like `C:\Program Files (x86)\Steam\steamapps\common\SteamVR\content\vrmonitor\translations\vrmonitor_english.txt`. I'm afraid I don't know how to fix it to make a pull request, though.

**Comment by APMichael** [comment]
Thank you very much for your information.

I changed that line and removed the pattern "vr*_*.txt". Please let us know if this fixes the problem.

**Comment by Virakal** [comment]
Great, that fixed it. Thanks for all your hard work on this project!

**Comment by APMichael** [comment]
Thank you very much for your reply and your kind words.
