### ISSUE TITLE
Add support for Deezer Desktop App

### ISSUE THREAD

**Issue by ZeroDot1** [MoscaDotTo/Winapp2#369]
https://www.deezer.com/desktop/download/artifact/win32/x86/4.3.5

**Comment by APMichael** [comment]
Thank you for your suggestion. But please provide complete and tested Winapp2 entries. Unfortunately, we are not able to install and test new applications for you. Thank you for your understanding.

**Comment by APMichael** [comment]
I got a quick look at the app. It is based on Chromium. Therefore, the following entry should work:

```
[Deezer Desktop *]
LangSecRef=3022
DetectFile=%LocalAppData%\Programs\deezer.desktop
Default=False
FileKey1=%AppData%\Deezer|*-journal;LOG;LOG.old|RECURSE
FileKey2=%AppData%\Deezer|Network Persistent State;Origin Bound Certs;QuotaManager;log.log
FileKey3=%AppData%\Deezer\*Cache|*.*|RECURSE
FileKey4=%AppData%\Deezer\*logs|*.*|RECURSE
FileKey5=%AppData%\Deezer\blob_storage|*.*|RECURSE
FileKey6=%AppData%\Deezer\Service Worker\*Cache*|*.*|RECURSE
FileKey7=%LocalAppData%\deezer.desktop-updater|*.*|RECURSE
```

Please test the entry to see if it works for you. Thanks a lot!

**Comment by APMichael** [comment]
@ZeroDot1: Are you still interested in this entry? Can you test it, please? Or should we close this entry request?

**Comment by ZeroDot1** [comment]
Thank you very much, sir.
This works, please merge it with the Winapp2.

**Comment by APMichael** [comment]
Thanks for the testing and your reply.
