### ISSUE TITLE
Chromium Metrics

### ISSUE THREAD

**Issue by mikhaelkh** [MoscaDotTo/Winapp2#372]
```
User Data\CrashpadMetrics-active.pma
User Data\Crashpad\
User Data\Stability\
User Data\Default\VideoDecodeStats\
User Data\Default\Feature Engagement Tracker\
```

**Comment by APMichael** [comment]
Thank you for your suggestion. But please provide complete and tested Winapp2 entries. Unfortunately, we are not able to install and test applications for you. Thank you for your understanding.

**Comment by APMichael** [comment]
I installed the latest Chromium browser and opened a new pull request with the changes.
