### ISSUE TITLE
Chromium `Web Applications` folder

### ISSUE THREAD

**Issue by mikhaelkh** [MoscaDotTo/Winapp2#383]
Is it safe to remove `%LocalAppData%\Chromium\User Data\Default\Web Applications\`?
For me this folder only has icons of some extensions (e.g. uBlock Origin, Dark Reader). And they are not removed when you remove corresponding extensions.

**Comment by APMichael** [comment]
I installed Chromium 75.0.3770.100, but the folder "Web Applications" was never created in any of my test sessions. (I know that some earlier versions created the folder.) Maybe you can remove the folder and see if it will ever be recreated again.

**Comment by mikhaelkh** [comment]
In Chromium 75.0.3770.100, I removed the folder, and after [uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin-development/cgbcahbpdhpcegmbfconppldiemgcoii) updated, `Web Applications` appeared again.

**Comment by APMichael** [comment]
Thank you for your quick reply. I was able to repro it and added a new entry for the folder "Web Applications". Now let's see if we get an issue report.

**Comment by APMichael** [comment]
> Now let's see if we get an issue report.

Looks good. Closing this for now. (Please re-open if necessary.)
