### ISSUE TITLE
Temporary ASP.NET Files itself should not be deleted

### ISSUE THREAD

**Issue by ArgonAlex** [MoscaDotTo/Winapp2#384]
It's fine to delete all subfolders and files of "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files", but deleting the folder itself will break ASP.NET wesbites until the folder is recreated with the correct permissions set.

**Comment by MoscaDotTo** [comment]
Is changing the `REMOVESELF` in `FileKey4` of `[.NET Framework *]` to a `RECURSE` a sufficient fix? 
```
[.NET Framework *]
LangSecRef=3025
Detect=HKLM\Software\Microsoft\.NETFramework
Default=False
FileKey1=%WinDir%\assembly\NativeImages_*\Temp|*.*|RECURSE
FileKey2=%WinDir%\assembly\t*mp|*.*|REMOVESELF
FileKey3=%WinDir%\Microsoft.NET\Framework*\*\*\Logs|*.*|RECURSE
FileKey4=%WinDir%\Microsoft.NET\Framework*\*\Temporary ASP.NET Files|*.*|RECURSE
FileKey5=%WinDir%\Microsoft.NET\Framework*\v4.0.30319\SetupCache|*.*|RECURSE
FileKey6=%WinDir%\System32\URTTemp|*.*|RECURSE
RegKey1=HKCU\Software\Microsoft\.NETFramework\SQM\Apps
```

**Comment by ArgonAlex** [comment]
That looks like it would do the trick.

**Comment by APMichael** [comment]
Thank you very much for your information. I have opened a new pull request.
