### ISSUE TITLE
Include links for each software?

### ISSUE THREAD

**Issue by ROCKNROLLKID** [MoscaDotTo/Winapp2#39]
I know this sounds a little weird, but how does everyone feel about including links for each software (CCleaner, BleachBit, System Ninja, and Avira System Speedup) that will take you to their website? I figured this will help gain fast access to each software, if anyone wanted to test out Winapp2 with each software, then they wouldn't have to browser the web searching for it or something.

Or does everyone think this is not needed?

**Comment by TZocker** [comment]
its so much work...., with free software no problem but wenn you have old paidware you dont find it anywhere. After some years by the way you have to check up all the links !
