### ISSUE TITLE
[WinappDebug] Jumpto line command

### ISSUE THREAD

**Issue by ROCKNROLLKID** [MoscaDotTo/Winapp2#390]
Currently Winappdebug tells us the line, but unless you use Notepad++ or something that can easily list the line numbers, this is kind of difficult to find. What if we can implement a command that allows WinappDebug to jump to that line in the Winapp2 file or any other file. Something like "-jumpto line 7634"

**Comment by MoscaDotTo** [comment]
Try CTRL+G if you're using Windows Notepad to open the "Go To Line" dialog

**Comment by ROCKNROLLKID** [comment]
Yes, that might just be a better idea, I just thought of this as a quick way of doing it.
