### ISSUE TITLE
script to extract entires

### ISSUE THREAD

**Issue by CSGalloway** [MoscaDotTo/Winapp2#391]
I have a lot of old winapp2.ini scripts and would like to extract each rule to a new file.
e.g. if I have the file winapp2.old.ini then a 

1) md entries.winapp2.old.ini 
2) the preamble would go to entries.winapp2.old.ini\preample.txt
3a) rule 1 would go to rule1.ini
3b) rule 2 would go to rule2.ini
etc.....
4) when all the file has been done as above, ren "winapp2.old.ini" done.winapp2.old.ini

A huge thank you if there is one out there......

**Comment by APMichael** [comment]
It's been some time since I've worked with scripts. But I think this script should work:
https://raw.githubusercontent.com/APMichael/Winapp2/master/Winapp2/Miscellaneous/waisplit.bat

**Comment by APMichael** [comment]
Closing this for now. (Please re-open if necessary.)
