### ISSUE TITLE
Trimming Idea?

### ISSUE THREAD

**Issue by ghostery11** [MoscaDotTo/Winapp2#392]
We already know, through the trimming of the Winapp2.ini File, which entries are used by the individual pc.

What about, if we remove the Detectfile and Detect, so CCleaner doesn't have to check, if the entries still exist or not.

And yes, even when the detect and detectfile are removed, it still works.

**Comment by ghostery11** [comment]
166 Entries on PC


Without:
1.63 Sec
1.83 Sec
1.83 Sec
1.89 Sec
2.02 Sec

Filesize: 137 Kb

With:
2.02 Sec
1.96 Sec
1.71 Sec
2.03 Sec
1.77 Sec

Filesize: 169 Kb



So, tested, and it seems it is slighty faster with the detect and detectfile in it.
Each test has been performed when the UAC windows came up.

Perhaps, if, we have still the detectfile or detect, but only a standard place,
then it will be faster. Lets say, all detect and detectfile will be replaced by
"HKLM\Software\Microsoft\"

Cclenaer version I use is:5.39, because of the pop up in later version, I won't update anymore.

**Comment by ghostery11** [comment]
Now I have replaced all detectfiles and detects with:
"Detect1=HKCU\Software\" and deleted the other detects, since it wont work, if detect is there several times.


With:
2.10 Sec
2.09 Sec
1.76 Sec
1.96 Sec
1.77 Sec

Filesize: 142 Kb

Yeah, even then it's not faster. So yeah the case is closed I think.
It seems, that ccleaner is not taking time to search for the existence of the entry, but more for creating a space in the ram.

**Comment by ghostery11** [comment]
@ROCKNROLLKID 
@MoscaDotTo 

For your notice only.

**Comment by ROCKNROLLKID** [comment]
All I can say is I don't see a benefit in this at all.

**Comment by MoscaDotTo** [comment]
Some aspect of what CCleaner does starting up goes beyond just validating the detection criteria I would imagine, given that winapp2ool's trim can eat the full winapp2.ini file and have it processed in well under 1 second (on my machine)
