### ISSUE TITLE
[Enhancement] Help Guide for People

### ISSUE THREAD

**Issue by winapp2** [MoscaDotTo/Winapp2#4]
We should add a Help Guide for people like links or how these entries are made and so on.

**Comment by CSGalloway** [comment]
Such as the original posting on
https://forum.piriform.com/index.php?showtopic=32310&page=1#entry175835


http://www.facebook.com/CSGalloway

**Comment by ROCKNROLLKID** [comment]
It is probably better to include this in the README file, that way it is shown on the first page/code page.

**Comment by winapp2** [comment]
I think a separate file is better.

**Comment by winapp2** [comment]
PR sent. Closing this.
