### ISSUE TITLE
Update README with new tools

### ISSUE THREAD

**Issue by ROCKNROLLKID** [MoscaDotTo/Winapp2#40]
@Shane or Robert:

Maybe you want to update the README to say what those tools do (CCdump, winappdebug, winappparser)? I am not sure what they do myself, lol, but I don't use CCleaner anyways.

**Comment by ShaneGowland** [comment]
This was mentioned in #37. I'll get to it at some point.

**Comment by ROCKNROLLKID** [comment]
@ShaneGowland I was told sometime ago that CCDump wasn't necessary anymore because CCleaner already does this within the program.

Also, would it be possible to combine Winappdebug and Winappparser into 1 tool?
