### ISSUE TITLE
Slimjet not in list of Applications

### ISSUE THREAD

**Issue by MaccabeeY** [MoscaDotTo/Winapp2#404]
I saw entries in Winapp2.ini for both Flashpeak's SlimBrower and Slimjet.
I have both installed but only SlimBrowser is displayed in the Application tab list, no Slimjet.
Please adjust so FlashPeak's Slimjet is available in the Application tab list.  thanks...

**Comment by APMichael** [comment]
The entries for the browser "Slimjet" are listed under the section "Google Chrome", there is no separate section "Slimjet". The entries always clean up all installed Chromium-based browsers at once.  It is not possible to clean each of them individually.

(I have seen that "SlimBrowser" is now a Firefox-based browser. I'll see if we can add it to the "Mozilla Firefox" entries like the other Firefox-based browsers.)

**Comment by MaccabeeY** [comment]
Ah, I see...

**Comment by APMichael** [comment]
I have opened new pull requests for the Firefox-based browser "SlimBrowser" (#405,#406,#407).
