### ISSUE TITLE
[WinappDebug] Add detecting for wrong use of ;

### ISSUE THREAD

**Issue by ROCKNROLLKID** [MoscaDotTo/Winapp2#409]
During my tests, it seems that if you use : instead of ; CCleaner will not detect the correct extension or entry. For example, I created to general log cleaning entries, one with *.log;*.log1 and another with *.log:*.log1. The one using ; detected the correct amount of .log files while the other one didn't detect anything at all for me. Same goes for other things being used instead, such as , or . or something similar. Seems like this could be a fairly easy mistake to make. It would be a nice addition for WinappDebug.

**Comment by MoscaDotTo** [comment]
It may be easier to simply flag any instance of `:` as a mistake, they're not allowed as a character in file/folder names on Windows and I don't think they're any part of the ccleaner syntax

**Comment by MoscaDotTo** [comment]
the semi/colon work is done now, I'm not sure whether it's a good idea to go after commas as they're a permitted character for windows filenames and could be used intentionally

**Comment by MoscaDotTo** [comment]
On that note though, this does stand out to me as a probably unintentional use of a comma in place of a semi colon 

```
[Portfolio Performance *]
LangSecRef=3021
DetectFile=%LocalAppData%\PortfolioPerformance
Default=False
FileKey1=%LocalAppData%\PortfolioPerformance\workspace\.metadata|*.lock,*.log
```

**Comment by APMichael** [comment]
Good catch, thanks! I will correct the entry.

**Comment by APMichael** [comment]
Is it possible to check for colons only after the pipe symbol? Otherwise there are error messages with the entries [CheckDisk Restored Files Folder \*] and [Windows System Volume Tracking Logs \*] from the Winapp3.ini.

**Comment by MoscaDotTo** [comment]
In the latest build of winapp2ool, I excluded entries who begin with a drive letter from this scan. This means we'll still check for colons before the pipe but we'll ignore any colons in a key whose value begins with a hardcoded drive letter.

**Comment by APMichael** [comment]
Good solution, thank you.
