### ISSUE TITLE
A couple of missing trailing slashes.

### ISSUE THREAD

**Issue by ShaneGowland** [MoscaDotTo/Winapp2#41]
From WinappDebug:

> Line: 1828 Error: Environmental variables must have a trailing backslash.
> Command: FileKey3=%ProgramFiles%|ArgusMonitor_EventLog.txt;ArgusMonitor_CSVLog.csv
> 
> Line: 9080 Error: Environmental variables must have a trailing backslash.
> Command: FileKey3=%ProgramFiles%|GUT*tmp
> 
> Line: 9111 Error: Environmental variables must have a trailing backslash.
> Command: FileKey1=%ProgramFiles%|_ISTMP1.DIR
> 
> ***********************************************
> Completed analysis of winapp2.ini. 3 errors were detected. Press any key to close.

**Comment by ROCKNROLLKID** [comment]
Do you know what the correct way they should be? Looking at them myself, I can't really see what is wrong with them.

Also, the line numbers you have are a little off to what I am getting with Notepad++. I am getting Line: 1828, Line: 9090, and Line: 9121.

**Comment by ROCKNROLLKID** [comment]
Fixed: https://github.com/MoscaDotTo/Winapp2/commit/00a0098a7f98bacc46f28cbd4dec195771291b26

Closing issue.
