### ISSUE TITLE
[WinappDebug] Detect if other entries are the same

### ISSUE THREAD

**Issue by ROCKNROLLKID** [MoscaDotTo/Winapp2#410]
This was discussed here: https://github.com/MoscaDotTo/Winapp2/pull/408

Currently, WinappDebug only detects if entries are the same within the same entry, but not if other entries are the same. So basically, if I made a entry with %SystemDrive%|*.log and another entry that had %SystemDrive%|*.log, WinappDebug would NOT detect this, however if I made a entry with both %SystemDrive%|*.log, then WinappDebug WOULD detect it.

I just opened this so it wouldn't be forgotten, but if it is too much work or if it causes too many false positives or some other issue, we can just forget it.

**Comment by MoscaDotTo** [comment]
I can envision this working with two settings

"strict" mode, where the keys' parameters must be identical (ie `%SystemDrive%|*.log` and `%SystemDrive%|*.log*` would *not* match 

and "warning" mode, where just identical folders would match (ie. the example above *would* match) - this would bear mostly false positives but would probably also eliminate most false negatives

**Comment by MoscaDotTo** [comment]
a basic version of this request has been implemented in v1.5, it will reset to a disabled state when you restart the application and can be enabled in the winappdebug advanced scans menu

**Comment by MoscaDotTo** [comment]
Currently it supports only FileKeys and RegKeys and produces a lot of "noise" as we expect to have some duplicate keys between entries
