### ISSUE TITLE
[WinappDebug] Detect if Wildcards are being used in replacement

### ISSUE THREAD

**Issue by ROCKNROLLKID** [MoscaDotTo/Winapp2#411]
Currently, WinappDebug doesn't detect if entries are the same if wildcards are being used. For example, %SystemDrive%|\*.log\* vs %SystemDrive%|\*.log;\*.log1;\*.log2 etc. Obviously we wouldn't need the \*.log1, 2, etc ones because they are already being detect with the use of the wildcard. This would be nice to also be paired with https://github.com/MoscaDotTo/Winapp2/issues/410

Again if it is too much work or too many false positives, then we can just close this.

**Comment by APMichael** [comment]
JFYI: GitHub uses "Styling with Markdown". Therefore, you have to escape some special characters with a backslash "\\". The special characters are for example the asterisk "\*" and the backslash "\\" itself (escaping: "\\\*" or "\\\\").

**Comment by ROCKNROLLKID** [comment]
Is that better? Was it not readable for you?

**Comment by APMichael** [comment]
Yes, thanks. Now the wildcards are displayed correctly. (You can see the differences under "edited".)

**Comment by MoscaDotTo** [comment]
I looked into this once a while back but the string matching seemed difficult. I'll look into it again when I have more time, but I recall it being very difficult to properly interpret and compare multiple wildcards in a single parameter correctly
