### ISSUE TITLE
Language entries

### ISSUE THREAD

**Issue by APMichael** [MoscaDotTo/Winapp2#416]
I found an old file in which I collected many entries for language files. I debugged it and attached it here.

[languages.txt](https://github.com/MoscaDotTo/Winapp2/files/3755712/languages.txt)

Should we add these entries to Winapp3.ini? If so, which ones?

**Comment by ROCKNROLLKID** [comment]
They all look alright to me. I don't use most of them so I can't tell if deleting them will break anything.

**Comment by APMichael** [comment]
Ok, thanks for your reply. Then I will add them with the next update. Let's see if we get any issue reports afterwards.
