### ISSUE TITLE
UTF-8 letters in "Spybot Search and Destroy History"

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [MoscaDotTo/Winapp2#418]
In "Spybot Search and Destroy History" are UTF-8 letters used - should be IMHO ASCII letter.

Analyzed here: https://github.com/bleachbit/bleachbit/issues/673

**Comment by APMichael** [comment]
Thanks for the information. But it looks like you are using an outdated version of Winapp2.ini. 

This is the entry in a current version:
```
[Spybot Search and Destroy History *]
LangSecRef=3024
Detect=HKLM\Software\Safer Networking Limited\SpybotSnD
Default=False
FileKey1=%CommonAppData%\Spybot - Search & Destroy\Backups|*.*|RECURSE
FileKey2=%CommonAppData%\Spybot - Search & Destroy\Recovery|*.*|RECURSE
FileKey3=%CommonAppData%\Spybot - Search & Destroy\Snapshots*|*.*|RECURSE
```

**Comment by Tobias-B-Besemer** [comment]
Thx 4 nfo! :) And sorry for the circumstances!

**Comment by APMichael** [comment]
No problem, that's okay. 😃
