### ISSUE TITLE
Some entries

### ISSUE THREAD

**Issue by ghost** [MoscaDotTo/Winapp2#42]
If you add or not. Closing this issue.

[Live Kernel Watchdog*]
LangSecRef=3025
Detect=HKCU\SOFTWARE\Microsoft
Default=False
FileKey1=%WinDir%\LiveKernelReports|*.dmp|RECURSE

-Fixed the Detect and the Filekey1.
It cleaned a 900mb big dump, which was on the LiveKernelReports Folder.

[Temporary Windows installation files*]
LangSecRef=3025
Warning=This will delete the files to get back to the previous Windows installation. It's not possible without it.
Detect=HKCU\SOFTWARE\Microsoft
Default=False
FileKey1=%SystemDrive%\$Windows.~WS|*.*|RECURSE|REMOVESELF

-For more info look at:
http://www.howtogeek.com/268667/what-is-the-windows.bt-folder-and-can-you-delete-it/

[Previous Windows installations*]
LangSecRef=3025
Warning=This will delete your previous Windows installations.
Detect=HKCU\SOFTWARE\Microsoft
Default=False
FileKey1=%SystemDrive%\$Windows.~BT|*.*|RECURSE|REMOVESELF

-For more info look at:
http://www.howtogeek.com/268667/what-is-the-windows.bt-folder-and-can-you-delete-it/

[Windows Old More*]
LangSecRef=3025
Warning=This will delete your previous Windows installations.
Detect=HKCU\SOFTWARE\Microsoft
Default=False
FileKey1=%SystemDrive%\Windows.old*|*.*|RECURSE|REMOVESELF

-This will delete all windows old folders

[InstallShield*]
LangSecRef=3024
Detect=HKCU\Software\InstallShield
Default=False
FileKey1=%ProgramFiles%|_ISTMP1.DIR
FileKey2=%SystemDrive%|_ISTMP*.DIR

-Removed the "\|"

[Installer*]
LangSecRef=3029
SpecialDetect=DET_CHROME
Default=False
Warning=Running this may remove Chrome's ability to automatically update to future versions on some computers.
FileKey1=%LocalAppData%\Google\Chrome*\Application\*\Installer|*.7z|RECURSE
FileKey2=%LocalAppData%\Google\Update\*\*\Installer|*.7z|RECURSE
FileKey3=%ProgramFiles%|GUT*tmp
FileKey4=%ProgramFiles%\Google\Chrome*\Application\*\Installer|*.7z|RECURSE
FileKey5=%ProgramFiles%\Google\Update\*\*\Installer|*.7z|RECURSE

-Removed the "\|"

[Foxit Reader 8.0*]
LangSecRef=3021
Detect=HKCU\Software\Foxit Software\Foxit Reader 8.0
Default=False
RegKey1=HKCU\Software\Foxit Software\Foxit Reader 8.0\Preferences\History\LastOpen
RegKey2=HKCU\Software\Foxit Software\Foxit Reader 8.0\Preferences\History\LastSession
RegKey3=HKCU\Software\Foxit Software\Foxit Reader 8.0\Preferences\Others|csInitialOpenDir
RegKey4=HKCU\Software\Foxit Software\Foxit Reader 8.0\MRU\File MRU
RegKey5=HKCU\Software\Foxit Software\Foxit Reader 8.0\MRU\Place MRU
FileKey1=%LocalAppData%\Foxit Reader|*_old.DMP
FileKey2=%AppData%\Foxit Software\Foxit Reader\Foxit Cloud\DownloadCache|*.cache
FileKey3=%AppData%\Foxit Software\Foxit Reader\Foxit Cloud\FileIDCache|*.fcd
FileKey4=%AppData%\Foxit Software\Foxit Reader\Foxit Cloud|foxitcloud.log
FileKey5=%CommonAppData%\Foxit Software|*.log|RECURSE

-Removed the "\|"

[Argus Monitor*]
LangSecRef=3024
Detect=HKCU\Software\Argotronic\Argus Monitor
Default=False
FileKey1=%Documents%|ArgusMonitor_EventLog.txt;ArgusMonitor_CSVLog.csv
FileKey2=%LocalAppData%\VirtualStore\Program Files*|ArgusMonitor_EventLog.txt;ArgusMonitor_CSVLog.csv
FileKey3=%ProgramFiles%|ArgusMonitor_EventLog.txt;ArgusMonitor_CSVLog.csv+

-Removed the "\|"

[Hedgewars VideoTemp*]
Section=Games
Detect1=HKLM\SOFTWARE\Hedgewars
Detect2=HKLM\SOFTWARE\Wow6432Node\Hedgewars
Default=False
FileKey1=%Documents%\Hedgewars\VideoTemp|*.*

[Windows-Installer-Baseline-Cache (==>Reduandante-System-Backups)*]
LangSecRef=3025
Detect=HKLM\Software\Microsoft
Default=False
FileKey1=%WinDir%\Installer\$PatchCache$|*.*|RECURSE
FileKey2=%WinDir%\winsxs\backup|*.*|RECURSE

[Windows System Volume Tracking.log*]
LangSecRef=3025
Detect=HKLM\Software\Microsoft
Default=False
FileKey1=%SystemDrive%\System Volume Information|tracking.log
FileKey2=C:\System Volume Information|tracking.log
FileKey3=D:\System Volume Information|tracking.log
FileKey4=E:\System Volume Information|tracking.log
FileKey5=F:\System Volume Information|tracking.log
FileKey6=G:\System Volume Information|tracking.log
FileKey7=H:\System Volume Information|tracking.log
FileKey8=I:\System Volume Information|tracking.log
FileKey9=J:\System Volume Information|tracking.log
FileKey10=K:\System Volume Information|tracking.log
FileKey11=L:\System Volume Information|tracking.log
FileKey12=M:\System Volume Information|tracking.log
FileKey13=N:\System Volume Information|tracking.log
FileKey14=O:\System Volume Information|tracking.log
FileKey15=P:\System Volume Information|tracking.log
FileKey16=Q:\System Volume Information|tracking.log
FileKey17=R:\System Volume Information|tracking.log
FileKey18=S:\System Volume Information|tracking.log
FileKey19=T:\System Volume Information|tracking.log
FileKey20=U:\System Volume Information|tracking.log
FileKey21=V:\System Volume Information|tracking.log
FileKey22=W:\System Volume Information|tracking.log
FileKey23=X:\System Volume Information|tracking.log
FileKey24=Y:\System Volume Information|tracking.log
FileKey25=Z:\System Volume Information|tracking.log

-This should be added as it's very useful without deleting anything important.

**Comment by ROCKNROLLKID** [comment]
The Piriform community did not agree to some of your entries as they thought it was too risky. The ones they were OK with, I will add them sometime today or tomorrow.

**Comment by ROCKNROLLKID** [comment]
Some of your additions I had to revert because it was breaking software. It is a good idea to test your entries out before making commits (as well as I should have done the same). Lets try our best to avoid mistakes like this for the future.

Closing issue.
