### ISSUE TITLE
FileKey not detected

### ISSUE THREAD

**Issue by Machou** [MoscaDotTo/Winapp2#426]
Hello

When i want detect _[Content Preferences *]_ from Firefox, i use :

```
DetectFile=%AppData%\Mozilla\Firefox
DetectFile2=G:\Divers\Logiciels Portable\Firefox\Data\profile
```

```
FileKey3=%AppData%\Mozilla\Firefox\Profiles\*|content-prefs.sqlite
FileKey4=%AppData%\Mozilla\SeaMonkey\Profiles\*|content-prefs.sqlite
FileKey5=%AppData%\Waterfox\Profiles\*|content-prefs.sqlite
FileKey6=G:\Divers\Logiciels Portable\Firefox\Data\profile\*|content-prefs.sqlite
```

The file **content-prefs.sqlite** is in my folder **G:\Divers\Logiciels Portable\Firefox\Data\profile** but he don't detect the file.

Maybe is wrong, anyone can help me please ?

**Comment by APMichael** [comment]
Is the file "**content-prefs.sqlite**" located directly in the folder "G:\\Divers\\Logiciels Portable\\Firefox\\Data\\**profile**" or in a folder like "G:\\Divers\\Logiciels Portable\\Firefox\\Data\\profile\\**xxx.default**"? If your profile path has no profile ID (like "xxx.default"), the FileKey should be:
```
FileKey6=G:\Divers\Logiciels Portable\Firefox\Data\profile|content-prefs.sqlite
```

**Comment by Machou** [comment]
work, thanks =) i have understand now !
