### ISSUE TITLE
'Dangerous Long' Junk File Extensions removing OS files

### ISSUE THREAD

**Issue by Dutchman101** [MoscaDotTo/Winapp2#429]
If you clean 'Junk File Extensions' under the Dangerous Long section, some Windows OS files that I have identified will be inadvertently removed.

Files:

> C:\Windows\PLA\Reports\en-GB\Report.System.Wired.xml
> C:\Windows\PLA\Reports\en-GB\Report.System.Wireless.xml
> C:\Windows\PLA\Reports\en-GB\Report.System.NetDiagFramework.xml

After Winapp2 removes these files, system file corruption can be detected by the cmd command sfc /scannow, which will output:

> Info                  CSI    0000023f [SR] Beginning Verify and Repair transaction
> Info                  CSI    00000240 [SR] Repairing corrupted file \??\C:\Windows\PLA\Reports\en-GB\\Report.System.Wireless.xml from store
> Info                  CSI    00000241 [SR] Repairing corrupted file \??\C:\Windows\PLA\Reports\en-GB\\Report.System.Wired.xml from store
> Info                  CSI    00000242 [SR] Repairing corrupted file \??\C:\Windows\PLA\Reports\en-GB\\Report.System.NetDiagFramework.xml from store

Restoring it using sfc /scannow, or manually finding the original file (appropiate for your OS version) is the only way to recover.

These files, in C:\Windows\PLA\, are part of the Windows feature "Performance Logs and Alerts (PLA)": [https://docs.microsoft.com/en-us/previous-versions/windows/desktop/pla/pla-portal](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/pla/pla-portal) and therefore it's possible that this corruption (the files being removed) can cause some software to perform incorrectly, or cause issues for users/system administrators using those tools.

For the record, contents of these 3 files on Windows 10 1909 (build 18363.535) - as they look relevant for proper functioning of something to me:
Report.System.Wired.xml: [https://pastebin.com/warFefSu](https://pastebin.com/warFefSu)
Report.System.Wireless.xml: [https://pastebin.com/x4uGqqGu](https://pastebin.com/x4uGqqGu)
Report.System.NetDiagFramework.xml: [https://pastebin.com/7eS6Spk7](https://pastebin.com/7eS6Spk7)

So i think preventing it is warranted.

**Suggested solution:**
Add an exception for these .xml files to Winapp2's Junk Files Extension definition, so it avoids them.

**Comment by APMichael** [comment]
Thank you for your information.

But it seems that the access rights of the subfolders and files of your folder "PLA" have been changed. The files can usually only be changed by the "TrustedInstaller".

If I do an analysis with the entry [Junk File Extensions \*] on my systems, CCleaner don't find these files because it obviously can't access them.

**Comment by Dutchman101** [comment]
Now that the files are restored for me, analyzing gives me inconsistent results; it won't be in the list of detected files. Running the cleaner without analyzing first though, will remove the files.


> But it seems that the access rights of the subfolders and files of your folder "PLA" have been changed. The files can usually only be changed by the "TrustedInstaller".

I doubt it. In my case, on the PLA folder TrustedInstaller has no rights except for "Special Permissions" and "List folder contents", and after some system groups the Administrators & Users groups are added: they respectively have full and limited (only Read, Read & Execute, and List folder contents) rights.

I confirmed these rights to exactly be the same (as above) on another machine.

Please note that I'm running CCleaner as administrator. I really don't know why running the cleaner instantly rather than analyzing would produce different results..

**Comment by APMichael** [comment]
Just to be sure: I didn't mean the access rights of the folder "PLA" itself. I was referring to the subfolders and files. The access rights of the mentioned XML files show that only the "TrustedInstaller" has full access. All others only read and execute. If I want to delete the mentioned XML files manually, Windows tells me that you need the permissions of the "TrustedInstaller".

**Comment by Dutchman101** [comment]
I think the permissions for said file are pretty much the same for me.

![img](https://user-images.githubusercontent.com/12105539/70835075-3ff1d980-1dfc-11ea-9301-840a12b4427a.png)

But in that case I have no clue why we are getting different results, and why even here the results from 'Analyze' differs from that of 'Clean' - it makes no sense. If you think that it warrants an exception because some machines (for some reason) may or may not have these files deletable for any reason, then go for it, otherwise feel free to leave it.

**Comment by APMichael** [comment]
Thank you for checking the access rights and your reply.

Ok, then I guess this is another strange and unexpected behavior from CCleaner.

I will add an ExcludeKey for the folder.
