### ISSUE TITLE
Duplicate option names within multiple sections

### ISSUE THREAD

**Issue by az0** [MoscaDotTo/Winapp2#43]
It needs renumbered.

````
[Auslogics BoostSpeed 5*]
LangSecRef=3024
Detect=HKCU\Software\Auslogics\BoostSpeed\
Default=False
FileKey1=%AppData%\Auslogics|*.htm;*.html;*.log;*.rsc;*.sta;*.xml|RECURSE
FileKey1=%LocalAppData%\VirtualStore\Program Files*\Auslogics\Auslogics BoostSpeed|rdboot.log
````

**Comment by az0** [comment]
I wrote a utility that found some more in Winapp2.ini

Duplicate option filekey1 in section Agomo Logs*
Duplicate option filekey1 in section Auslogics BoostSpeed 5*
Duplicate option filekey5 in section BB TestAssistant 4*
Duplicate option filekey1 in section BlackBeltPrivacy DarkNet Logs*
Duplicate option regkey9 in section CyberLink Power2Go 9*
Duplicate option detect3 in section MS Office Picture Manager More*
Duplicate option filekey1 in section Web Sling Player Cache*

**Comment by ROCKNROLLKID** [comment]
Fixed for BleachBit: https://github.com/MoscaDotTo/Winapp2/commit/fa4847d77bafdd6897df58ea1acd2f1f044413f0

**Comment by ROCKNROLLKID** [comment]
As for the duplicate tool, since this is Robert's GitHub, I will let him decide if he wants to include that here.

**Comment by ROCKNROLLKID** [comment]
Closing as another issue was opened for this: https://github.com/MoscaDotTo/Winapp2/issues/45
