### ISSUE TITLE
[Trim] White List

### ISSUE THREAD

**Issue by APMichael** [MoscaDotTo/Winapp2#430]
A suggestion from **siliconman01** of the community: https://forum.piriform.com/topic/32310-winapp2ini-additions/page/327/?tab=comments#comment-313392.

> Suggested enhancement to the Trim function of Winapp2ool:
> 
> Provide a White List function that tells the Trim to NOT trim "white listed" cleaning functions.  This would overcome the situation where the Detect and/or DetectFile of certain modules disappears during a cleaning but can reappear on a Windows or third party application update.  For example:
> 
> 1.  A new Winapp2.ini is issued/trimmed and install.  At this point in time, no Dell folder is present at/on C:\\.
>
> 2.  Then Dell issues a new driver update which is then installed.  This creates a Dell folder on C:\\.  This folder and its content is no longer needed after the driver is installed.  However, the cleaning module in Winapp2.ini or a user's Custom.ini  is not present because it was trimmed out in (1) above.  The user must wait for the next Winapp2.ini release/trim for Winapp2.ini to insert that cleaning module to remove the C:\\Dell folder.  
> 
> There are several modules like this in Winapp2.ini and also in my Custom.ini file where this exists.  A Trim White list would obviate this problem.
> 
> JMS

**Comment by MoscaDotTo** [comment]
This is done in the latest beta, if there's any bugs with it we can open a new issue
