### ISSUE TITLE
MS Office entry needs warning

### ISSUE THREAD

**Issue by lucknaumann** [MoscaDotTo/Winapp2#433]
MS Office entry does **not** have but *should* have a warning because of FileKey5
	
`FileKey5=%Documents%|~*.ppt;~*.pptx;~*.doc;~*.docx|RECURSE`

Here's an example of what the warning should read:

`Warning=This will delete ALL PowerPoint & Word files in the Documents folder & its subfolders!`

There may be other items to include in this warning since I'm not 100% certain what all the FileKeys or RegKeys pertain to or what the ultimate results are. This obviously does more than just delete temp, log and cache files.

**Comment by Tmp341** [comment]
> `FileKey5=%Documents%|~*.ppt;~*.pptx;~*.doc;~*.docx|RECURSE`

Looks like ``temp`` files to me. Office deletes them (afaik) when you save and close the file.

**Comment by lucknaumann** [comment]
Thanks for responding. After running this all my PowerPoint & Word files were deleted. Fortunately, I had a backup. If it wasn't this, then I guess it was something else. Thanks again.
