### ISSUE TITLE
[SpeedFan *] - new entry for winapp2.ini

### ISSUE THREAD

**Issue by aquila-XP** [MoscaDotTo/Winapp2#434]
After talking with Shane Gowland, I will start to submit new entries for winapp2.ini file by creating an Issue for each one.

`[SpeedFan *]`
`...`
`FileKey2=%WinDir%\system32|initdebug.nfo`
`FileKey3=%WinDir%\SysWOW64|initdebug.nfo`

**Comment by APMichael** [comment]
Thank you very much for your new and revised entries.

However, it is not necessary to open a separate issue for each entry. You can submit them all at once.

Update: 33dafe6e8cd693b34af8f3d870b618bc0bde3d24

**Comment by TZocker** [comment]
Hi,

Please one request not 160 ....
I got over 300 mail notifications, its not funny...

greetz
