### ISSUE TITLE
OpenOffice.org deletes deletes desktop

### ISSUE THREAD

**Issue by az0** [MoscaDotTo/Winapp2#44]
This affects BleachBit and maybe all other applications that use this entry. The REMOVESELF removes the desktop, not just the OpenOffice.org folder.

````
[OpenOffice.org Setup Files*]
LangSecRef=3021
Detect1=HKLM\Software\OpenOffice.org
Detect2=HKLM\Software\Wow6432Node\OpenOffice.org
Detect3=HKLM\Software\OpenOffice
Detect4=HKLM\Software\Wow6432Node\OpenOffice
FileKey1=%UserProfile%\Desktop|OpenOffice.org * Installation Files|REMOVESELF
````

BleachBit's ticket for this bug https://bugs.launchpad.net/bleachbit/+bug/1388322

I think you want this instead
````
FileKey1=%UserProfile%\Desktop\OpenOffice.org * Installation Files|REMOVESELF
````

**Comment by ROCKNROLLKID** [comment]
Did you mean change the REMOVESELF to RECURSE?

**Comment by az0** [comment]
This should remove the contents and leave an empty folder
FileKey1=%UserProfile%\Desktop|OpenOffice.org * Installation Files|RECURSE

This should remove the contents and delete the folder (but not delete the desktop). Notice between the original and this version the pipe is a slash.
````
FileKey1=%UserProfile%\Desktop\OpenOffice.org * Installation Files|REMOVESELF
````
In case they interpret it differently, ideally someone could test this in at least two applications. It can be tested by mocking up a folder named `OpenOffice.org 4.0 Installation Files` with a single file with any name.

**Comment by ROCKNROLLKID** [comment]
Fixed: https://github.com/MoscaDotTo/Winapp2/commit/00506aba038e88746420e01fed4a31e2b5cfabc1

Plus also a grammar error in one of the comments.
