### ISSUE TITLE
[Your Freedom *] - new entry for winapp2.ini

### ISSUE THREAD

**Issue by aquila-XP** [MoscaDotTo/Winapp2#442]
`[Your Freedom *]`
`LangSecRef=3022`
`DetectFile=%ProgramFiles(x86)%\Your Freedom\freedom.exe`
`Default=False`
`FileKey1=%LocalAppData%\Your Freedom|*.old`

**Comment by APMichael** [comment]
JFYI: %ProgramFiles(x86)% is not required. You can always use %ProgramFiles%.
