### ISSUE TITLE
[Puran Delete Empty Folders *] - new entry for winapp2.ini

### ISSUE THREAD

**Issue by aquila-XP** [MoscaDotTo/Winapp2#448]
`[Puran Delete Empty Folders *]`
`LangSecRef=3024`
`Detect1=HKLM\SOFTWARE\Puran Software\Delete Empty Folders`
`Detect2=HKLM\SOFTWARE\WOW6432Node\Puran Software\Delete Empty Folders`
`Default=False`
`RegKey1=HKLM\SOFTWARE\Puran Software\Delete Empty Folders|Drives`
`RegKey2=HKLM\SOFTWARE\WOW6432Node\Puran Software\Delete Empty Folders|Drives`

**Comment by APMichael** [comment]
JFYI: Detect lines do not require WOW6432Node.
