### ISSUE TITLE
[Pictus *] - new entry for winapp2.ini

### ISSUE THREAD

**Issue by aquila-XP** [MoscaDotTo/Winapp2#450]
`[Pictus *]`
`LangSecRef=3023`
`Detect=HKLM\Software\Wow6432Node\Poppeman\Pictus`
`DetectFile=%AppData%\Poppeman\Pictus`
`Default=False`
`FileKey1=%AppData%\Poppeman\Pictus|*.txt`
or
`FileKey1=%AppData%\Poppeman\Pictus|runlog.txt;setup.txt`

**Comment by APMichael** [comment]
Detect lines do not require WOW6432Node.
