### ISSUE TITLE
[Kingston SSD Manager *] - new entry for winapp2.ini

### ISSUE THREAD

**Issue by aquila-XP** [MoscaDotTo/Winapp2#457]
`[Kingston SSD Manager *]`
`LangSecRef=3024`
`DetectFile=%ProgramFiles(x86)%\Kingston_SSD_Manager`
`Default=False`
`FileKey1=%ProgramFiles(x86)%\Kingston_SSD_Manager|*.log;*log.txt`

**Comment by APMichael** [comment]
%ProgramFiles(x86)% is not required. You can always use %ProgramFiles%.
