### ISSUE TITLE
[Windows Subsystems *] - update entry for winapp2.ini

### ISSUE THREAD

**Issue by aquila-XP** [MoscaDotTo/Winapp2#464]
`[Windows Subsystems *]`
...
`RegKey7=HKCU\Software\Classes\VirtualStore\MACHINE\SOFTWARE\Wow6432Node\Microsoft\Direct3D\MostRecentApplication`

**Comment by APMichael** [comment]
Keys for VirtualStore are not required because the trim function of winapp2ool adds them.
