### ISSUE TITLE
false positives - steam games

### ISSUE THREAD

**Issue by timse201** [MoscaDotTo/Winapp2#51]
files will be deleted and no new game can be started

C:\Program Files (x86)\Steam\steamapps\common\Supreme Ruler Ultimate\Cache\AFGC2020.SAV	9.071 KB
C:\Program Files (x86)\Steam\steamapps\common\Supreme Ruler Ultimate\Cache\BAR1941.SAV	8.396 KB
C:\Program Files (x86)\Steam\steamapps\common\Supreme Ruler Ultimate\Cache\BGER.SAV	8.944 KB
C:\Program Files (x86)\Steam\steamapps\common\Supreme Ruler Ultimate\Cache\BINDIA.SAV	8.923 KB
C:\Program Files (x86)\Steam\steamapps\common\Supreme Ruler Ultimate\Cache\BITALY.SAV	9.053 KB
C:\Program Files (x86)\Steam\steamapps\common\Supreme Ruler Ultimate\Cache\BSPAIN.SAV	9.056 KB
C:\Program Files (x86)\Steam\steamapps\common\Supreme Ruler Ultimate\Cache\CAL2020.SAV	9.207 KB
C:\Program Files (x86)\Steam\steamapps\common\Supreme Ruler Ultimate\Cache\CB1942.SAV	7.961 KB
C:\Program Files (x86)\Steam\steamapps\common\Supreme Ruler Ultimate\Cache\ColdWar.SAV	8.622 KB
C:\Program Files (x86)\Steam\steamapps\common\Supreme Ruler Ultimate\Cache\COMP1940.SAV	8.270 KB
C:\Program Files (x86)\Steam\steamapps\common\Supreme Ruler Ultimate\Cache\DS2020.SAV	9.645 KB
C:\Program Files (x86)\Steam\steamapps\common\Supreme Ruler Ultimate\Cache\FIN39.SAV	7.819 KB
C:\Program Files (x86)\Steam\steamapps\common\Supreme Ruler Ultimate\Cache\FL1982.SAV	7.721 KB
C:\Program Files (x86)\Steam\steamapps\common\Supreme Ruler Ultimate\Cache\FR1940.SAV	8.335 KB
C:\Program Files (x86)\Steam\steamapps\common\Supreme Ruler Ultimate\Cache\GAZ1942.SAV	7.707 KB
C:\Program Files (x86)\Steam\steamapps\common\Supreme Ruler Ultimate\Cache\GC2020.SAV	9.293 KB
C:\Program Files (x86)\Steam\steamapps\common\Supreme Ruler Ultimate\Cache\GCP1.SAV	7.433 KB
C:\Program Files (x86)\Steam\steamapps\common\Supreme Ruler Ultimate\Cache\GRE1940.SAV	8.304 KB
C:\Program Files (x86)\Steam\steamapps\common\Supreme Ruler Ultimate\Cache\KAS2020.SAV	9.079 KB
C:\Program Files (x86)\Steam\steamapps\common\Supreme Ruler Ultimate\Cache\MA2020.SAV	9.354 KB
C:\Program Files (x86)\Steam\steamapps\common\Supreme Ruler Ultimate\Cache\PH1941.SAV	7.815 KB
C:\Program Files (x86)\Steam\steamapps\common\Supreme Ruler Ultimate\Cache\Poland39.SAV	7.765 KB
C:\Program Files (x86)\Steam\steamapps\common\Supreme Ruler Ultimate\Cache\SEA1940.SAV	7.910 KB
C:\Program Files (x86)\Steam\steamapps\common\Supreme Ruler Ultimate\Cache\SR1936.SAV	8.211 KB
C:\Program Files (x86)\Steam\steamapps\common\Supreme Ruler Ultimate\Cache\SR1940.SAV	8.328 KB
C:\Program Files (x86)\Steam\steamapps\common\Supreme Ruler Ultimate\Cache\SR1941.SAV	8.399 KB
C:\Program Files (x86)\Steam\steamapps\common\Supreme Ruler Ultimate\Cache\SR1942.SAV	8.399 KB
C:\Program Files (x86)\Steam\steamapps\common\Supreme Ruler Ultimate\Cache\SW2020.SAV	9.628 KB
C:\Program Files (x86)\Steam\steamapps\common\Supreme Ruler Ultimate\Cache\TR2017.SAV	9.273 KB
C:\Program Files (x86)\Steam\steamapps\common\Supreme Ruler Ultimate\Cache\W2020.SAV	9.289 KB

**Comment by ROCKNROLLKID** [comment]
[Steam Games*]
Section=Games
Detect=HKCU\Software\Valve\Steam
Default=False
FileKey1=%ProgramFiles%\Steam\steamapps|*.mdmp;*.tmp;*.dmp;*.icns;.DS_Store;logfile.*;*.log;text.txt;output_log.txt;*log.txt;log*.txt|RECURSE
FileKey2=%ProgramFiles%\Steam\steamapps\common\*\Cache|*.*|RECURSE
FileKey3=%ProgramFiles%\Steam\steamapps\common\*\config\html|*.*|RECURSE
FileKey4=%ProgramFiles%\Steam\steamapps\common\*\DebugData|*.*|RECURSE
FileKey5=%ProgramFiles%\Steam\steamapps\common\*\docs|*.*|RECURSE
FileKey6=%ProgramFiles%\Steam\steamapps\common\*\*\downloads|*.*|RECURSE
FileKey7=%ProgramFiles%\Steam\steamapps\common\*\EULA|*.*|RECURSE
FileKey8=%ProgramFiles%\Steam\steamapps\common\*\Manual|*.*|RECURSE
FileKey9=%ProgramFiles%\Steam\Steamapps\temp|*.*|RECURSE

FileKey 2 is the problem here. I would recommend you create a ExcludeKey for this, as removing this is not very efficient.

**Comment by timse201** [comment]
true but we could also specify the files that could deleted so there would be no issue anymore and also with other games that are not reported so far
all these files are .sav files

**Comment by ROCKNROLLKID** [comment]
Looking through some of the games I have, each caches seem to have different extensions to them. Some have custom made extensions, too. It would be a lot to add all these extensions to that entry. This is the only reported problem have had for Steam cache cleaning, so I think it would just be easier to make the ExcludeKey for this.

**Comment by timse201** [comment]
could be that older versions of this game (2020 gold, cold war, 1936) are affected, too

**Comment by thurask** [comment]
I can verify the following save folders:

Supreme Ruler 1936\Cache
Supreme Ruler 2020\CacheGC
Supreme Ruler Cold War\Cache
Supreme Ruler Ultimate\Cache

**Comment by timse201** [comment]
are these all *.sav files?

**Comment by thurask** [comment]
Correct. All .sav files.
