### ISSUE TITLE
[AVIPreview *] - new entry for winapp2.ini

### ISSUE THREAD

**Issue by aquila-XP** [MoscaDotTo/Winapp2#534]
`[AVIPreview *]`
`LangSecRef=3023`
`Detect=HKCU\Software\Andrei Jefremov\AVIPreview by Andrei Jefremov, visit www.avipreview.com for more`
`Default=False`
`RegKey1=HKCU\Software\Andrei Jefremov\AVIPreview by Andrei Jefremov, visit www.avipreview.com for more\Recent File List`

**Comment by APMichael** [comment]
Already covered by CCleaner: [AVI Preview].
