### ISSUE TITLE
[Download Accelerator Plus (DAP) *] - new entry for winapp2.ini

### ISSUE THREAD

**Issue by aquila-XP** [MoscaDotTo/Winapp2#538]
`[Download Accelerator Plus (DAP) *]`
`LangSecRef=3022`
`Detect=HKCU\Software\SpeedBit\Download Accelerator`
`DetectFile=%ProgramFiles%\DAP\DAP.exe`
`Default=False`
`FileKey1=%CommonAppData%\SpeedBit\DAP\Log|*.log;*.bak`
`FileKey2=%CommonAppData%\SpeedBit\DAP\Temp|*.tmp`
`FileKey3=%CommonAppData%\SpeedBit\DAP\Plugins\Log|*.*`

**Comment by APMichael** [comment]
FileKey1 and 2 already covered by CCleaner: [Download Accelerator Plus].
