### ISSUE TITLE
[Structured Storage Viewer *] - changed entry for winapp2.ini

### ISSUE THREAD

**Issue by aquila-XP** [MoscaDotTo/Winapp2#541]
`[Structured Storage Viewer *]`
`LangSecRef=3024`
`Detect=HKCU\Software\MiTeC\SSViewer`
`Default=False`
`RegKey1=HKCU\Software\MiTeC\SSViewer\3.x\wnd_re_Main\MRUHistory`

Note: Replaced `|` with `\` in front of MRUHistory. I submitted this entry long time ago correctly but Robert Ward changed it.

**Comment by MoscaDotTo** [comment]
> I submitted this entry long time ago correctly but Robert Ward changed it.

Unintentional on my part, sorry about that! 😁 Probably a consequence of one of the major reformats with the help of the original WinappDebug
