### ISSUE TITLE
[iMesh *] - new entry for winapp2.ini

### ISSUE THREAD

**Issue by aquila-XP** [MoscaDotTo/Winapp2#575]
`[iMesh *]`
`LangSecRef=3022`
`Detect=HKCU\Software\iMesh`
`DetectFile=%ProgramFiles%\iMesh Applications\iMesh\iMesh.exe`
`Default=False`
`FileKey1=%ProgramFiles%\iMesh Applications\iMesh|*.log`

**Comment by MoscaDotTo** [comment]
This software is no longer available or functional FWIW.
