### ISSUE TITLE
[Documentation] Please post this files here! 

### ISSUE THREAD

**Issue by winapp2** [MoscaDotTo/Winapp2#6]
https://forum.piriform.com/index.php?showtopic=32310&p=266881

Can someone download these two files and post their content to here. Don't want to sign up just for a download. I think these both files are very interesting.

**Comment by TZocker** [comment]
slao how works github .... 

thx

**Comment by CSGalloway** [comment]
[Winapp2-EXTRA GENERAL.txt](https://github.com/MoscaDotTo/Winapp2/files/435895/Winapp2-EXTRA.GENERAL.txt)
[Winsys2.ini.txt](https://github.com/MoscaDotTo/Winapp2/files/435894/Winsys2.ini.txt)

**Comment by winapp2** [comment]
Thanks Csgalloway
