### ISSUE TITLE
Update removed entries ini to be consistent with all presently removed entries

### ISSUE THREAD

**Issue by MoscaDotTo** [MoscaDotTo/Winapp2#60]
This doesn't need to be done all at once, but if done in chunks should be done alphabetically, I think.

**Comment by ROCKNROLLKID** [comment]
During the overhaul, I attempted to bring back some of the really old ones, but it's really hard now to figure out what exactly has been taken out from long time ago, so I am going to close this as resolved. If anyone knows anything I missed, they can always make a post about it.
