### ISSUE TITLE
Condense different versions of (some?) applications into single entries

### ISSUE THREAD

**Issue by MoscaDotTo** [MoscaDotTo/Winapp2#61]
I'd imagine this can at least be done for entries who are otherwise only different by a version number in the folder name.

Use of wildcards might be easiest for some paths, and would probably help shrink the file in many cases 

Some applications may be better off with disjoint entries though, if the thought arises it should be discussed here

**Comment by ROCKNROLLKID** [comment]
This is currently being done with the development build of Winapp2, so I will go ahead and close this.
