### ISSUE TITLE
[ExamDiff Pro *] - new entry for winapp2.ini

### ISSUE THREAD

**Issue by aquila-XP** [MoscaDotTo/Winapp2#613]
`[ExamDiff Pro *]`
`LangSecRef=3024`
`Detect=HKCU\Software\PrestoSoft\ExamDiff Pro`
`Default=False`
`RegKey1=HKCU\Software\PrestoSoft\ExamDiff Pro\Recent Binary Find Strings`
`RegKey2=HKCU\Software\PrestoSoft\ExamDiff Pro\Recent Center Merged Files`
`RegKey3=HKCU\Software\PrestoSoft\ExamDiff Pro\Recent Find Strings Bin`
`RegKey4=HKCU\Software\PrestoSoft\ExamDiff Pro\Recent Left Directories`
`RegKey5=HKCU\Software\PrestoSoft\ExamDiff Pro\Recent Left Files`
`RegKey6=HKCU\Software\PrestoSoft\ExamDiff Pro\Recent Left Merged Files`
`RegKey7=HKCU\Software\PrestoSoft\ExamDiff Pro\Recent Right Directories`
`RegKey8=HKCU\Software\PrestoSoft\ExamDiff Pro\Recent Right Files`
`RegKey9=HKCU\Software\PrestoSoft\ExamDiff Pro\Recent Session Files`
`RegKey10=HKCU\Software\PrestoSoft\ExamDiff Pro\Recent Sessions`

**Comment by APMichael** [comment]
Most RegKeys are already covered by CCleaner: [ExamDiff Pro].
