### ISSUE TITLE
Winapp2.ini for CCleaner users

### ISSUE THREAD

**Issue by CSGalloway** [MoscaDotTo/Winapp2#62]
Where the website mentions:

"For CCleaner users, download the latest copy of Winapp2. 
Move the copy to your CCleaner directory. "

 - discuss how to achieve this....

**Comment by ROCKNROLLKID** [comment]
I am confused as to what you are trying to ask? Are you asking how to move the file to your CCleaner directory? If so, you just right click on Winapp2, click copy, go to wherever you installed CCleaner to, and paste it there.

**Comment by charishi** [comment]
I whish to ask you where is the winapp2.ini file for ccleaner.
There are two winapp2.ini files but both for non-ccleaner. Current (24Dec2016) winapp2.ini  in https://github.com/moscadotto/winapp2 is for non-ccleaner. It is same file structure of winapp2.ini in https://github.com/MoscaDotTo/Winapp2/tree/master/Non-CCleaner.

**Comment by TZocker** [comment]
It should be 
https://github.com/MoscaDotTo/Winapp2/blob/master/Winapp2.ini

**Comment by charishi** [comment]
Thanks!

**Comment by ROCKNROLLKID** [comment]
I closed this due to no response to my previous question. Re-open if you are still having a issue.
