### ISSUE TITLE
Many duplicate keys in non-CCleaner/Winapp2.ini

### ISSUE THREAD

**Issue by az0** [MoscaDotTo/Winapp2#65]
One example (4sync):
https://github.com/MoscaDotTo/Winapp2/blob/master/Non-CCleaner/Winapp2.ini#L22207

https://github.com/MoscaDotTo/Winapp2/blob/master/Non-CCleaner/Winapp2.ini#L21807

List of duplicates

> [4Sync*]
> [Adobe Dreamweaver MRU*]
> [Adobe Reader 11 Recent File List*]
> [Aimersoft Video Converter Ultimate*]
> [AIM More*]
> [Alcohol 120% Log*]
> [Anonymizer Log*]
> [Ashampoo Burning Studio 14 Extras*]
> [Camtasia Studio 8*]
> [CoolNovo - Cache*]
> [CoolNovo - Cookies*]
> [CoolNovo - Form Data*]
> [CoolNovo - History*]
> [CoolNovo - Session Restore*]
> [Copernic Agent*]
> [Copernic Desktop Search*]
> [dBpoweramp*]
> [Directory Opus Logs*]
> [DVDFab (Logs)*]
> [DVDFab Passkey (Logs)*]
> [FastStone Capture Extras*]
> [HandBrake Logs*]
> [Live Kernel Watchdog*]
> [MailWasher Pro*]
> [Memory Dumps*]
> [Microsoft Visio 2010*]
> [MS Office OneDrive*]
> [MS Office Temp Files*]
> [Nvidia Graphics Driver Installation Files*]
> [Office 2016*]
> [PDFCreator*]
> [Picasa Log*]
> [PKZip*]
> [Recent Picture Locations*]
> [SketchUp Make 2013*]
> [Snagit 12*]
> [Stored HSTS Cookies*]
> [SyncBackFree*]
> [Tag&Rename 3.7*]
> [TeamViewer Connections*]
> [TeamViewer Temporary Files*]
> [Temp Files*]
> [Universal Extractor*]
> [VirtualCloneDrive*]
> [Windows CBS Logs More*]
> [Windows Defender Extras*]
> [Windows Log Files Extras*]
> [Wondershare Video Converter Pro Extras*]

**Comment by ROCKNROLLKID** [comment]
Looks like a second removed entry section got added at the bottom. I removed it. Should solve this issue, correct?

**Comment by az0** [comment]
Yes, solved.
