### ISSUE TITLE
Winapp2 with CCleaner

### ISSUE THREAD

**Issue by Gitoffthelawn** [MoscaDotTo/Winapp2#697]
I gave Winapp2.ini a try with CCleaner Portable v5.65.

Questions:

1) Without Winapp2, CCleaner loads instantly, and displays its tabs right away.  With Winapp2, it takes over 20 seconds for the "Applications" tab in CCleaner to display.  Is this a known issue and is there any way to improve this?

2) Winapp2 is designed to delete unneeded registry keys/values.  But, for Winapp2 items, CCleaner does not show any indication of what registry keys/values will be deleted, even with its "Analyze" function.  Furthermore, the Registry tab of CCleaner does not list any of the additions provided by Winapp2.
   a) Are the Winapp2 registry items actually deleted by CCleaner?
   b) If so, is it when performing a "Custom Clean" (which lists Winapp2 apps) or a "Registry Clean" (which does not list the Winapp2 apps)?
   c) Is there any way in CCleaner to preview the registry keys/values being deleted by Winapp2 entries?
   d) Is there any way in CCleaner to see what registry keys have been deleted by Winapp2 entries after the fact?

Thanks!

**Comment by APMichael** [comment]
1. This is not an issue, after all CCleaner has to process thousands of entries after adding the Winapp2.ini. You can use the Trim function of Winapp2ool after each update of Winapp2.ini.

2. a) Yes.
b) Custom Clean.
c) Unfortunately not possible.
d) Unfortunately not possible.
