### ISSUE TITLE
[Question] Will browsers based on others be labeled? 

### ISSUE THREAD

**Issue by winapp2** [MoscaDotTo/Winapp2#7]
Will browsers based on others be labeled? For example Palemoon and then the label [Mozilla] because it's based on Mozilla. I think this is very important.

**Comment by winapp2** [comment]
[Palemoon Cache (Mozilla)] 

This looks much more great for me.

**Comment by TZocker** [comment]
other detection or same as firefox?

**Comment by ROCKNROLLKID** [comment]
Interesting idea, but when will this really be needed?

**Comment by winapp2** [comment]
It's much more readable.

**Comment by MoscaDotTo** [comment]
Seems superfluous to me as we group these entries by their LangSecRef which is unique to the browser. 

Most of the existing Mozilla labels are to differentiate from Chrome labels as CCleaner doesn't support multiple entries with the same name

**Comment by winapp2** [comment]
PR sent, closing this.
