### ISSUE TITLE
Winapp2ool: VirusTotal, alarming results

### ISSUE THREAD

**Issue by ivasemma-6872** [MoscaDotTo/Winapp2#700]
Dear developer,
Here are the results provided by VirusTotal on your latest version of winapp2ool (Windows): they are particularly disturbing...
https://www.virustotal.com/gui/file/36eb49dec1dbce18ce64f3fbd865e8ec19b566bf70727455535ed893c4114e7b/detection
For my part, I have already run the software on my computer. I hope these are just false alarms.
Thank you.
Best regards,

**Comment by MoscaDotTo** [comment]
They are false positives, fear not! I am working on rebuilding winapp2oolXP to be up to date with the latest changes. The current beta build of the tool doesn't get flagged so hopefully that translates to the updated winapp2oolxp not getting flagged either.

**Comment by ivasemma-6872** [comment]
All right, thank you.
I add that you also have a similar result with your file ./Winapp2/tree/master/winapp2ool/bin/Release/winapp2ool.exe :
https://www.virustotal.com/gui/file/f6fad4ba2b446e8d89ade409455f6312c757d61772310375adad2c3e6131b0bc/detection
Thank you.
Best regards,

**Comment by MoscaDotTo** [comment]
https://www.virustotal.com/gui/file-analysis/MDExNmI0YTVjMzhjYTNjMjZjNDUzODAxN2E5MDJkNjI6MTU4NzUxMTQ1MA==/detection

going to keep an eye on the release configurations and see if the false positive flags resurface

**Comment by MoscaDotTo** [comment]
They're back lol.

**Comment by MoscaDotTo** [comment]
https://www.virustotal.com/gui/file/9ccd4503891baf12ce66d824445ff2105f573936fc71fd15020b1eb972d39bed/detection

**Comment by MoscaDotTo** [comment]
I have high hopes that the changes I've made in this build will both solve our false positive flagging and allow me to restore the automatic update checking on the beta branch without having it sit behind a setting

**Comment by MoscaDotTo** [comment]
I built a version that did not access the internet and it was still flagged, so I assumed it had to be the way I was reading the version info from the executables. When I initially implemented this, I did so in a way that would allow me to read the manifest without placing a file system lock on the file, but this turned out to be a bit of a hack and there was an existing API for it. Hoping that this was the underlying issue the whole time

**Comment by APMichael** [comment]
Thanks for the update. I keep my fingers crossed that the false positives will stay away now.

**Comment by MoscaDotTo** [comment]
I think we're finally clear on the virustotal front. Hooray!

**Comment by ShaneGowland** [comment]
Hey Robbie; can't currently download the .zip version of the repository. Google Chrome is nuking it with a 'virus detected' claim.

Hope you're doing well and staying safe btw :)

**Comment by MoscaDotTo** [comment]
WFM in Firefox 77 and Chrome 79. I've had issues with Google holding over on new builds when old ones were flagged though in the past. 

Safe and sound quaratined away from my nyc workplace for now, hope you're staying safe and healthy as well :)

**Comment by MoscaDotTo** [comment]
Updated Chrome to version 84 and still WFM
