### ISSUE TITLE
[WinappDebug] New browser sections

### ISSUE THREAD

**Issue by APMichael** [MoscaDotTo/Winapp2#704]
CCleaner now supports the browsers Brave and Vivaldi directly. Therefore we probably need new top sections in Winapp2.ini again. Can you please add the LangSecRefs 3033 (Vivaldi) and 3034 (Brave) and sort them in new top sections?

If you need to change something anyway, you can also allow LangSecRef 3001. A new top section is **not** necessary for this. I have received several requests if we cannot assign the correct LangSecRef to the two IE entries...

Many thanks in advance.

**Comment by MoscaDotTo** [comment]
Would it be worthwhile to consider using other LangSecRefs that are built into CCleaner that we don't currently use? Eg. 3002 is "Windows Explorer" and I can imagine quite a few entries from "Windows" making sense in that category

**Comment by MoscaDotTo** [comment]
We don't need to make top level categories for all of them but I'll make sure WinappDebug doesn't throw a fit over it

**Comment by MoscaDotTo** [comment]
WinappDebug should now be OK with any valid CCleaner LangSecRef and should create top level sections for Vivaldi, Brave, and Internet Explorer. Edge Insider should now be called Edge Chromium

**Comment by APMichael** [comment]
Many thanks for the quick implementation.

Unfortunately there is a problem, everything after "; End of Thunderbird" is cut off.

Now that "Internet Explorer" also has its top level section, shouldn't we include "Microsoft Edge" (3005, the previous version) and "CCleaner Browser" (3032) as top level sections? Then every browser has its top level section.

**Comment by MoscaDotTo** [comment]
This should be fixed now, sorry about that. In a previous update I had changed `winapp2file.vb` to be a little more agnostic towards the total # of top level sections but the work wasn't totally complete, so adding sections broke things a bit. 

I also removed the code that would handle the two disjoint Edge sections

**Comment by APMichael** [comment]
Works with Winapp2.ini, but Winapp3.ini is now empty (except the header text).

**Comment by APMichael** [comment]
Great, with the latest version it now works as expected! 😃 

Thanks a lot, also for the further enhancements. 👍
