### ISSUE TITLE
Error since version 1.4.7419.18289. Windows 7 SP1 x86

### ISSUE THREAD

**Issue by vodek3** [MoscaDotTo/Winapp2#711]
Since version 1.4.7419.18289 in Windows 7 SP1 x86, the following error:

 ```
 ╔════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
 ║                                       Trimming... Please wait, this may take a moment...                                   ║
 ╚════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝

Unhandled Exception: System.ArgumentException: The path is not of a legal form.
   в System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   в System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   в System.IO.Path.GetFullPathInternal(String path)
   в System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption sea
rchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   в System.IO.Directory.GetDirectories(String path, String searchPattern)
   в winapp2ool.Trim.expandWildcard(String dir, Boolean isFileSystem)
   в winapp2ool.Trim.checkPathExist(String key)
   в winapp2ool.Trim.checkExistence(keyList& kl, Func`2 chkExist)
   в winapp2ool.Trim.processEntryExistence(winapp2entry& entry)
   в winapp2ool.Trim._Closure$__36-0._Lambda$__0(winapp2entry entry)
   в System.Collections.Generic.List`1.ForEach(Action`1 action)
   в winapp2ool.Trim.processEntryList(List`1& entryList)
   в winapp2ool.Trim.trimFile(winapp2file winapp2)
   в winapp2ool.Trim.initTrim()
   в winapp2ool.Trim.handleUserInput(String input)
   в winapp2ool.MenuMaker.initModule(String name, Action showMenu, Action`1 handleInput, Int32 itmLen)
   в winapp2ool.Winapp2ool.handleUserInput(String input)
   в winapp2ool.MenuMaker.initModule(String name, Action showMenu, Action`1 handleInput, Int32 itmLen)
   в winapp2ool.Winapp2ool.main()
```

Under Windows 10 x64 version 1.4.7419.18289 works correctly

**Comment by MoscaDotTo** [comment]
Does this issue occur on the beta build? You can switch to the beta from the application's settings or from this link https://github.com/MoscaDotTo/Winapp2/tree/Branch1/winapp2ool/bin/Release

If so, does this crash the application entirely? I've updated the beta to handle exceptions generally on this function and give a little more information. If you could run trim again on the beta build and read from winapp2ool.log the entry & path that caused the error that'd help a lot!

**Comment by vodek3** [comment]
`╔═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗  ║                                                            Trimming... Please wait, this may take a moment...                                                         ║  ╚═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝ Error: System.ArgumentException Encountered
System.ArgumentException: Путь имеет недопустимую форму.
   в System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   в System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   в System.IO.Path.GetFullPathInternal(String path)
   в System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   в System.IO.Directory.GetDirectories(String path, String searchPattern)
   в winapp2ool.Trim.expandWildcard(String dir, Boolean isFileSystem)
Please report this error on GitHub. It will be saved to winapp2ool.log in the same folder as winapp2ool.
Press Enter to continue`

**Comment by vodek3** [comment]
**winapp2ool.log:**
[winapp2ool.log](https://github.com/MoscaDotTo/Winapp2/files/4637424/winapp2ool.log)

**Comment by MoscaDotTo** [comment]
thank you!

**Comment by vodek3** [comment]
Anything else?

**Comment by MoscaDotTo** [comment]
Keep your eye out for updated beta builds and let me know if anything changes :)

**Comment by vodek3** [comment]
With build  winapp2ool 1.4.7441.15296 it seems that works!

`╔════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
║                                                    Trim Complete                                                   ║
╠════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╣
║                                                      Entry Count                                                   ║
║                                                                                                                    ║
║ Initial: 2437                                                                                                      ║
║ Trimmed: 173                                                                                                       ║
║ 2264 entries trimmed from winapp2.ini (93%)                                                                        ║
║                                                                                                                    ║
║ Press any key to return to the menu.                                                                               ║
╚════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝`

**Comment by MoscaDotTo** [comment]
Glad the issue is fixed! 

I've purchased a code signing certificate and am awaiting validation for it, so hopefully messages like this go away!
