### ISSUE TITLE
[Suggestion] Winapp4

### ISSUE THREAD

**Issue by Dutchman101** [MoscaDotTo/Winapp2#713]
Hi,

I am an advanced user that always combines Winapp2.ini and Winapp3.ini, then runs it regularly with all options selected and has never ran into a stability issue or any consequences of 'dangerous entries'. Therefore, doing this and using all possible options remains my preference.

Every time that either of these files get updated in your repository, I manually combine the latest versions of both (paste Winapp3.ini contents at the end of Winapp2.ini). My suggestion is to add another flavor of Winapp, where both ini's are already combined. This would spare myself time, and it can give other users a hint of the possibility to get an even more thorough cleaning procedure.

Thanks for considering!

**Comment by MoscaDotTo** [comment]
you can do this with winapp2ool! 

First configure winapp2ool to save your settings (so you don't need to reconfigure it each time) 

winapp2.ini can be updated through the main menu whenever an update is available and both files can be downloaded through the Downloader options too

The merge module will merge the two files and save it as whatever you like - there are two settings for collision detection but there should be no conflicts between these files to my awareness

**Comment by APMichael** [comment]
@MoscaDotTo 

Couldn't you also create a batch script? Then all you need is a double click. But what would be the correct command line for "Merge"?
```
winapp2ool download winapp2 -s
winapp2ool download winapp3 -s
winapp2ool merge ??? -s
```
By the way, I noticed that Winapp2ool crashes when the command line is already elevated (admin rights):
```
Unhandled exception: System.IO.FileNotFoundException: winapp2ool
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at winapp2ool.Winapp2ool.main()
```

**Comment by APMichael** [comment]
Okay, I figured out the command line. Here the batch script to create the Winapp4.ini:
```
@ECHO OFF
CLS
CD /D "%~dp0"
ECHO Downloading Winapp2.ini ...
winapp2ool.exe download winapp2 -s
ECHO Downloading Winapp3.ini ...
winapp2ool.exe download winapp3 -s
ECHO Merging Winapp2.ini with Winapp3.ini to Winapp4.ini ...
winapp2ool.exe merge -2f winapp3.ini -3f winapp4.ini -s
ECHO Done!
TIMEOUT /T 5
```
Just copy the text into a text file and name it e.g. winapp4.bat. Move the file into the directory of Winapp2ool, right-click it and select "Run as administrator".

I think this is the easiest solution for all who are interested in a Winapp4.ini. (But I would rather not add the Winapp4.ini directly to the GitHub repository.)

**Comment by MoscaDotTo** [comment]
> Edit: Winapp2ool does not crash when using "winapp2ool.exe".
Interesting. I have a feeling that the commandline handling in general may be broken in some places because it occurs before settings are loaded from disk and hasn't been updated to address a bunch of new features (ie. trimming with white/blacklisting now requires the ability to configure a -4f but no such feature exists yet)  I've been meaning to take a look at it.

**Comment by Dutchman101** [comment]
Thanks, these tools will make it easier for me to do that.

But..
> I think this is the easiest solution for all who are interested in a Winapp4.ini. (But I would rather not add the Winapp4.ini directly to the GitHub repository.)

The combination of them has serious benefits for a more thorough cleaning, adding it as a separate flavor will bring it to the attention (and be used by) more users, not just those that are willing to go the extra mile for merging them or finding these nice ways to merge them automatically.

Maybe it's doable and safer if you:
- add a more severe caution about the risks (even though I used all options on multiple systems with plenty of applicable software, without ever messing something up, but that might be luck)
- untick the boxes with highest risk/slow scanning speed by default, such as "Dangerous Long"

But in the end, this is just a suggestion.. I (and others that wanted this) already got enough to merge more efficiently.

**Comment by APMichael** [comment]
Thank you for your reply and your thoughts on the topic. 👍 

Let us see if we can do this in some way in the future.
