### ISSUE TITLE
Small change on Star Citizen entry

### ISSUE THREAD

**Issue by hvcrios** [MoscaDotTo/Winapp2#715]
It's such a small thing that I think going through the strenuous work of syncing and rebasing my repository wasn't worth it

here's how it currently is:

```
 [Star Citizen *]
 Section=Games
 DetectFile1=%AppData%\rsilauncher
 DetectFile2=%LocalAppData%\Star Citizen
 FileKey1=%AppData%\RSI Launcher|*.*|RECURSE
 FileKey2=%AppData%\rsilauncher|*.log;*.jpg
 FileKey3=%AppData%\rsilauncher\*Cache|*.*
 FileKey4=%AppData%\rsilauncher\_update_|*.*
 FileKey5=%LocalAppData%\Star Citizen|*.*
 FileKey6=%ProgramFiles%\Roberts Space Industries\StarCitizen\LIVE|*.log|RECURSE
```

All I wanted to do was change the "FileKey4" pattern to:

`FileKey4=%AppData%\rsilauncher\*update*|*.*`

Should've done that in the first place, some funny person decided to change the folder from `_update_` to `__update__` for whatever reason... so it's not catching that anymore.

Thanks in advance.

**Comment by APMichael** [comment]
Thanks for the revised entry. I will add it with the next update.
