### ISSUE TITLE
Please don't remove items from Winapp2.ini based on ccleaner

### ISSUE THREAD

**Issue by Skrell** [MoscaDotTo/Winapp2#726]
Not all of us use ccleaner and I would appreciate having the additional filtering capabilities built into the winapp2.ini file.  Hope that makes sense.

**Comment by APMichael** [comment]
This is exactly the reason why you can also download a non-CCleaner version of Winapp2.ini.

https://github.com/MoscaDotTo/Winapp2#files-of-interest-on-this-repo

**Comment by Skrell** [comment]
My apologies I did not realize that! Many thanks!

**Comment by APMichael** [comment]
That's all right. Glad I could help. 😃
