### ISSUE TITLE
difference between ccleaner+winapp2+winapp3 and bleachit+winapp2+winapp3

### ISSUE THREAD

**Issue by Janaue** [MoscaDotTo/Winapp2#734]
Hi

I struggle to see the difference between  ccleaner+winapp2+winapp3 and bleachit+winapp2+winapp3. Is there one ?

**Comment by APMichael** [comment]
As far as I know, BleachBit always uses its own Winapp2.ini file. Therefore, a custom file (e.g. one merged from Winapp2.ini and Winapp3.ini) is always overwritten by default when BleachBit starts:

https://github.com/bleachbit/winapp2.ini

Also, BleachBit currently still has a bug and deletes too many files:

https://github.com/bleachbit/bleachbit/issues/982

**Comment by Janaue** [comment]
yes i disabled the auto update in bleachBit.

**Comment by Janaue** [comment]
I thought that Bleachbit used your winapp2, because on your page, it is written

    Open BleachBit.
    Select the "Edit" tab, and then "Preferences".
    Check the box that reads "Download and update cleaners from community (Winapp2.ini)".
    Note: BleachBit 2.2 is the last version to work on Windows XP. Winapp2.ini and Winapp3.ini will continue to work with this version.


so i understand that bleachbit downloads your winapp2 since is just have to check the box for auto-update. However I always prefer winapp2+winapp3, so even if they are the same, i need the little exe winapp2ool.exe to get the merger.

**Comment by APMichael** [comment]
> yes i disabled the auto update in bleachBit.

Ok, except for the bug, there is practically no difference then. Except that BleachBit does not support exclusions for registry values, but only one entry uses them: [Windows ShellBags *]

> I thought that Bleachbit used your winapp2, ...

The author of BleachBit prefers to review the file before making it available to his users.
