### ISSUE TITLE
CCleaner updater file entry

### ISSUE THREAD

**Issue by lenrussel** [MoscaDotTo/Winapp2#739]
Please update this entry in winapp3 as the updater file has been changed to **CCUpdate.exe**

[CCleaner Updater Removal *]
Section=Dangerous Utilities
Detect=HKCU\Software\Piriform\CCleaner
Warning=You will need to manually update CCleaner after running this.
FileKey1=%ProgramFiles%\CCleaner|**CCupdater.exe**

**Comment by APMichael** [comment]
Thanks for the tip. This seems to have been a long overlooked typo.
