### ISSUE TITLE
[Feature Request] Microsoft Teams cleanup

### ISSUE THREAD

**Issue by ltdeta** [MoscaDotTo/Winapp2#743]
I have found only the configuration for CCCleaner
https://albandrodsmemory.wordpress.com/2019/01/04/microsoft-teams-how-to-clean-cache/

I am not the creator, so I can not say 100% if the formatting is correct

> 
> [Microsoft Teams ]
> LangSecRef=3021
> Default=True
> DetectFile=%LocalAppData%\Microsoft\Teams
> FileKey1=%AppData%\Microsoft\Teams\application cache\cache||RECURSE
> FileKey2=%AppData%\Microsoft\Teams\blob_storage||RECURSE
> FileKey3=%AppData%\Microsoft\Teams\Cache||RECURSE
> FileKey4=%AppData%\Microsoft\Teams\databases||RECURSE
> FileKey5=%AppData%\Microsoft\Teams\GPUcache||RECURSE
> FileKey6=%AppData%\Microsoft\Teams\IndexedDB||RECURSE
> FileKey7=%AppData%\Microsoft\Teams\Local Storage||RECURSE
> FileKey8=%AppData%\Microsoft\Teams\tmp||RECURSE
> FileKey9=%AppData%\Microsoft\Teams\Service Worker\CacheStorage||REMOVESELF
> FileKey10=%AppData%\Microsoft\Teams|old_logs_.txt
> ;remove previous version:
> FileKey11=%LocalAppData%\Microsoft\Teams\previous|.*|REMOVESELF

**Comment by APMichael** [comment]
Thank you for pointing this out.

This entry should work:
```
[Microsoft Teams *]
LangSecRef=3021
DetectFile=%LocalAppData%\Microsoft\Teams
FileKey1=%AppData%\Microsoft\Teams|old_logs_*.txt
FileKey2=%AppData%\Microsoft\Teams\*Cache|*.*|RECURSE
FileKey3=%AppData%\Microsoft\Teams\blob_storage|*.*|RECURSE
FileKey4=%AppData%\Microsoft\Teams\databases|*.*|RECURSE
FileKey5=%AppData%\Microsoft\Teams\IndexedDB|*.*|RECURSE
FileKey6=%AppData%\Microsoft\Teams\Local Storage|*.*|RECURSE
FileKey7=%AppData%\Microsoft\Teams\Service Worker\CacheStorage|*.*|REMOVESELF
FileKey8=%AppData%\Microsoft\Teams\tmp|*.*|RECURSE
FileKey9=%LocalAppData%\Microsoft\Teams\previous|*.*|REMOVESELF
```
I will add it with the next update.
