### ISSUE TITLE
TeraCopy entry update in winapp3.ini

### ISSUE THREAD

**Issue by lenrussel** [MoscaDotTo/Winapp2#744]
Please update TeraCopy entry, as all the directory locations have been updated since v3.5 to
C:\Program Files\TeraCopy\
C:\Program Files\TeraCopy\App\Languages

[TeraCopy Languages *]
Section=Language Files
Detect=HKCU\Software\Code Sector\TeraCopy
Warning=This will delete all languages excluding English.
FileKey1=%ProgramFiles%\TeraCopy\locale|*.*

**Comment by APMichael** [comment]
Thanks, I hope this entry works as desired. It should now support the new, but also the old versions.

```
[TeraCopy Languages *]
Section=Language Files
Detect=HKCU\Software\Code Sector\TeraCopy
Warning=This will delete all languages excluding English.
FileKey1=%ProgramFiles%\TeraCopy\App\Languages|*.*
FileKey2=%ProgramFiles%\TeraCopy\locale|*.*
```
Will be added with the next update.
