### ISSUE TITLE
NVIDIA * Entry removes Geforce Experience login data

### ISSUE THREAD

**Issue by MoscaDotTo** [MoscaDotTo/Winapp2#747]
Reported to me via email, the affected file was reported to be 

%localappdata%\NVIDIA Corporation\NVIDIA GeForce Experience\CefCache\IndexedDB\*.LOG

we should probably move this to a separate entry as i believe the geforce experience does not do anything if you're not logged into it

**Comment by TZocker** [comment]
Sorry, i can't reproduce that issue.

Sometimes I have to update my login, after time/ or reinstall.

**Comment by APMichael** [comment]
This is certainly an unintended side effect of FileKey12:

```
FileKey12=%LocalAppData%\NVIDIA Corporation|*.log;*.bak;*.old|RECURSE
```

FileKey12 uses RECURSE to clean up the various subfolders as well. Unfortunately, the subfolder "CefCache" is Chromium-based and therefore *.log files are database files there.

The proposed exception should work:
```
ExcludeKey1=PATH|%LocalAppData%\NVIDIA Corporation\*\CefCache\IndexedDB\|*.log
```
