### ISSUE TITLE
Add Media Playback History to all chromium-based browsers

### ISSUE THREAD

**Issue by KosMos-pv** [MoscaDotTo/Winapp2#752]
I have Opera 75 and it also creates Media History file in its profile folder. In my case it's located here - C:\Users\KosMos\AppData\Roaming\Opera Software\Opera Stable\Media History and C:\Users\KosMos\AppData\Roaming\Opera Software\Opera Stable\Media History-journal. So this entry should be expanded for all chromium-based browsers, not only Google Chrome and Edge.

**Comment by APMichael** [comment]
Thanks for pointing this out.
