### ISSUE TITLE
Request to add Mega.nz's MegaSync Cache

### ISSUE THREAD

**Issue by pogue** [MoscaDotTo/Winapp2#754]
I've searched all over my PC for the entries for the MegaSync cache for the utility that downloads and uploads files to a mega.nz account. I searched the whole C drive, including %appdata% although I didn't search the registry.

You can download MegaSync here:
https://help.mega.nz/megasync/getting-started.html#what-is-megasync

If anyone can figure out where the cache is and add it to winapp2.ini it would be most appreciated.

**Comment by APMichael** [comment]
After a quick search, I could only find references to log and crash files. All these files are located in subfolders of the folder:
`C:\Users\<YourUserName>\AppData\Local\Mega Limited\MEGAsync`
Maybe you can also find the folder for the cache files in there?

```
[MEGAsync *]
LangSecRef=3023
DetectFile=%LocalAppData%\Mega Limited\MEGAsync
FileKey1=%LocalAppData%\Mega Limited\MEGAsync\crashDumps|*.*
FileKey2=%LocalAppData%\Mega Limited\MEGAsync\logs|*.*
```

**Comment by pogue** [comment]
I just checked the wiapp2.ini and it contained the following strings:

[code][MEGAsync *]
LangSecRef=3022
DetectFile=%LocalAppData%\Mega Limited\MEGAsync
FileKey1=%LocalAppData%\Mega Limited\MEGAsync\crashDumps|*.*
FileKey2=%LocalAppData%\Mega Limited\MEGAsync\logs|*.*[/code[

**Comment by APMichael** [comment]
As written in my previous post, the new [MEGAsync \*] entry only cleans log and crash files.

You can check if you can find a subfolder for cache files under `C:\Users\<YourUserName>\AppData\Local\Mega Limited\MEGAsync`. If not, it obviously does not exist.

Maybe this info will help: https://www.reddit.com/r/techsupport/comments/30l5o3/where_can_i_find_megas_cache/cptj2dv/?context=3

Then you would simply have to clean Chrome's cache, which is already built into CCleaner.

**Comment by pogue** [comment]
I'm not using Chrome to download. I'm using MegaSync exclusively.

**Comment by APMichael** [comment]
Maybe you should ask the customer support of "MEGA" if the "MEGAsync" client creates cache files and where it stores them?
