### ISSUE TITLE
Code Signing Certificate will expire June 11

### ISSUE THREAD

**Issue by MoscaDotTo** [MoscaDotTo/Winapp2#755]
Hey everyone :) Just wanted to let you know that the code signing certificate that I use to sign winapp2ool will expire in June and I will not be renewing it immediately. This is because I'm in the process of legally changing my name and do not want my old name to continue appearing on the certificate. After June 11 for some indeterminate amount of time, the certificate will no longer be valid and you may see winapp2ool flagged as malware (erroneously)

**Comment by APMichael** [comment]
Thanks for the info.

**Comment by MoscaDotTo** [comment]
Mercifully this issue is finally resolved

**Comment by APMichael** [comment]
Great news! And thanks for the new version.
