### ISSUE TITLE
Possible duplication in FileKey1 of [MS SQL Server]

### ISSUE THREAD

**Issue by rados** [MoscaDotTo/Winapp2#756]
I've just noticed that we have:

"
[MS SQL Server *]
...
FileKey1=%ProgramFiles%\Microsoft SQL Server\*\MSSQL\Log|\*ERRORLOG\*;\*.\*|RECURSE
"

I am wondering if the "\*ERRORLOG\*" is excessive, as we have "\*.\*" anyway?

Thanks.

**Comment by APMichael** [comment]
Thank you for pointing this out. Correct, with the search pattern "\*.\*" no further search patterns are necessary.
