### ISSUE TITLE
Latest Winapp2.ini caused black screen with mouse cursor on Windows 10.

### ISSUE THREAD

**Issue by ariskos** [MoscaDotTo/Winapp2#76]
Hello i recently re-format my computer and i had come to this issue displayed in the title.
I will try to be as detailed i can be so you can resolve the issue :

Previously i had legacy-bios MBR on my OCZ vertex 3 and now i have UEFI with GPT on my ssd, The installation was done with "diskpart" , selected the volume "clean" , "convert gpt" and installed on the disk(4th partition that has been created). After Windows Installation i immediately used "Windows Upgrade Assistant" to update to the latest revision

> Version 10.0.14393 Build 14393

after that i installed "CCleaner" and cleaned the system. My CCleaner settings were

> Options->Advanced->Only delete files in Windows Temp folders older than 24 hours(Unchecked)

Then i **checked everything** on Cleaner-Windows  & Cleaner-Applications Tab, also i did the **registry cleanup** and rebooted. PC worked flawlessly at this point. 

Now the real problem comes up i downloaded 

> **winapp2.ini** and **trim** placed on CCleaner folder and trimmed the system

Then i started the cleaning process again with all things checked and 

> Rebooted

Boom! my 

> Computer boots up with a black screen and a mouse cursor only.

I didn't have access to the explorer but the system seemed to be working background (i tried START+R and typed explorer.exe blindly and the cursor was "loading" this indicates that it runs correct on the background but i could only see the mouse and a black screen. 

Normally i wouldn't post for an issue if i don't replicate it so i tried again the same procedure (Re-formated,Installed latest revision,run ccleaner with winapp2.ini). Second time white cursor with black screen.

> Replicated the installation of windows with CCleaner & winapp2.ini and again i have a black screen.

 I don't wanna spent more time testing it to find the **exact** key that causes this but i gave you enough information to try it on a virtual machine. Thank you for your time.

**Comment by ROCKNROLLKID** [comment]
The only thing I can think of that was recently done was maybe the entry "[Fontcache More*]. Can you test that entry out and see if it is the problem?

If not, then the only way to know is to go through them one at a time. You can do section by section to help speed up the process. So far, no one else has reported this and my Windows 10 system is running fine with running almost all the entries.

**Comment by Nergal-di-Cuthah** [comment]
"Then i started the cleaning process again with all things checked" including registry or no? It's hard to tell if you just check everything off, though it is disturbing that one of the winapp2 entries would cause this. I'd be interested to see if somebody can recreate this (if not registry related)

**Comment by ariskos** [comment]
I tried to run winapp2.ini without **trim** and it worked without causing any issues i will try with trim now and post back

**Comment by ariskos** [comment]
I am really sorry for spending your time , it works with trim also and the issue was simple yet stupid :/.

> chkdsk /R /F C:

**Comment by Nergal-di-Cuthah** [comment]
What was the issue though? What caused this...enquiring minds

**Comment by deadair3210** [comment]
if it was fixed by chkdsk, i would assume it was a filesystem or disk issue, not a ccleaner or winapp2 issue
