### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by ROCKNROLLKID** [MoscaDotTo/Winapp2#77]
@MoscaDotTo Check your PM at Piriforms. Thinking about putting the donation links here at GitHub, as well.

**Comment by MoscaDotTo** [comment]
Sorry for the late reply :) I've no issue with what you said in the pm.

**Comment by ROCKNROLLKID** [comment]
I am kind of new to PayPal, but how do you set up a donation link like you did? I only find how to make a donation button, but I just want a donation link instead.
