### ISSUE TITLE
New and modified entries for winapp2.ini (A letter)

### ISSUE THREAD

**Issue by aquila-XP** [MoscaDotTo/Winapp2#776]
`[Advanced IP Scanner *]`
...
Note: Please rearrange the order of the lines. `RegKey5` should be in place of `RegKey2`.

`[Advanced Port Scanner *]`
...
Note: Please rearrange the order of the lines. `RegKey9` should be in place of `RegKey3`.

`[AMD/ATI *]`
...
Note: Please rearrange the order of the lines. `FileKey5` should be in place of `FileKey4`.

`[Apowersoft Streaming Audio Recorder *]`
...
`DetectFile=%AppData%\ApowerSoft\Streaming Audio Recorder`
`FileKey3=%AppData%\ApowerSoft\Streaming Audio Recorder\log|*.log`

`[Ares *]`
...
`DetectFile=%LocalAppData%\Ares`

Note: I understand that you try to keep the file as small as possible.
The reason I add `Detect=` line and also an additional `DetectFile=` line is because I found that if an application is uninstalled (the files from `%ProgramFiles%` directory and Registry entries are removed), but there are many files left behind in %AppData% folder that CCleaner no longer detects them.
In the case of `[Pocket Killbox *]` entry, if someone mannually removes `%SystemDrive%\!Killbox` folder, the Registry line (`HKCU\Software\KillBox|LastPath`) is not detected if there is no `Detect=` line.
If I uninstall "Ares Galaxy" program, the Registry key - `HKCU\Software\Ares` is removed, but the files on `%LocalAppData%\Ares` folder are not. If I don't have an extra detection option, those files are not detected.

`[Ashampoo Registry Cleaner *]`
`LangSecRef=3024`
`DetectFile=%ProgramFiles%\Ashampoo\Ashampoo Registry Cleaner*`
`FileKey1=%CommonAppData%\Ashampoo|ico_ashampoo_deals.ico`
`FileKey2=%LocalAppData%\Ashampoo\boxshots|*.png`
`FileKey3=%ProgramFiles%\Ashampoo\Ashampoo Registry Cleaner*\Backups|*.*`

`[Ashampoo WinOptimizer *]`
`LangSecRef=3024`
`DetectFile=%ProgramFiles%\Ashampoo\Ashampoo WinOptimizer*`
`FileKey1=%ProgramFiles%\Ashampoo\Ashampoo WinOptimizer*\Backups|*.ini;*.reg`

`[Asmwsoft PC Optimizer *]`
`LangSecRef=3024`
`DetectFile=%ProgramFiles%\Asmwsoft PC Optimizer\Asmwsoft PC-Optimizer.exe`
`FileKey1=%ProgramFiles%\Asmwsoft PC Optimizer|eraselog.txt`

`[ASUS Logs *]`
...
`DetectFile4=%LocalAppData%\AcSdkInsLog`
`FileKey5=%LocalAppData%\AcSdkInsLog|*.*`

`[Atlantis Quest *]`
`Section=Games`
`DetectFile=%ProgramFiles%\GameTop.com\Atlantis Quest\Atlantis.exe`
`FileKey1=%ProgramFiles%\GameTop.com\Atlantis Quest|Error.log`

`[Atomic Cleaner *]`
...
`FileKey2=%LocalAppData%\Atomicware\AtomicCleaner*\Logs|*.*`

`[Auslogics BoostSpeed *]`
...
`FileKey4=%ProgramFiles%\Auslogics\BoostSpeed|GASender.exe;GoogleAnalyticsHelper.dll`
`RegKey32=HKLM\SOFTWARE\Auslogics\Google Analytics Package`

Note: Google Analytics is used for telemetry purpose. The program will function just fine without these files.

`[Auslogics Disk Defrag *]`
...
`FileKey3=%ProgramFiles%\Auslogics\Disk*Defrag*|GASender.exe;GoogleAnalyticsHelper.dll`
`RegKey1=HKLM\SOFTWARE\Auslogics\Google Analytics Package`

`[Auslogics Driver Updater *]`
`LangSecRef=3024`
`DetectFile=%ProgramFiles%\Auslogics\Driver Updater`
`FileKey1=%ProgramFiles%\Auslogics\Driver Updater|GASender.exe;GoogleAnalyticsHelper.dll`
`RegKey1=HKLM\SOFTWARE\Auslogics\Google Analytics Package`

`[Auslogics Duplicate File Finder *]`
...
`DetectFile=%ProgramFiles%\Auslogics\Duplicate File Finder`
`FileKey1=%ProgramFiles%\Auslogics\Duplicate File Finder|GASender.exe;GoogleAnalyticsHelper.dll`
`RegKey2=HKLM\SOFTWARE\Auslogics\Google Analytics Package`

`[Autodesk AutoCAD *]`
...
`FileKey1=%LocalAppData%\Autodesk\Autocad*|*.log|RECURSE`
`FileKey2=%LocalAppData%\Autodesk\Autocad*\r*\*\BrowserCache|data_*;index`
...
`FileKey5=%AppData%\Autodesk\Autocad*\r*\*\Recent|*.lnk|RECURSE`

`[AV Stumpfl Wings Platinum *]`
`LangSecRef=3023`
`DetectFile=%ProgramFiles%\AV Stumpfl\Wings Platinum`
`FileKey1=%ProgramFiles%\AV Stumpfl\Wings Platinum|*Log.txt`

`[Avast *]`
...
`FileKey11=%AppData%\AVAST Software\Avast\log|*.*`

`[AVG *]`
...
`FileKey19=%AppData%\AVG\Antivirus\cache|ChromeDWriteFontCache`
`FileKey20=%ProgramFiles%\AVG\Antivirus|*.tmp|RECURSE`

`[AVG PC TuneUp *]`
`....`
`DetectFile=%AppData%\AVG TuneUp`
`FileKey4=%CommonAppData%\TuneUp Software\TuneUp Utilities*|*.log|RECURSE`
...
`FileKey28=%AppData%\AVG\AVG TuneUp\Cache|ChromeDWriteFontCache;data_*;f_*;index`
`FileKey29=%AppData%\AVG\AVG TuneUp\log|*.*`
`FileKey30=%AppData%\AVG\TuneUp\log|*.*`
`FileKey31=%AppData%\AVG TuneUp\Cache|*.*|RECURSE`
`FileKey32=%AppData%\AVG TuneUp\log|*.*`
`FileKey33=%CommonAppData%\AVG\AVG TuneUp\Backups|*.rcb`
`FileKey34=%CommonAppData%\AVG\AVG TuneUp\Cache|*.log`
`FileKey35=%CommonAppData%\AVG\AVG TuneUp\log|*.*`
`FileKey36=%CommonAppData%\AVG\AWL*|TUReportData.10.tudb`
`FileKey37=%CommonAppData%\AVG\Icarus\Logs|*.log`
`FileKey38=%CommonAppData%\AVG\TuneUp|*.bak;*.old`
`FileKey39=%CommonAppData%\AVG\TuneUp\log|*.*|RECURSE`
`FileKey40=%CommonAppData%\TuneUp Software\tu*|TUReportData.10.tudb`
`FileKey41=%ProgramFiles%\AVG\AVG TuneUp\DATA\log|*.*`
`FileKey42=%ProgramFiles%\AVG\AVG TuneUp\x*\DATA\log|*.*`
`FileKey43=%ProgramFiles%\AVG\TuneUp\DATA\log|*.*`
`FileKey44=%ProgramFiles%\AVG\TuneUp\DATA\report|*.*`

`[Avid *]`
`LangSecRef=3023`
`DetectFile1=%AppData%\Digidesign`
`DetectFile2=%LocalAppData%\Avid`
`FileKey1=%AppData%\Digidesign\Recent Files|*.*|RECURSE`
`FileKey2=%AppData%\Digidesign\Recent Folders|*.*|RECURSE`
`FileKey3=%LocalAppData%\Avid\Crashlog|*.*`
`FileKey4=%LocalAppData%\Avid\Logs|*_log.txt;*.dlog`
`FileKey5=%LocalAppData%\Avid\Pro Tools\Cache|*.*|RECURSE`

`[Avira AntiVir Desktop *]`
...
`FileKey4=%CommonAppData%\Avira\Antivirus\LOGFILES|*.log|RECURSE`
`FileKey5=%CommonAppData%\Avira\Antivirus\EVENTDB\Logs|*.*`
`FileKey6=%CommonAppData%\Avira\OptimizerHost\Logs|*.*`

`[Avira Launcher *]`
`LangSecRef=3021`
`DetectFile=%ProgramFiles%\Avira\Launcher\Avira.*.exe`
`FileKey1=%CommonAppData%\Avira\Launcher|*.backup`
`FileKey2=%CommonAppData%\Avira\Launcher\Logfiles*|*.*`
`FileKey3=%CommonAppData%\Avira\Launcher\Temp|*.*|RECURSE`
`FileKey4=%ProgramFiles%\Avira\Launcher|*.backup`

`[Avira Privacy Pal *]`
`LangSecRef=3024`
`DetectFile=%CommonAppData%\Avira\PrivacyPal`
`FileKey1=%CommonAppData%\Avira\PrivacyPal\Logs|*.*`

`[Avira System Speedup *]`
`LangSecRef=3024`
`DetectFile=%CommonAppData%\Avira\SystemSpeedup`
`FileKey1=%CommonAppData%\Avira\SystemSpeedup\Logs|*.*`
`FileKey1=%CommonAppData%\Avira\SystemSpeedup\Update|*.exe`

`[Axigen Mail Server *]`
`LangSecRef=3022`
`DetectFile=%ProgramFiles%\Axigen Mail Server`
`FileKey1=%ProgramFiles%\Axigen Mail Server\log|LOG_FILE.txt`

**Comment by APMichael** [comment]
> Note: Please rearrange the order of the lines. ...

The alphabetical sorting of the Keys is done by Winapp2ool. Therefore another sorting is not possible.

---

> Note: I understand that you try to keep the file as small as possible. ...
>  ... because I found that if an application is uninstalled ...

That's the wrong way to look at it. If a program has been uninstalled, then CCleaner should also no longer show the entry for the program. This is desired by the users, because there were already many requests in the official forum, why CCleaner still shows an uninstalled program. A big disadvantage of your approach would be that CCleaner would then show a lot of entries of uninstalled programs, although there is only an empty user data folder.

Removing the leftovers after an uninstall is not and never has been CCleaner's job. This is everyone's responsibility - either manually or with the help of an uninstall tool.

Therefore, for most entries, a single detection should be sufficient, which reliably detects an installed program.

---

`[Avira AntiVir Desktop *]`
`FileKey4=%CommonAppData%\Avira\Antivirus\LOGFILES|*.log|RECURSE`
Already covered by CCleaner's built-in entry:
`FileKey14=%CommonAppData%\Avira\Antivirus\LOGFILES|*.*`

`[Avira System Speedup *]`
`FileKey1=%CommonAppData%\Avira\SystemSpeedup\Logs|*.*`
Already covered by CCleaner's built-in entry:
`FileKey5=%CommonAppData%\Avira\SystemSpeedup\Logs|*.*`

**Comment by aquila-XP** [comment]
Thank you for the explanations, APMichael.
Somehow I overlooked those lines that already exist in CCleaner.
