### ISSUE TITLE
New and modified entries for winapp2.ini (B letter)

### ISSUE THREAD

**Issue by aquila-XP** [MoscaDotTo/Winapp2#777]
`[Babylon *]`
...
`Detect=HKCU\Software\Babylon\Babylon Translator`
`FileKey1=%AppData%\Babylon|log_file.txt`

`[Background_Fault *]`
`LangSecRef=3022`
`DetectFile=%LocalAppData%\Background_Fault\QQIme*.exe`
`FileKey1=%LocalAppData%\Background_Fault|debug.log`

`[Backups *]`
`LangSecRef=3026`
`DetectFile=%AppData%\Mozilla\Firefox`
`FileKey1=%AppData%\Mozilla\Firefox\Profiles\*|*-backup.json|RECURSE`
`FileKey2=%AppData%\Mozilla\Firefox\Profiles\*\sessions|backup-*.session`

`[Battle.net *]`
...
`DetectFile=%ProgramFiles%\Blizzard App\Battle.net*.exe`
`FileKey11=%LocalAppData%\Blizzard Entertainment\Telemetry|*.*`
`FileKey12=%ProgramFiles%\Blizzard App\Logs|*.log`

`[BDtoAVCHD *]`
`LangSecRef=3023`
`DetectFile=%ProgramFiles%\BDtoAVCHD`
`FileKey1=%ProgramFiles%\BDtoAVCHD\ac3to|log.txt`

`[BelarcAdvisor *]`
`LangSecRef=3024`
`DetectFile=%ProgramFiles%\Belarc\BelarcAdvisor\BelarcAdvisor.exe`
`FileKey1=%ProgramFiles%\Belarc\BelarcAdvisor|*.bci`
`FileKey2=%ProgramFiles%\Belarc\BelarcAdvisor\System\tmp|*.html`

`[Beyondo *]`
`LangSecRef=3024`
`Detect=HKCU\Software\Bluefive\Beyondo`
`RegKey1=HKCU\Software\Bluefive\Beyondo\RecentFiles`

`[Binding of Isaac Rebirth *]`
`Section=Games`
`DetectFile=%Documents%\My Games\Binding of Isaac Rebirth`
`FileKey1=%Documents%\My Games\Binding of Isaac Rebirth|log.txt`

`[BK ReplaceEm *]`
`LangSecRef=3024`
`Detect=HKLM\Software\BK\BK ReplaceEm`
`RegKey1=HKLM\Software\BK\BK ReplaceEm|destPath`
`RegKey2=HKLM\Software\BK\BK ReplaceEm|sourceExcludeFilter`
`RegKey3=HKLM\Software\BK\BK ReplaceEm|sourcePath`

`[BlueSprig JetClean *]`
...
`FileKey3=%ProgramFiles%\BlueSprig\JetClean|*_Log.txt`

`[BlueStacks *]`
`LangSecRef=3021`
`Detect1=HKCU\Software\BlueStacks`
`Detect2=HKLM\Software\BlueStacks`
`FileKey1=%CommonAppData%\BlueStacks\CefData\Cache|*.*|RECURSE`
`FileKey2=%CommonAppData%\BlueStacks\Engine\Android\Logs|*.log*`
`FileKey3=%CommonAppData%\BlueStacks\Logs|*.log|RECURSE`
`FileKey4=%LocalAppData%\BlueStacks|*.log`
`FileKey5=%LocalAppData%\BlueStacksSetup|BlueStacksInstaller*.exe`
`FileKey6=%Pictures%\BlueStacks|*_Screenshot_*.jpg`

`[Boilsoft Video Utilities *]`
`LangSecRef=3023`
`DetectFile=%AppData%\Boilsoft\Boilsoft Video*`
`FileKey1=%AppData%\Boilsoft\Boilsoft Video Converter|*.log`
`FileKey2=%AppData%\Boilsoft\Boilsoft Video Joiner|*.log`
`FileKey3=%AppData%\Boilsoft\Boilsoft Video Splitter|*.log`

`[Bricks of Egypt *]`
`Section=Games`
`DetectFile=%CommonAppData%\Arcade Lab`
`FileKey1=%CommonAppData%\Arcade Lab|log.txt`

`[ByteFence Anti-Malware *]`
`LangSecRef=3024`
`Detect=HKCU\Software\ByteFence\RTOP`
`FileKey1=%CommonAppData%\ByteFence\RTOP|uclogfile.bin`
`FileKey2=%ProgramFiles%\ByteFence\Logs|*.*`

**Comment by aquila-XP** [comment]
Hi APMichael.
Why didn't include also `[Backups *]` in Winapp2.ini?

**Comment by APMichael** [comment]
Especially FileKey2 seems to be very outdated. The entries for browsers are always adapted for the relatively current versions. I myself have been using Firefox for decades and have never seen these files. Also, no one in the community has ever reported these files.

**Comment by aquila-XP** [comment]
`*-backup.json` will clear `logins-backup.json`. Usually there is no problem if this file is cleared.

`FileKey2=%AppData%\Mozilla\Firefox\Profiles\*\sessions|backup*.session` will clear backup files from older versions of Firefox and also forks of Browsers based on Firefox like Waterfox, GNU IceCat, K-Meleon.
