### ISSUE TITLE
New and modified entries for winapp2.ini (N & O letters)

### ISSUE THREAD

**Issue by aquila-XP** [MoscaDotTo/Winapp2#790]
`[NesterJ *]`
`LangSecRef=3024`
`Detect=HKCU\Software\nesterJ`
`RegKey1=HKCU\Software\nesterJ\Recent`

`[Native Instruments Software *]`
`LangSecRef=3023`
`DetectFile1=%Documents%\Native Instruments`
`DetectFile2=%LocalAppData%\Native Instruments`
`FileKey1=%Documents%\Native Instruments\Guitar Rig*\CrashLogs|*.*`
`FileKey2=%Documents%\Native Instruments\Kontakt\CrashLogs|*.*`
`FileKey3=%Documents%\Native Instruments\Reaktor*\CrashLogs|*.*`
`FileKey4=%Documents%\Native Instruments\Service Center\Crashlogs|*.*`
`FileKey5=%Documents%\Native Instruments\Traktor*|*.log`
`FileKey6=%Documents%\Native Instruments\Traktor*\CrashLogs|*.*`
`FileKey7=%Documents%\Native Instruments\Traktor*\History|*.*`
`FileKey8=%Documents%\Native Instruments\Traktor*\Logs|*.*`
`FileKey9=%LocalAppData%\Cache\Native Instruments\Native Access|*.log`
`FileKey10=%LocalAppData%\Cache\Native Instruments\Native Access\Cache|*.*|RECURSE`
`FileKey11=%LocalAppData%\Native Instruments\Guitar Rig*\Temp|*.*`
`FileKey12=%LocalAppData%\Native Instruments\Kontakt*\Kconvert Logs|*.*`
`FileKey13=%LocalAppData%\Native Instruments\Kontakt*\Kconvert Temp|*.*`
`FileKey14=%LocalAppData%\Native Instruments\Kontakt*\LibrariesCache|*.cache`
`FileKey15=%LocalAppData%\Native Instruments\Native Access*\Cache|*.*|RECURSE`
`FileKey16=%LocalAppData%\Native Instruments\Reaktor*\Cache|*.*`

`[Nero TuneItUp *]`
`LangSecRef=3024`
`DetectFile=%CommonAppData%\Nero\Nero TuneItUp`
`FileKey1=%CommonAppData%\Nero\Nero TuneItUp\DriverUpdate|*.log`
`FileKey2=%CommonAppData%\Nero\Nero TuneItUp\ExceptionHandlerDll|*.dmp;*.exlog;*.log`
`FileKey3=%CommonAppData%\Nero\Nero TuneItUp\RegCleanerDll\Log|*.log`
`FileKey4=%CommonAppData%\Nero\Nero TuneItUp\RegDefragDll\Log|*.log`
`FileKey5=%CommonAppData%\Nero\Nero TuneItUp\Reports|*.html|RECURSE`
`FileKey6=%CommonAppData%\Nero\Nero TuneItUp\Services|*.log`
`FileKey7=%CommonAppData%\Nero\Nero TuneItUp\SoftwareProducts|*.log`
`FileKey8=%CommonAppData%\Nero\Nero TuneItUp\Startup|*.log`
`FileKey9=%CommonAppData%\Nero\Nero TuneItUp\TemperatureMonitoringModule|*.log`

`[Net-Peeker *]`
`LangSecRef=3024`
`Detect=HKLM\Software\eMingSoftware\NetPeeker`
`FileKey1=%CommonAppData%\eMingSoftware\NetPeeker\Log|*.*`
`RegKey1=HKCU\Software\eMingSoftware\Net-Peeker Group Console\Recent File List`
`RegKey2=HKLM\Software\eMingSoftware\NetPeeker|ConsoleName`

`[NetAnts *]`
...
`FileKey1=%ProgramFiles%\NetAnts|*.job;history.txt;netantslog.htm`
`RegKey1=HKCU\Software\Netants\MRU`

`[NetSurf Browser *]`
`LangSecRef=3022`
`DetectFile=%AppData%\NetSurf`
`FileKey1=%AppData%\NetSurf|Cookies;URLs`

`[NetUtils WNetStat *]`
`LangSecRef=3024`
`Detect=HKCU\Software\NetUtils\WNetStat`
`RegKey1=HKCU\Software\NetUtils\WNetStat|LastFile`

`[NetworkActiv AUTAPF *]`
`LangSecRef=3024`
`DetectFile=%ProgramFiles%\NetworkActiv AUTAPF*`
`FileKey1=%ProgramFiles%\NetworkActiv AUTAPF*|*log.txt`

`[Nitro PDF Reader *]`
`LangSecRef=3021`
`DetectFile=%AppData%\Nitro\Reader`
`FileKey1=%AppData%\Nitro\Reader\*|*Log.txt;NitroPDFHistory.dat`

`[NoBot *]`
`LangSecRef=3024`
`Detect=HKLM\Software\NoBot`
`DetectFile=%SystemDrive%\NoBot`
`FileKey1=%SystemDrive%\NoBot\Logs|*.*`
`FileKey2=%SystemDrive%\NoBot\Quarantine|*.*`

`[Noise Engineering *]`
`LangSecRef=3023`
`DetectFile=%UserProfile%\Noise Engineering\NE products`
`FileKey1=%UserProfile%\Noise Engineering\NE products|*.log`

`[Nokia Suite *]`
`LangSecRef=3021`
`DetectFile=%AppData%\Nokia Suite`
`FileKey1=%AppData%\Nokia\intellisync\*\configuration|*.log`
`FileKey2=%AppData%\Nokia Suite\Nokia Connector|*.log`

`[Norman Malware Cleaner *]`
`LangSecRef=3024`
`DetectFile=%UserProfile%\Desktop\NFix_*.log`
`FileKey1=%UserProfile%\Desktop|NFix_*.log`

`[Norton Secure VPN  *]`
`LangSecRef=3022`
`DetectFile=%LocalAppData%\Norton Secure VPN`
`FileKey1=%LocalAppData%\Norton Secure VPN|*.log`
`FileKey2=%LocalAppData%\Norton Secure VPN\Cache\qmlcache|*.qmlc`

`[Norton Utilities *]`
...
`DetectFile2=%ProgramFilesDir%\Norton SystemWorks Premier Edition\Norton Utilities`
`FileKey4=%ProgramFilesDir%\Norton SystemWorks Premier Edition\Norton Utilities|*.log;*.tmp`

`[Notion *]`
`LangSecRef=3021`
`DetectFile=%AppData%\Notion`
`FileKey1=%AppData%\Notion|*.log`
`FileKey2=%AppData%\Notion\Cache|*.*`
`FileKey3=%AppData%\Notion\Code Cache|*.*|RECURSE`
`FileKey4=%AppData%\Notion\partitions|*.old;LOG|RECURSE`
`FileKey5=%AppData%\Notion\partitions\*Cache|*.*|RECURSE`

`[NVIDIA *]`
...
`FileKey13=%LocalAppData%\NVIDIA Corporation\*\CefCache|Cookies*;QuotaManager*;Visited Links`

`[Ontrack EasyRecovery *]`
...
`FileKey2=%ProgramFiles%\Kroll Ontrack\Ontrack EasyRecovery*\licman|*_log.txt;*.tmp`

`[Ookla Speed Test *]`
...
`DetectFile=%LocalLowAppData%\Ookla\Speedtest`
`FileKey7=%LocalLowAppData%\Ookla\Speedtest|*log.txt`

`[OpenCandy *]`
`LangSecRef=3021`
`DetectFile1=%AppData%\OpenCandy`
`DetectFile2=%AppData%\RHEng`
`DetectFile3=%AppData%\RPEng`
`FileKey1=%AppData%\OpenCandy|*.*|REMOVESELF`
`FileKey2=%AppData%\RHEng|*.*|REMOVESELF`
`FileKey3=%AppData%\RPEng|*.*|REMOVESELF`

Note: OpenCandy is adware and it should be removed.

`[OpenShot *]`
`LangSecRef=3023`
`DetectFile=%UserProfile%\.openshot_qt`
`FileKey1=%UserProfile%\.openshot_qt|*.log`
`FileKey2=%UserProfile%\.openshot_qt\*cache|*.*`
`FileKey3=%UserProfile%\.openshot_qt\thumbnail|*.png`

`[OpenShot Video Editor *]`
`LangSecRef=3023`
`DetectFile=%ProgramFiles%\OpenShot Video Editor\launch.exe`
`FileKey1=%ProgramFiles%\OpenShot Video Editor\settings|*.log`

`[Opera Logs *]`
...
`FileKey2=%LocalAppData%\Programs\Opera*|*.log|RECURSE`
`FileKey4=%LocalAppData%\Opera\Opera*|*.log`
`FileKey5=%ProgramFiles%\Opera\assistant|*.log`
`FileKey6=%UserProfile%\Downloads\Opera Autoupdate|*.log`
`FileKey7=%UserProfile%\Opera Autoupdate|*.log`

`[Opera Update *]`
...
`FileKey1=%LocalAppData%\Programs\Opera*|*.backup;*.old|RECURSE`
`FileKey2=%UserProfile%\.opera|*.*|REMOVESELF`
`FileKey3=%UserProfile%\Downloads\.opera|*.*|REMOVESELF`

`[Origin *]`
...
`DetectFile=%AppData%\Origin`
`FileKey1=%AppData%\Origin\Logs|*.*`
`FileKey3=%CommonAppData%\Origin\*Logs|*.*`
...
`FileKey10=%AppData%\Origin\*Cache|*.*`
`FileKey11=%AppData%\Origin\Telemetry|*.*`
`FileKey12=%ProgramFiles%\Origin|*.log`

`[Origin Installers *]`
...
`FileKey3=%ProgramFiles%\Origin|vc*redist*.exe`

`[OSO Update *]`
`LangSecRef=3022`
`DetectFile=%UserProfile%\CC-Logs`
`FileKey1=%UserProfile%\CC-Logs\osoupd|*.log`

`[Other Explorer MRUs *]`
`LangSecRef=3025`
`Detect=HKCU\Software\Microsoft\Windows\CurrentVersion\Applets`
`RegKey1=HKU\.DEFAULT\Software\Microsoft\Windows\CurrentVersion\Applets\Regedit|LastKey`
`RegKey2=HKU\S-1-5-18\Software\Microsoft\Windows\CurrentVersion\Applets\Regedit|LastKey`

`[Outward *]`
`Section=Games`
`DetectFile=%LocalLowAppData%\Nine Dots Studio\Outward`
`FileKey1=%LocalLowAppData%\Nine Dots Studio\Outward|*log.txt`

**Comment by APMichael** [comment]
`[Opera Logs *] + [Opera Update *]`
Please note that the separate Opera entries are only for Chromium-based Opera. Please add FileKeys for previous versions to the `[Opera *]` entry. Thank you.

`[Other Explorer MRUs *]`
I renamed the entry to `[RegEdit *]`, as in CCleaner's built in winapp.ini. I guess they forgot to remove the FileKey from the `[Other Explorer MRUs *]` entry (winsys.ini).
