### ISSUE TITLE
New and modified entries for winapp2.ini (P letter)

### ISSUE THREAD

**Issue by aquila-XP** [MoscaDotTo/Winapp2#793]
`[Paint Shop Pro Cache *]`
`LangSecRef=3023`
`DetectFile=%ProgramFiles%\Jasc Software Inc\Paint Shop Pro*\Cache`
`FileKey1=%ProgramFiles%\Jasc Software Inc\Paint Shop Pro*\Cache|*.*`

`[PaintTool SAI *]`
`LangSecRef=3023`
`DetectFile=%AppData%\SYSTEMAX Software Development\SAI*`
`FileKey1=%AppData%\SYSTEMAX Software Development\SAI*|recent.txt`
`FileKey2=%Documents%\SYSTEMAX Software Development\SAI*\error|*.txt`

`[Paragon Migrate OS to SSD *]`
`LangSecRef=3024`
`DetectFile=%ProgramFiles%\Paragon Software\Migrate OS to SSD*`
`FileKey1=%ProgramFiles%\Paragon Software\Migrate OS to SSD*\program|*.log;*.txt`

`[Parallel Password Recovery *]`
`LangSecRef=3024`
`Detect=HKCU\Software\Parallel Password Recovery`
`FileKey1=%ProgramFiles%\Parallel Password Recovery|*.log`
`RegKey1=HKCU\Software\Parallel Password Recovery\Parallel recovery server\1.0|Last stored job`
`RegKey2=HKCU\Software\Parallel Password Recovery\PPR GUI manager\1.0|Last password definition file path`
`RegKey3=HKCU\Software\Parallel Password Recovery\PPR GUI manager\1.0|Last test path`
`RegKey4=HKCU\Software\Parallel Password Recovery\PPR GUI manager\1.0|Path to password definition file`
`RegKey5=HKCU\Software\Parallel Password Recovery\PPR GUI manager\1.0|Path to test file`
`RegKey6=HKLM\Software\Parallel Password Recovery\Parallel recovery server\1.0|Last stored job`
`RegKey7=HKLM\Software\Parallel Password Recovery\PPR GUI manager\1.0|Last test path`
`RegKey8=HKLM\Software\Parallel Password Recovery\PPR GUI manager\1.0|Path to password definition file`
`RegKey9=HKLM\Software\Parallel Password Recovery\PPR GUI manager\1.0|Path to test file`
`RegKey10=HKLM\Software\Wow6432Node\Parallel Password Recovery\Parallel recovery server\1.0|Last stored job`
`RegKey11=HKLM\Software\Wow6432Node\Parallel Password Recovery\PPR GUI manager\1.0|Last password definition file path`
`RegKey12=HKLM\Software\Wow6432Node\Parallel Password Recovery\PPR GUI manager\1.0|Last test path`
`RegKey13=HKLM\Software\Wow6432Node\Parallel Password Recovery\PPR GUI manager\1.0|Path to password definition file`
`RegKey14=HKLM\Software\Wow6432Node\Parallel Password Recovery\PPR GUI manager\1.0|Path to test file`

`[PCBooster Free Browser Cleaner *]`
`LangSecRef=3024`
`DetectFile=%ProgramFiles%\PCBooster Free Browser Cleaner\PCBoosterFreeBrowserCleaner.exe`
`FileKey1=%AppData%\PCBooster Free Browser Cleaner New Version Available|*.*|REMOVESELF`
`FileKey2=%ProgramFiles%\PCBooster Free Browser Cleaner\Logs|*.*`

`[PCWinBooster *]`
`LangSecRef=3024`
`DetectFile=%AppData%\Soft4Boost\PCWinBooster*`
`FileKey1=%AppData%\Soft4Boost\Logs|*.*|RECURSE`

`[PDF Architect *]`
...
`DetectFile2=%AppData%\PDF Architect*`
`FileKey2=%AppData%\PDF Architect*\Logs|*.*`

`[PDFsam Enhanced *]`
`LangSecRef=3021`
`DetectFile=%AppData%\PDFsam Enhanced*`
`FileKey1=%AppData%\PDFsam Enhanced*\logs|*.htm`
`FileKey2=%CommonAppData%\PDFsam Enhanced*\Installation\logs|*.*`

`[PeaZip *]`
`LangSecRef=3024`
`DetectFile=%ProgramFiles%\PeaZip\peazip.exe`
`FileKey1=%ProgramFiles%\PeaZip\res|note.txt|RECURSE`

`[pgAdmin *]`
...
`FileKey1=%AppData%\pgAdmin|pgadmin*.log`

`[Photo DVD Slideshow *]`
`LangSecRef=3023`
`DetectFile=%AppData%\Photo DVD Slideshow`
`FileKey1=%AppData%\Photo DVD Slideshow|*.log`
`FileKey2=%AppData%\Photo DVD Slideshow\PhotosCache|*.*`

`[PhotoFlare *]`
`LangSecRef=3023`
`Detect=HKCU\Software\photoflare.io\PhotoFlare`
`RegKey1=HKCU\Software\photoflare.io\PhotoFlare|OpenFolder`
`RegKey2=HKCU\Software\photoflare.io\PhotoFlare|RecentFiles`
`RegKey3=HKCU\Software\photoflare.io\PhotoFlare|SaveFolder`
`RegKey4=HKCU\Software\photoflare.io\PhotoFlare|SaveFormat`

`[PictureMover *]`
`LangSecRef=3023`
`DetectFile=%AppData%\PictureMover`
`FileKey1=%AppData%\PictureMover\log|*.*`

`[Pioneer Rekordbox *]`
`LangSecRef=3023`
`DetectFile=%AppData%\Pioneer\Rekordbox`
`FileKey1=%AppData%\Pioneer\Rekordbox\Crashes|*.dmp`
`FileKey2=%AppData%\PioneerLog|*Log.txt`
`FileKey3=%Documents%\Rekordbox|*log*.txt`

`[Plex Media Server *]`
`....`
`FileKey8=%LocalAppData%\Plex\Cache\qmlcache|*.jsc;*.qmlc`
`FileKey9=%LocalAppData%\Plex\Cache\qtwebengine\Default\Cache|*.*`
`FileKey10=%LocalAppData%\Plex\logs|*.*`

`[PokerStars *]`
...
`FileKey3=%ProgramFiles%\PokerStars*|*.log.*`

`[Popcorn Time *]`
...
`DetectFile=%LocalAppData%\Popcorn*Time*`
`FileKey3=%LocalAppData%\Popcorn*Time*\User Data\*\*Cache|*.*`
`FileKey5=%LocalAppData%\PopcornTime\PopcornTime\Cache\QTWebEngine\Default\Cache|*.*`
`FileKey6=%LocalAppData%\PopcornTime\QTWebEngine\Default\GPUCache|*.*`

`[PortForward.com PortChecker *]`
`LangSecRef=3024`
`Detect=HKCU\Software\VB and VBA Program Settings\PFPortChecker`
`RegKey1=HKCU\Software\VB and VBA Program Settings\PFPortChecker\Settings|Port`

`[Postman *]`
...
`FileKey4=%AppData%\Postman\partitions\postman_shell\GPUCache|*.*`
`FileKey5=%AppData%\Postman\partitions\postman_shell\webrtc_event_logs|*.*`
`FileKey6=%AppData%\Postman\partitions\postman_user_cookies\webrtc_event_logs|*.*`
`FileKey7=%AppData%\Postman\webrtc_event_logs|*.*`

`[PowerISO *]`
...
`FileKey1=%AppData%\PowerISO\Upgrade|*.*|REMOVESELF`
`FileKey2=%ProgramFiles%\PowerISO|*.tmp`
`RegKey1=HKCU\Software\PowerISO\SCDEmu|ImageName0`
`RegKey2=HKCU\Software\PowerISO\SCDEmu|ImageName1`
`RegKey3=HKCU\Software\PowerISO\SCDEmu|ImageName2`
`RegKey4=HKCU\Software\PowerISO\SCDEmu|ImageName3`
`RegKey5=HKCU\Software\PowerISO\SCDEmu|ImageName4`
`RegKey6=HKCU\Software\PowerISO\SCDEmu|ImageName5`
`RegKey7=HKCU\Software\PowerISO\SCDEmu|ImageName6`
`RegKey8=HKCU\Software\PowerISO\SCDEmu|ImageName7`
`RegKey9=HKCU\Software\PowerISO\SCDEmu|ImageName8`
`RegKey10=HKCU\Software\PowerISO\SCDEmu|ImageName9`
`RegKey11=HKCU\Software\PowerISO\SCDEmu|ImageName10`
`RegKey12=HKCU\Software\PowerISO\SCDEmu|ImageName11`
`RegKey13=HKCU\Software\PowerISO\SCDEmu|ImageName12`
`RegKey14=HKCU\Software\PowerISO\SCDEmu|ImageName13`
`RegKey15=HKCU\Software\PowerISO\SCDEmu|ImageName14`
`RegKey16=HKCU\Software\PowerISO\SCDEmu|ImageName15`
`RegKey17=HKCU\Software\PowerISO\SCDEmu|ImageName16`
`RegKey18=HKCU\Software\PowerISO\SCDEmu|ImageName17`
`RegKey19=HKCU\Software\PowerISO\SCDEmu|ImageName18`
`RegKey20=HKCU\Software\PowerISO\SCDEmu|ImageName19`
`RegKey21=HKCU\Software\PowerISO\SCDEmu|ImageName20`
`RegKey22=HKCU\Software\PowerISO\SCDEmu|ImageName21`
`RegKey23=HKCU\Software\PowerISO\SCDEmu|ImageName22`
`RegKey24=HKU\S-1-5-18\Software\PowerISO|ExtractPath0`
`RegKey25=HKU\S-1-5-18\Software\PowerISO|ExtractPath1`
`RegKey26=HKU\S-1-5-18\Software\PowerISO|ExtractPath2`
`RegKey27=HKU\S-1-5-18\Software\PowerISO|ExtractPath3`
`RegKey28=HKU\S-1-5-18\Software\PowerISO|ExtractPath4`
`RegKey29=HKU\S-1-5-18\Software\PowerISO|ExtractPath5`
`RegKey30=HKU\S-1-5-18\Software\PowerISO|ExtractPath6`
`RegKey31=HKU\S-1-5-18\Software\PowerISO|ExtractPath7`
`RegKey32=HKU\S-1-5-18\Software\PowerISO\SCDEmu|ImageName0`
`RegKey33=HKU\S-1-5-18\Software\PowerISO\SCDEmu|ImageName1`
`RegKey34=HKU\S-1-5-18\Software\PowerISO\SCDEmu|ImageName2`
`RegKey35=HKU\S-1-5-18\Software\PowerISO\SCDEmu|ImageName3`
`RegKey36=HKU\S-1-5-18\Software\PowerISO\SCDEmu|ImageName4`
`RegKey37=HKU\S-1-5-18\Software\PowerISO\SCDEmu|ImageName5`
`RegKey38=HKU\S-1-5-18\Software\PowerISO\SCDEmu|ImageName6`
`RegKey39=HKU\S-1-5-18\Software\PowerISO\SCDEmu|ImageName7`
`RegKey40=HKU\S-1-5-18\Software\PowerISO\SCDEmu|ImageName8`
`RegKey41=HKU\S-1-5-18\Software\PowerISO\SCDEmu|ImageName9`
`RegKey42=HKU\S-1-5-18\Software\PowerISO\SCDEmu|ImageName10`
`RegKey43=HKU\S-1-5-18\Software\PowerISO\SCDEmu|ImageName11`
`RegKey44=HKU\S-1-5-18\Software\PowerISO\SCDEmu|ImageName12`
`RegKey45=HKU\S-1-5-18\Software\PowerISO\SCDEmu|ImageName13`
`RegKey46=HKU\S-1-5-18\Software\PowerISO\SCDEmu|ImageName14`
`RegKey47=HKU\S-1-5-18\Software\PowerISO\SCDEmu|ImageName15`
`RegKey48=HKU\S-1-5-18\Software\PowerISO\SCDEmu|ImageName16`
`RegKey49=HKU\S-1-5-18\Software\PowerISO\SCDEmu|ImageName17`
`RegKey50=HKU\S-1-5-18\Software\PowerISO\SCDEmu|ImageName18`
`RegKey51=HKU\S-1-5-18\Software\PowerISO\SCDEmu|ImageName19`
`RegKey52=HKU\S-1-5-18\Software\PowerISO\SCDEmu|ImageName20`
`RegKey53=HKU\S-1-5-18\Software\PowerISO\SCDEmu|ImageName21`
`RegKey54=HKU\S-1-5-18\Software\PowerISO\SCDEmu|ImageName22`
`RegKey55=HKU\S-1-5-18\Software\PowerISO|Reopen0`
`RegKey56=HKU\S-1-5-18\Software\PowerISO|Reopen1`
`RegKey57=HKU\S-1-5-18\Software\PowerISO|Reopen2`
`RegKey58=HKU\S-1-5-18\Software\PowerISO|Reopen3`

`[Presentation Foundation *]`
...
`FileKey1=%SystemDrive%\Documents and Settings\LocalService\Local Settings\Application Data|*FontCache*.dat`
`FileKey2=%WinDir%\ServiceProfiles\LocalService\AppData\Local|*FontCache*.dat`

`[Prevent Restore *]`
`LangSecRef=3024`
`DetectFile=%AppData%\Prevent Restore`
`FileKey1=%AppData%\Prevent Restore|rreport.txt`

`[PriceGong *]`
...
`FileKey2=%LocalLowAppData%\PriceGong\data|*.txt`

`[priPrinter *]`
`LangSecRef=3021`
`Detect=HKLM\Software\Pelikan Software KFT\priPrinter`
`FileKey1=%AppData%\Pelikan Software KFT\priPrinter|cache_*.dat`
`FileKey2=%CommonAppData%\priPrinter\dumps|*.*`
`RegKey1=HKCU\Software\Pelikan Software KFT\priPrinter|lastCleanUp`

`[privacy.sexy *]`
...
`DetectFile=%AppData%\privacy.sexy`
`FileKey2=%AppData%\privacy.sexy\*Storage|*.old;LOG|RECURSE`
`FileKey6=%AppData%\privacy.sexy|Network Persistent State`
`FileKey7=%AppData%\privacy.sexy\blob_storage|*.*|RECURSE`

`[Pro PC Cleaner *]`
`LangSecRef=3024`
`DetectFile=%Documents%\ProPCCleaner`
`FileKey1=%Documents%\ProPCCleaner|log.txt;logerror.txt`

`[PUBG Lite *]`
`Section=Games`
`DetectFile=%ProgramFiles%\PUBGLite\Launcher.exe`
`FileKey1=%ProgramFiles%\PUBGLite|*.log`

`[PuTTY *]`
`LangSecRef=3022`
`DetectFile=%LocalAppData%\NETworkManager\PuTTY*`
`FileKey1=%LocalAppData%\NETworkManager\PuTTY_Log|*.log`

`[PySol Fan Club edition *]`
`Section=Games`
`DetectFile=%AppData%\PySolFC`
`FileKey1=%AppData%\PySolFC|comments.dat;statistics.dat`
`FileKey2=%ProgramFiles%\PySol Fan Club Edition|*.log`

**Comment by APMichael** [comment]
`[Paint Shop Pro Cache *]`
`DetectFile=%ProgramFiles%\Jasc Software Inc\Paint Shop Pro*\Cache`
A wildcard is not allowed here. (Only in the last part of the path.)

`[PictureMover *]`
Entry already exists as `[Snapfish Picture Mover *]`.
