### ISSUE TITLE
New and modified entries for winapp2.ini (Q & R letters)

### ISSUE THREAD

**Issue by aquila-XP** [MoscaDotTo/Winapp2#795]
`[QIP Infium *]`
`LangSecRef=3022`
`DetectFile=%ProgramFiles%\QIP Infium\qip.exe`
`FileKey1=%ProgramFiles%\QIP Infium\Profiles\*\Logs|*.*`

`[Qmmp *]`
`LangSecRef=3023`
`DetectFile=%UserProfile%\.qmmp`
`FileKey1=%UserProfile%\.qmmp\cache|*.*|RECURSE`

`[Qt Framework *]`
...
`RegKey3=HKCU\Software\QtProject\OrganizationDefaults\FileDialog|history`
`RegKey4=HKCU\Software\Trolltech\OrganizationDefaults\Qt Factory Cache 4.5`
`RegKey5=HKCU\Software\Trolltech\OrganizationDefaults\Qt Plugin Cache 4.5.false`

`[QtWeb Internet Browser *]`
`LangSecRef=3022`
`DetectFile=%LocalAppData%\QtWeb.NET\QtWeb Internet Browser`
`FileKey1=%LocalAppData%\QtWeb.NET\QtWeb Internet Browser|cookies;history;Icons;WebpageIcons.db`

`[RadioBOSS *]`
`LangSecRef=3022`
`DetectFile=%AppData%\djsoft.net\RadioBOSS*`
`FileKey1=%AppData%\djsoft.net\RadioBOSS*|~tmp;*.bak;*log.txt;nowplaying.txt`
`FileKey2=%AppData%\djsoft.net\RadioBOSS*\log|*log.txt`
`FileKey3=%AppData%\djsoft.net\RadioBOSS*\profile|*.bak`
`FileKey4=%AppData%\djsoft.net\RadioBOSS*\report|*.csv`
`FileKey5=%AppData%\djsoft.net\RadioBOSS*\temp|*.*`

`[RaidCall *]`
`LangSecRef=3022`
`DetectFile=%ProgramFiles%\RaidCall\raidcall.exe`
`FileKey1=%ProgramFiles%\RaidCall|*.log`

`[Realore Whiterra Roads of Rome NG *]`
`Section=Games`
`DetectFile=%AppData%\Realore Whiterra Roads of Rome NG`
`FileKey1=%AppData%\Realore Whiterra Roads of Rome NG|log.txt`

`[RealPlayer *]`
...
`FileKey16=%AppData%\Real\RPDS\Cache|*.*|RECURSE`
`FileKey17=%LocalAppData%\Real\RealPlayer\Content\images|*.jpg`
`FileKey18=%WinDir%|cdplayer.ini`

`[Recent Files Scanner *]`
`LangSecRef=3024`
`Detect=HKCU\Software\Groupwyse Software\Recent Files Scanner`
`RegKey1=HKCU\Software\Groupwyse Software\Recent Files Scanner\Paths`

`[Recovery Toolbox for Word *]`
...
`DetectFile=%LocalAppData%\Recovery Toolbox for Word`
`FileKey1=%LocalAppData%\Recovery Toolbox for Word|*.log`

`[RegHunter *]`
`LangSecRef=3024`
`DetectFile=%ProgramFiles%\Enigma Software Group\RegHunter\RegHunter.exe`
`FileKey1=%ProgramFiles%\Enigma Software Group\RegHunter\Log|*.log`

`[Registry Corrector *]`
`LangSecRef=3024`
`DetectFile=%AppData%\RegCorrector`
`FileKey1=%AppData%\RegCorrector|RegCorrector_Undo_*.reg`

`[Registry Finder *]`
`LangSecRef=3024`
`DetectFile=%AppData%\RegistryFinder`
`FileKey1=%AppData%\RegistryFinder|RegCountCache.json`
`FileKey2=%AppData%\RegistryFinder\UndoHistory|*.*`
`FileKey3=%AppData%\RegistryFinder\UnsentCrashReports\Logs|*.*`
`FileKey4=%ProgramFiles%\Registry Finder|RegistryFinder.log`

`[Rename Expert *]`
`LangSecRef=3024`
`DetectFile=%AppData%\Rename Expert`
`FileKey1=%AppData%\Rename Expert\*\Logs|*.*`
`FileKey2=%AppData%\Rename Expert\*\Restore|*.xml`

`[Respondus *]`
`LangSecRef=3021`
`DetectFile=%LocalAppData%\Respondus`
`FileKey1=%LocalAppData%\Respondus\Cache|LOG;LOG.old|RECURSE`
`FileKey2=%LocalAppData%\Respondus\Cache|Network Persistent State;Visited Links`
`FileKey3=%LocalAppData%\Respondus\Cache\*Cache|*.*|RECURSE`
`FileKey4=%LocalAppData%\Respondus\Cache\blob_storage|*.*|RECURSE`
`FileKey5=%LocalAppData%\Respondus\Pepper Data\Shockwave Flash\WritableRoot\#sharedobjects|*.*|RECURSE`

`[Revo Uninstaller Backups *]`
...
`DetectFile=%LocalAppData%\VS Revo Group\Revo Uninstaller*`
`FileKey3=%LocalAppData%\VS Revo Group\Revo Uninstaller*|RUPBackUpData.ini`

`[Roblox Downloads *]`
...
`DetectFile2=%CommonAppData%\Roblox`
`FileKey2=%CommonAppData%\Roblox\Downloads|*.*|RECURSE`

`[ROLI Connect *]`
`LangSecRef=3023`
`DetectFile=%AppData%\ROLI Connect`
`FileKey1=%AppData%\ROLI Connect|*-journal;log.log;Network Persistent State`
`FileKey2=%AppData%\ROLI Connect\*Cache|*.*|RECURSE`
`FileKey3=%AppData%\ROLI Connect\__update__|*Setup*.exe`
`FileKey4=%AppData%\ROLI Connect\Logs|*.*`

`[Rollback Journals *]`
...
`Detect11=HKCU\Software\ChromePlus`
`Detect12=HKCU\Software\Chromium`
`Detect13=HKCU\Software\Flock`
`Detect14=HKCU\Software\RockMelt`
`Detect15=HKCU\Software\Torch`
`Detect16=HKCU\Software\Yandex\YandexBrowser`
`DetectFile=%LocalAppData%\Google\Chrome*`
`FileKey1=%LocalAppData%\7Star\7Star\User Data|*-journal|RECURSE`
`FileKey2=%LocalAppData%\360Browser\Browser\User Data|*-journal|RECURSE`
`FileKey3=%LocalAppData%\Amigo\User Data|*-journal|RECURSE`
`FileKey4=%LocalAppData%\CentBrowser\User Data|*-journal|RECURSE`
`FileKey5=%LocalAppData%\Chromium\User Data|*-journal|RECURSE`
`FileKey6=%LocalAppData%\CocCoc\Browser\User Data|*-journal|RECURSE`
`FileKey7=%LocalAppData%\Comodo\Dragon\User Data|*-journal|RECURSE`
`FileKey8=%LocalAppData%\Coowon\Coowon\User Data|*-journal|RECURSE`
`FileKey9=%LocalAppData%\Epic Privacy Browser\User Data|*-journal|RECURSE`
`FileKey10=%LocalAppData%\Flock\User Data|*-journal|RECURSE`
`FileKey11=%LocalAppData%\Google\Chrome*\User Data|*-journal|RECURSE`
`FileKey12=%LocalAppData%\Iridium\User Data|*-journal|RECURSE`
`FileKey13=%LocalAppData%\MapleStudio\ChromePlus\User Data|*-journal|RECURSE`
`FileKey14=%LocalAppData%\RockMelt\User Data|*-journal|RECURSE`
`FileKey15=%LocalAppData%\Slimjet\User Data|*-journal|RECURSE`
`FileKey16=%LocalAppData%\Superbird\User Data|*-journal|RECURSE`
`FileKey17=%LocalAppData%\Torch\User Data|*-journal|RECURSE`
`FileKey18=%LocalAppData%\Yandex\YandexBrowser\User Data|*-journal|RECURSE`

`[Rovio Angry Birds *]`
`Section=Games`
`DetectFile=%AppData%\Rovio\Angry Birds`
`FileKey1=%AppData%\Rovio\Angry Birds\updates\update|*.exe`

**Comment by APMichael** [comment]
`[Qt Framework *]`
`RegKey4=HKCU\Software\Trolltech\OrganizationDefaults\Qt Factory Cache 4.5`
`RegKey5=HKCU\Software\Trolltech\OrganizationDefaults\Qt Plugin Cache 4.5.false`
The existing RegKey "HKCU\Software\Trolltech\OrganizationDefaults" already covers this.

`[Rollback Journals *]`
These browsers do not need to be added as they are directly supported by CCleaner. The entry is present because "CustomLocationX=" does not clean the folder parent to the profile. This is also true for the `[Shader Cache *]` entry.
