### ISSUE TITLE
New and modified entries for winapp2.ini (S & T letters)

### ISSUE THREAD

**Issue by aquila-XP** [MoscaDotTo/Winapp2#796]
`[Scrivener *]`
`LangSecRef=3021`
`DetectFile=%LocalAppData%\LiteratureandLatte\Scrivener`
`FileKey1=%LocalAppData%\LiteratureandLatte\Scrivener\Cache|*.*|RECURSE`
`FileKey2=%LocalAppData%\LiteratureandLatte\Scrivener\QtWebEngine\Default|*.old;LOG|RECURSE`
`FileKey3=%LocalAppData%\LiteratureandLatte\Scrivener\QtWebEngine\Default\GPUCache|*.*`

`[ScummVM *]`
...
`FileKey1=%AppData%\ScummVM\Logs|*.*`

`[Seagate Premium Recovery Suite *]`
`LangSecRef=3021`
`Detect=HKCU\Software\Pixel8\Premium Recovery Suite`
`FileKey1=%ProgramFiles%\Premium Recovery Suite\Logs|*.*`

`[Security Editor *]`
`LangSecRef=3025`
`Detect=HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\SecEdit`
`RegKey1=HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\SecEdit|LastUsedDatabase`

`[Security Task Manager *]`
`LangSecRef=3024`
`Detect=HKCU\Software\Neuber GbR\Security Task Manager`
`RegKey1=HKCU\Software\Neuber GbR\Security Task Manager\Options|HistoryExe`
`RegKey2=HKCU\Software\Neuber GbR\Security Task Manager\Options|HostKnown`

`[SecuROM Diagnostics Tool *]`
...
`Detect=HKCU\Software\SecuROM`
`FileKey3=%AppData%\SecuROM\UserData|*.bak`

`[Serato DJ *]`
`LangSecRef=3023`
`DetectFile=%Music%\_Serato_`
`FileKey1=%Music%\_Serato_|*.log|RECURSE`

`[ShellLess *]`
`LangSecRef=3021`
`Detect=HKCU\Software\ShellLess1.10b`
`RegKey1=HKCU\Software\ShellLess1.10b\ShellLess\Recent File List`

`[Shotcut *]`
`LangSecRef=3023`
`DetectFile=%LocalAppData%\Meltytech\Shotcut`
`FileKey1=%LocalAppData%\Meltytech\Shotcut|*-log.txt`

`[ShrewSoft VPN Client *]`
`LangSecRef=3022`
`DetectFile=%ProgramFiles%\ShrewSoft\VPN Client`
`FileKey1=%ProgramFiles%\ShrewSoft\VPN Client\debug|*.log`

`[SIP Workbench VoIP Protocol Analyzer *]`
`LangSecRef=3024`
`Detect=HKCU\Software\BreakPoint\SIP Workbench`
`RegKey1=HKCU\Software\BreakPoint\SIP Workbench|file1`
`RegKey2=HKCU\Software\BreakPoint\SIP Workbench|file2`
`RegKey3=HKCU\Software\BreakPoint\SIP Workbench|file3`
`RegKey4=HKCU\Software\BreakPoint\SIP Workbench|file4`
`RegKey5=HKCU\Software\BreakPoint\SIP Workbench|file5`
`RegKey6=HKCU\Software\BreakPoint\SIP Workbench|file6`
`RegKey7=HKCU\Software\BreakPoint\SIP Workbench|file7`
`RegKey8=HKCU\Software\BreakPoint\SIP Workbench|file8`
`RegKey9=HKCU\Software\BreakPoint\SIP Workbench|file9`

`[SketchUp Make *]`
...
`DetectFile=%AppData%\SketchUp\SketchUp*`
`FileKey1=%AppData%\SketchUp\SketchUp*\SketchUp|~*.tmp`
`FileKey2=%AppData%\SketchUp\SketchUp*\WebCache|data_*;f_*;index`
`FileKey3=%AppData%\SketchUp\SketchUp*\WebCache\GPUCache|*.*`

`[Skyler Lyon Kleaner *]`
`LangSecRef=3024`
`DetectFile=%ProgramFiles%\Skyler Lyon\Kleaner\Kleaner.exe`
`FileKey1=%ProgramFiles%\Skyler Lyon\Kleaner|*.txt`

`[Slim PDF Reader *]`
`LangSecRef=3021`
`DetectFile=%LocalAppData%\Investintech.com Inc\SPR`
`FileKey1=%LocalAppData%\Investintech.com Inc\SPR\*|*.log`
`FileKey2=%ProgramFiles%\Investintech.com Inc\Slim PDF Reader*\Licenses|*.*|REMOVESELF`

`[SmartDrive-Wiz *]`
`LangSecRef=3024`
`DetectFile=%ProgramFiles%\Opoku\SmartDrive-Wiz\SmartDrive-Wiz.exe`
`FileKey1=%ProgramFiles%\Opoku\SmartDrive-Wiz\Legal|*.*|REMOVESELF`
`FileKey2=%ProgramFiles%\Opoku\SmartDrive-Wiz\Log|*.*`

`[SmartSynchronize *]`
`LangSecRef=3024`
`DetectFile=%AppData%\syntevo\SmartSynchronize`
`FileKey1=%AppData%\syntevo\SmartSynchronize\*\Logs|*.*`

`[Softube Central *]`
`LangSecRef=3023`
`DetectFile=%AppData%\Softube*Central`
`FileKey1=%AppData%\Softube*Central\Logs|*.*`
`FileKey2=%AppData%\SoftubeCentral|*-journal;log.log;Network Persistent State`
`FileKey3=%AppData%\SoftubeCentral|*.old;LOG|RECURSE`
`FileKey4=%AppData%\SoftubeCentral\*Cache|*.*|RECURSE`
`FileKey5=%AppData%\SoftubeCentral\blob_storage|*.*|RECURSE`
`FileKey6=%AppData%\SoftubeCentral\Softube Central\Logs|*.*`

`[Solid Edge * ]`
`LangSecRef=3021`
`Detect1=HKCU\Software\Unigraphics Solutions\Solid Edge\Version 109`
`Detect2=HKCU\Software\Unigraphics Solutions\Solid Edge\Version 110`
`RegKey1=HKCU\Software\Unigraphics Solutions\Solid Edge\Version 109\MRUex`
`RegKey2=HKCU\Software\Unigraphics Solutions\Solid Edge\Version 110\MRUex`

`[Spider Player *]`
`LangSecRef=3023`
`DetectFile=%AppData%\Spider Player`
`FileKey1=%AppData%\Spider Player|URLHistory.xml`

`[Spitfire Audio *]`
`LangSecRef=3023`
`DetectFile1=%AppData%\com.spitfireaudio`
`DetectFile2=%AppData%\Spitfire Audio`
`FileKey1=%AppData%\com.spitfireaudio|*.log`
`FileKey2=%AppData%\Spitfire Audio\settings|*.log`

`[SPlayer *]`
`LangSecRef=3023`
`DetectFile=%AppData%\SPlayer`
`FileKey1=%AppData%\SPlayer|default.mpcpl;local.db`

`[Spybot AntiBeacon *]`
...
`FileKey1=%LocalAppData%\Safer-Networking Ltd\Spybot*|*.log;Spybot Lab.txt`

`[SpyHunter *]`
`LangSecRef=3024`
`DetectFile=%ProgramFiles%\EnigmaSoft\SpyHunter\SpyHunter*.exe`
`FileKey1=%ProgramFiles%\EnigmaSoft\SpyHunter\Logs|*.*`

`[SpyShelter *]`
`LangSecRef=3024`
`DetectFile=%AppData%\SpyShelter`
`FileKey1=%AppData%\SpyShelter|shelter-log.txt`

`[Steinberg Cubase *]`
`LangSecRef=3023`
`DetectFile=%ProgramFiles%\Steinberg\Cubase*`
`FileKey1=%ProgramFiles%\Steinberg\Cubase*|*.log`

`[Stellaris *]`
`Section=Games`
`DetectFile=%Documents%\Paradox Interactive\Stellaris`
`FileKey1=%Documents%\Paradox Interactive\Stellaris\.launcher-cache|*.*`
`FileKey2=%Documents%\Paradox Interactive\Stellaris\_backup_*\ShaderCache\dx*|*.*|REMOVESELF`
`FileKey3=%Documents%\Paradox Interactive\Stellaris\Cache|*.*`
`FileKey4=%Documents%\Paradox Interactive\Stellaris\Crashes|*.*|REMOVESELF`
`FileKey5=%Documents%\Paradox Interactive\Stellaris\Dumps|*.*`
`FileKey6=%Documents%\Paradox Interactive\Stellaris\Logs|*.*`
`FileKey7=%Documents%\Paradox Interactive\Stellaris\Screenshots|*.png`
`FileKey8=%Documents%\Paradox Interactive\Stellaris\ShaderCache\dx*|*.*|REMOVESELF`

`[Stremio *]`
`LangSecRef=3022`
`DetectFile=%LocalAppData%\Smart Code LTD\Stremio`
`FileKey1=%AppData%\Stremio\Stremio-Server\Stremio-Cache|*.*|RECURSE`
`FileKey2=%LocalAppData%\Smart Code LTD\Stremio\Cache|*.*|RECURSE`
`FileKey3=%LocalAppData%\Smart Code LTD\Stremio\QtWebEngine\Default|*-journal;LOG;LOG.old|RECURSE`
`FileKey4=%LocalAppData%\Smart Code LTD\Stremio\QtWebEngine\Default|Origin Bound Certs;QuotaManager;Visited Links`
`FileKey5=%LocalAppData%\Smart Code LTD\Stremio\QtWebEngine\Default\Service Worker\*Cache*|*.*|RECURSE`

`[SumatraPDF *]`
...
`DetectFile2=%LocalAppData%\SumatraPDF`
`FileKey2=%LocalAppData%\SumatraPDF\sumatrapdfcache|*.*`

`[SUMo *]`
...
`FileKey1=%AppData%\KC Softwares\SUMo|*.log;db.bak;errlst.txt;SUMo.cache;SUMo.skipped`

`[Syncios Cell Phone Backup & Manage *]`
...
`FileKey2=%AppData%\Syncios|*.log;log.txt`

`[Synthesia *]`
...
`FileKey1=%AppData%\Synthesia|log.txt;log-configuration.txt;recentSongs.xml`

`[SystemScheduler *]`
`LangSecRef=3024`
`DetectFile=%ProgramFiles%\SystemScheduler\Scheduler.exe`
`FileKey1=%ProgramFiles%\SystemScheduler\Events|*.*`

`[SystemTools Exporter *]`
`LangSecRef=3024`
`Detect=HKCU\Software\SystemTools\Exporter`
`RegKey1=HKCU\Software\SystemTools\Exporter\Recent File List`

`[SysTools AD Browser *]`
`LangSecRef=3024`
`DetectFile=%ProgramFiles%\SysTools AD Browser\ADBrowser.exe`
`FileKey1=%ProgramFiles%\SysTools AD Browser|Setup Log*.txt`

`[SysTools PDF Unlocker *]`
`LangSecRef=3021`
`DetectFile=%ProgramFiles%\SysTools PDF Unlocker\PDFUnlocker.exe`
`FileKey1=%ProgramFiles%\SysTools PDF Unlocker|*.log;Setup Log*.txt`

`[Task ForceQuit Pro *]`
`LangSecRef=3024`
`DetectFile=%CommonAppData%\Softorino\Task ForceQuit Pro*`
`FileKey1=%CommonAppData%\Softorino\Task ForceQuit Pro*\Logs|*.*`
`FileKey2=%CommonAppData%\Softorino\Task ForceQuit Pro*\Update|*.*`

`[TeamViewer *]`
...
`FileKey6=%LocalAppData%\TeamViewer\Database|tvchatfilecache.db`

`[Telemetry *]`
`LangSecRef=3026`
...
`FileKey29=%CommonAppData%\Mozilla|profile_count_*.json`

`[Temp Files *]`
`LangSecRef=3026`
...
`FileKey4=%ProgramFiles%\Mozilla*|*.tmp;*_tmp.exe|RECURSE`
...
`FileKey9=%LocalLowAppData%\Mozilla|Temp-*|*.*|REMOVESELF`

`[Tencent AndroidServer *]`
`LangSecRef=3021`
`DetectFile=%AppData%\Tencent\AndroidServer`
`FileKey1=%AppData%\Tencent\AndroidServer|*.log.xml`

`[Toshiba PC Diagnostic Tool Utility *]`
`LangSecRef=3024`
`DetectFile=%AppData%\Toshiba\PCDiag`
`FileKey1=%AppData%\Toshiba\PCDiag|*.*|RECURSE`
`FileKey2=%ProgramFiles%\Toshiba\configfree|*.log`

`[Total Commander Thumbnail Cache *]`
`LangSecRef=3024`
`DetectFile=%LocalAppData%\GHISLER`
`FileKey1=%LocalAppData%\GHISLER|tcthumbs.*db;treeinfoC.wc`

`[TP-Link *]`
...
`FileKey2=%LocalAppData%\TP-Link\nsissetup|*.log`

`[Track Folder Changes *]`
`LangSecRef=3024`
`Detect=HKCU\SOFTWARE\antiufo\TrackFolderChanges`
`RegKey1=HKCU\SOFTWARE\antiufo\TrackFolderChanges|LastFolder`

`[Trimble Connect for Sketchup *]`
`LangSecRef=3021`
`DetectFile=%AppData%\Trimble Connect for Sketchup`
`%AppData%\Trimble Connect for Sketchup\Logs|*.*`

`[Trusteer Rapport *]`
...
`FileKey4=%AppData%\Trusteer\Rapport\user\Logs|*.*`

`[TunelBear VPN *]`
`LangSecRef=3022`
`DetectFile=%AppData%\TunelBear`
`FileKey1=%AppData%\TunelBear\Logs|*.*`

`[TweakBit Internet Optimizer *]`
`LangSecRef=3024`
`DetectFile=%ProgramFiles%\TweakBit\Internet Optimizer\InternetOptimizer.exe`
`FileKey1=%ProgramFiles%\TweakBit\Internet Optimizer|GASender.exe;GoogleAnalyticsHelper.dll`
`RegKey1=HKLM\SOFTWARE\Auslogics\Google Analytics Package`

**Comment by APMichael** [comment]
`[Skyler Lyon Kleaner *]`
Entry already exists as `[Kleaner *]`.
