### ISSUE TITLE
[Enhancement] Winsys2.ini

### ISSUE THREAD

**Issue by winapp2** [MoscaDotTo/Winapp2#8]
We should add Winsys2.ini File for People who want to delete more files for a greater risk of course. I think the idea of Winapp2.ini for extreme entries is good. Because the people who know actually know what they're doing, they should have the chance to go along with this file. 

Am I wrong?

**Comment by TZocker** [comment]
https://www.dropbox.com/sh/dhfm9y23e2huj05/AAAgV8k-d_JCCF7tpQ9p-2JTa?dl=0

**Comment by CSGalloway** [comment]
I think if the entries to delete more files for a greater risk - should have it's on section.

**Comment by winapp2** [comment]
I think the new Winsys.ini should be maintained here with more entries in it. All people should have an eye on that entry.

**Comment by winapp2** [comment]
Pull sended, closing issue.
