### ISSUE TITLE
bugsplat (games) detected if poedit is installed

### ISSUE THREAD

**Issue by timse201** [MoscaDotTo/Winapp2#80]
If poedit (a translation editor) is installed it creates the path HKCU\Software\Bugsplat (\poedit\Poedit\) which is used to detect Bugsplat, too.

**Comment by MoscaDotTo** [comment]
Sounds like Bugsplat doesn't belong in the games category. 

Would probably recommend reassignment to utilities or applications. Thoughts?

**Comment by vslavik** [comment]
BugSplat is a [crash reporting system](https://www.bugsplat.com) used by many. Classifying it as anything other than “applications’ DLLs that are off-limits and shouldn’t be messed with in any way” is a truly bad idea.

**Comment by ROCKNROLLKID** [comment]
This was fixed in the last major update.
