### ISSUE TITLE
Time to say goodbye

### ISSUE THREAD

**Issue by APMichael** [MoscaDotTo/Winapp2#809]
This was my last update of the Winapp2.ini for now. Unfortunately, due to major changes in my job and personal life, I no longer have the time to continue maintaining Winapp2.ini. 😢

If all goes well, @MoscaDotTo will probably take over the maintenance again soon.

I hope to return to the project at some point. Until then, I wish you all a wonderful and healthy time.

**Comment by aquila-XP** [comment]
**@APMichael** It was a pleasure working with you.
Best of luck.

**Comment by APMichael** [comment]
@aquila-XP Many thanks for your kind words.

Also to you a big thank you for the many new and updated entries.

All the best to you.

**Comment by TZocker** [comment]
@APMichael All the best to you.
