### ISSUE TITLE
Slack Desktop application needs cleaning entries

### ISSUE THREAD

**Issue by FuccDucc** [MoscaDotTo/Winapp2#813]
The popular workplace communication service Slack has a Windows application at [https://slack.com/intl/en-nl/downloads/windows](https://slack.com/intl/en-nl/downloads/windows) and it has really bad cache management.

The bad cache management results in that it can grow to several GB's on your disk, especially in this folder location: `C:\Users\USERNAME\AppData\Roaming\Slack\Service Worker\CacheStorage` .. do note that before i initially found out about this, after a long period of Slack usage it was 8 GB in my case (which, let me rant, really isn't worth it just to get a l[ittle bit faster boot times](https://slack.engineering/service-workers-at-slack-our-quest-for-faster-boot-times-and-offline-support/) - "Slack Service Worker" cache article).

There are other cache folders as well, but they don't nearly as badly have the unlimited growth as "CacheStorage" (from ServiceWorker) does. Many PC users don't know they could clean up a couple of GB's purely from that folder alone, and also, clearing it has no negative impact on the operation, other than it may take a few launches to get + 50% boot speed upon cache regenerating, but it will be far from the original bloated size at that point. Regularly clearing it as soon it reaches GB's will be recommended, as long Slack doesn't improve their cache management/cache purging.

Like i said there are other cache folders, the main directory follows a format like CEF/Electron:

![index](https://user-images.githubusercontent.com/61570793/138557715-43192921-2597-4701-8b43-fc87f79e2b6e.png)

I'm saying because it will be the best if Winapp2.ini can add cleaning for all cache folders, like it does for many apps with this kind of folder layout. Currently, Winapp2 and Winapp3 have no entries for Slack at all, despite its popularity these days.. so someone who knows how to write Winapp entries (i dont) please help and get it added?

**Comment by APMichael** [comment]
Included in #824.
