### ISSUE TITLE
MEGASync Update

### ISSUE THREAD

**Issue by pogue** [MoscaDotTo/Winapp2#814]
So, I contacted mega.nz (aka mega.io now) regarding clearing the cache even further than what's done automatically. I posted this to Pifiform's forum [here](https://community.ccleaner.com/topic/61245-include-cache-clean-of-meganzs-megasync-software/?tab=comments#comment-332142), but the mods suggest I let you guys add it first.

So, here is what MEGA said when I asked them where their cache was located

> The location of the folder .debris/SyncDebris
As advised in our previous email, they are placed inside every local synced folder.
Data accidentally deleted in your Cloud Drive Sync folder gets moved to a hidden folder named .rubbish (WIN) or .debris (Linux and macOS) on your computer inside the local Sync folder .
Example: Megasync on Mint - where there are two synchronization folders set.
/home/user/Documents/sync folder 1/.debris
/home/user/Pictures/sync folder 2/.debris

> [...]

> Further to our previous email. MEGAsync writes temp files for regular downloads in the target folders, and for sync downloads in the "Rubbish/tmp" (or .debris/tmp) folder inside the sync path.

So MEGAsync always writes temporary files in the target drive.

> Our developers would not recommend deleting app and SDK caches.
As they keep information that should not be wiped up often, such as sessions, transfer information for resumption, account state, config of the application, etc
In any case, if you would like to clear up leftovers data, they would suggest wiping up .debris/SyncDebris folders of syncs, placed inside every local synced folder.

> My reply:
Thank you for your response. We at the winapp2.ini project believe that users should be allowed to clear any cache with wish, regardless of the negatives that might reset the settings of the application.
However, in cases like these where the deletion of the settings might cause problems, we use a popup window prompt the user that deleting these caches folders might cause problems with the apps with specifics of what they will do if the user chooses to delete them.
So, if you could please let me know the location of the folders app and SDK caches, as well as the location of the folder  .debris/SyncDebris I would greatly appreciate it.

> Further to our previous email. MEGAsync writes temp files for regular downloads in the target folders, and for sync downloads in the "Rubbish/tmp" (or .debris/tmp) folder inside the sync path.

> So MEGAsync always writes temporary files in the target drive.

> If there's anything else we can assist you with, please, let us know.

> Kind Regards,
MEGA Support

> Check answers to some frequently asked questions in our Help Centre here: https://mega.nz/help

> Follow us on https://www.facebook.com/MEGAprivacy https://twitter.com/MEGAprivacy & https://mega.nz/blog

Hopefully, that gives you enough information about where to start looking for the MEGASync cached files, and their SDK files which are, from what I gleam from these emails are deletable and regenerate, but you have to redo all your settings and so you'd probably want to put a pop-up on that one warning users it will reset all their settings.

You can download the MegaSync software at [https://mega.io/sync](https://mega.io/sync)

Thanks for your help!
pogue

P.S. - Is there any option somewhere in the Github settings where you can have it email you when you get a new reply to a post? I'm looking everywhere and not seeing that as an option. Thanks.

**Comment by TZocker** [comment]
> So, I contacted mega.nz (aka mega.io now) regarding clearing the cache even further than what's done automatically. I posted this to Pifiform's forum [here](https://community.ccleaner.com/topic/61245-include-cache-clean-of-meganzs-megasync-software/?tab=comments#comment-332142), but the mods suggest I let you guys add it first.
> 
> So, here is what MEGA said when I asked them where their cache was located
> 
> > The location of the folder .debris/SyncDebris
> > As advised in our previous email, they are placed inside every local synced folder.
> > Data accidentally deleted in your Cloud Drive Sync folder gets moved to a hidden folder named .rubbish (WIN) or .debris (Linux and macOS) on your computer inside the local Sync folder .
> > Example: Megasync on Mint - where there are two synchronization folders set.
> > /home/user/Documents/sync folder 1/.debris
> > /home/user/Pictures/sync folder 2/.debris
> 
> > [...]
> 
> > Further to our previous email. MEGAsync writes temp files for regular downloads in the target folders, and for sync downloads in the "Rubbish/tmp" (or .debris/tmp) folder inside the sync path.
> 
> So MEGAsync always writes temporary files in the target drive.
> 
> > Our developers would not recommend deleting app and SDK caches.
> > As they keep information that should not be wiped up often, such as sessions, transfer information for resumption, account state, config of the application, etc
> > In any case, if you would like to clear up leftovers data, they would suggest wiping up .debris/SyncDebris folders of syncs, placed inside every local synced folder.
> 
> > My reply:
> > Thank you for your response. We at the winapp2.ini project believe that users should be allowed to clear any cache with wish, regardless of the negatives that might reset the settings of the application.
> > However, in cases like these where the deletion of the settings might cause problems, we use a popup window prompt the user that deleting these caches folders might cause problems with the apps with specifics of what they will do if the user chooses to delete them.
> > So, if you could please let me know the location of the folders app and SDK caches, as well as the location of the folder  .debris/SyncDebris I would greatly appreciate it.
> 
> > Further to our previous email. MEGAsync writes temp files for regular downloads in the target folders, and for sync downloads in the "Rubbish/tmp" (or .debris/tmp) folder inside the sync path.
> 
> > So MEGAsync always writes temporary files in the target drive.
> 
> > If there's anything else we can assist you with, please, let us know.
> 
> > Kind Regards,
> > MEGA Support
> 
> > Check answers to some frequently asked questions in our Help Centre here: https://mega.nz/help
> 
> > Follow us on https://www.facebook.com/MEGAprivacy https://twitter.com/MEGAprivacy & https://mega.nz/blog
> 
> Hopefully, that gives you enough information about where to start looking for the MEGASync cached files, and their SDK files which are, from what I gleam from these emails are deletable and regenerate, but you have to redo all your settings and so you'd probably want to put a pop-up on that one warning users it will reset all their settings.
> 
> You can download the MegaSync software at https://mega.io/sync
> 
> Thanks for your help! pogue
> 
> P.S. - Is there any option somewhere in the Github settings where you can have it email you when you get a new reply to a post? I'm looking everywhere and not seeing that as an option. Thanks.


PLS Test:


[MEGAsync*]
Section=3024
DetectFile=%CommonAppData%\MEGAsync
FileKey1=%LocalAppData%\MEGAsync|*.png
FileKey2=%LocalAppData%\Mega Limited\MEGAsync|*.bak
FileKey3=%LocalAppData%\Mega Limited\MEGAsync|*.bak
FileKey4=%LocalAppData%\Mega Limited\MEGAsync\logs|*.log
FileKey5=%LocalAppData%\Mega Limited\MEGAsync\crashDumps|*.*

**Comment by MoscaDotTo** [comment]
the megasync entry above has been included in 20230901, please re-file if this isn't sufficient
