### ISSUE TITLE
missing Origin PC cache folders

### ISSUE THREAD

**Issue by FuccDucc** [MoscaDotTo/Winapp2#825]
for the gaming platform [Origin](https://www.origin.com/usa/en-us/store/download), some cache locations aren't included in Winapp2 yet, but should be:

AppData\Local\Origin\Origin\QtWebEngine\Default\Application Cache
AppData\Local\Origin\Origin\QtWebEngine\Default\Service Worker\CacheStorage
AppData\Local\Origin\Origin\QtWebEngine\Default\Service Worker\ScriptCache
AppData\Local\Origin\Origin\cache\QtWebEngine\Default\Cache
AppData\Local\Origin\Web Cache

**Comment by APMichael** [comment]
The last two locations are already cleaned up by Winapp2.ini:
```
FileKey8=%LocalAppData%\Origin\Origin\cache|*.*|RECURSE
FileKey12=%LocalAppData%\Origin\Web Cache|*.*|RECURSE
```
The others were added #824.
