### ISSUE TITLE
Add an option to download winapp3.ini from winapp2ool

### ISSUE THREAD

**Issue by Shakil-Shahadat** [MoscaDotTo/Winapp2#830]

**Comment by MoscaDotTo** [comment]
This is already supported, select option 6 in the downloader screen 
![image](https://user-images.githubusercontent.com/529203/141705080-fdaa3b71-1952-4020-b4c7-2989676ff9ee.png)

**Comment by Shakil-Shahadat** [comment]
Thanks. It's not available in the current release version.

Anyway, when can I expect to see version 1.5 to be released?

**Comment by MoscaDotTo** [comment]
![image](https://user-images.githubusercontent.com/529203/141705403-aa7f2833-08ee-440e-8d9e-a19db1625757.png)

This option has been available for quite a while, here it is in v1.02 from 2019 :) 

The option is "advanced" in the Downloader menu 
![image](https://user-images.githubusercontent.com/529203/141705437-85d0e4b1-a882-4b1a-864e-8ef0d3353bc8.png)

If the update notification for v1.5 doesnt appear you can update by downloading winapp2ool through the downloads menu (option 3)

**Comment by Shakil-Shahadat** [comment]
Oh, got it. Got the latest version of wnapp2ool too.

Thanks again.
