### ISSUE TITLE
'CCleaner Driver Updater Removal'

### ISSUE THREAD

**Issue by wefalltomorrow** [MoscaDotTo/Winapp2#831]
This entry from Winapp3 seems to break CCleaner after the v5.87.9306 update. Any other methods to remove the Driver Updater for the time being without bricking CCleaner? Cheers.

**Comment by Shakil-Shahadat** [comment]
CCleaner doesn't even run after removing `CCleanerDU.dll`. I don't think there is anyway.

**Comment by wefalltomorrow** [comment]
> 
> 
> CCleaner doesn't even run after removing `CCleanerDU.dll`. I don't think there is anyway.

It worked in the previous update, I might have to revert for now then sadly.

**Comment by Shakil-Shahadat** [comment]
I meant doesn't work in the current version.

**Comment by wefalltomorrow** [comment]
I've just reverted to CCleaner v5.73.8130 permanently, can't be bothered dealing with their crappy updates anymore.

**Comment by APMichael** [comment]
Strange, it still works fine for me. I have tested it with the "Slim" and the "Portable" version.
