### ISSUE TITLE
Opera GX Gaming Browser

### ISSUE THREAD

**Issue by sirinath** [MoscaDotTo/Winapp2#839]
Can rules be added for Opera GX?

**Comment by APMichael** [comment]
The browser "Opera GX" is already supported. The entries for "Opera" clean up all versions of "Opera" including "Opera GX".

**Comment by sirinath** [comment]
Running CCEnhancer the additional cleaning options for Opera GX is not shown in the UI but shown for other Chrome based browsers.

**Comment by APMichael** [comment]
CCleaner shows the entries correctly under "Opera":
![grafik](https://user-images.githubusercontent.com/33252157/144832085-1aa8bee4-48a5-4d9a-baf0-e59d9c8335a2.png)

**Comment by sirinath** [comment]
Opera seams OK now but for Chrome does not show all the options:

![image](https://user-images.githubusercontent.com/637415/144839413-3e2f6084-a59f-46f4-93e4-ec75d2f7ac02.png)

**Comment by sirinath** [comment]
A side question. Is [7-zip ZS](https://github.com/mcmilk/7-Zip-zstd) fork supported through the 7-Zip options in a similar way?

**Comment by APMichael** [comment]
> Opera seams OK now but for Chrome does not show all the options:

This does not seem to be due to the winapp2.ini. Do you use the function "Advanced" > "Trim winapp2.ini" in the CCEnhancer? Probably this function causes the problems with the not shown entries. Alternatively, you can try the Trim function from winapp2ool.

> A side question. Is [7-zip ZS](https://github.com/mcmilk/7-Zip-zstd) fork supported through the 7-Zip options in a similar way?

Unfortunately no, "7-Zip ZS" would need its own entry:
```
[7-Zip ZS *]
LangSecRef=3024
Detect=HKCU\Software\7-Zip-Zstandard
RegKey1=HKCU\Software\7-Zip-Zstandard\Compression|ArcHistory
RegKey2=HKCU\Software\7-Zip-Zstandard\Extraction|PathHistory
RegKey3=HKCU\Software\7-Zip-Zstandard\FM|CopyHistory
RegKey4=HKCU\Software\7-Zip-Zstandard\FM|FolderHistory
RegKey5=HKCU\Software\7-Zip-Zstandard\FM|PanelPath0
RegKey6=HKCU\Software\7-Zip-Zstandard\FM|PanelPath1
```

**Comment by sirinath** [comment]
The options go missing here an there every time I update and run Trim.

**Comment by MoscaDotTo** [comment]
After running trim, return to the winapp2ool main menu and type `savelog` to get a copy of the trim log. This will show you exactly which entries did and did not return relevant detection criteria for your system. winapp2ool will automatically save a file called winapp2ool.log when you do this.

**Comment by MoscaDotTo** [comment]
FWIW CCEnhancer's trim feature delivers a very sparse winapp2.ini for me as well. ~100 entries vs. the 224 on my machine produced by winapp2ool trim, notably most of the Chromium entries are missing. At a glance, I would say that CCEnhancer's trim does not support wildcards in DetectFiles

**Comment by MoscaDotTo** [comment]
winapp2ool's trim module is built on top of various other parts of the winapp2ool application; it's probably not a simple or straightforward port to make, depending on how ccenhancer's trim function is built. If he were to adapt the winapp2ool trim algorithm, it may require a significant amount of work just for the singular feature. that said, the trim source is freely available under the gplv3 license, along with the rest of winapp2ool's source. 

https://github.com/MoscaDotTo/Winapp2/blob/master/winapp2ool/modules/trim/Trim.vb

**Comment by ShaneGowland** [comment]
> At a glance, I would say that CCEnhancer's trim does not support wildcards in DetectFiles

Correct. It's been on my to-do list to fix since around 2013, so I'm starting to think it's not going to get fixed :/

**Comment by APMichael** [comment]
@MoscaDotTo and @ShaneGowland : Thank you very much for your replies.

**Comment by sirinath** [comment]
Can the entry for 7-Zip ZS be added?

**Comment by MoscaDotTo** [comment]
Yes

**Comment by MoscaDotTo** [comment]
included in the latest update
