### ISSUE TITLE
[BleachBit] Issue with Java.ini

### ISSUE THREAD

**Issue by sirinath** [MoscaDotTo/Winapp2#840]
I get the following error in BelachBit:

```
parsing error in section Folders View Settings *
Traceback (most recent call last):
  File "bleachbit\Winapp.pyo", line 171, in __init__
  File "bleachbit\Winapp.pyo", line 296, in handle_section
  File "bleachbit\Winapp.pyo", line 297, in <listcomp>
  File "bleachbit\Winapp.pyo", line 217, in excludekey_to_nwholeregex
NotImplementedError: REG not supported in ExcludeKey
neither option LangSecRef nor Section found in section Previous Java Installation Cleanup *
```

**Comment by APMichael** [comment]
> ```
> parsing error in section Folders View Settings *
> Traceback (most recent call last):
>   File "bleachbit\Winapp.pyo", line 171, in __init__
>   File "bleachbit\Winapp.pyo", line 296, in handle_section
>   File "bleachbit\Winapp.pyo", line 297, in <listcomp>
>   File "bleachbit\Winapp.pyo", line 217, in excludekey_to_nwholeregex
> NotImplementedError: REG not supported in ExcludeKey
> ```

Most of the error message is caused by the entry `[Folders View Settings *]`, because BleachBit does not support `ExcludeKey` with `REG|`. Therefore BleachBit always automatically downloads its own minimally modified version of the winapp2.ini.

If you want to use the official winapp2.ini with BleachBit, then you must delete the following lines of the entry `[Folders View Settings *]` before:
```
ExcludeKey1=REG|HKCU\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\Bags\AllFolders
ExcludeKey2=REG|HKCU\Software\Classes\Wow6432Node\Local Settings\Software\Microsoft\Windows\Shell\Bags\AllFolders
ExcludeKey3=REG|HKCU\Software\Microsoft\Windows\Shell\Bags\1\Desktop
ExcludeKey4=REG|HKCU\Software\Microsoft\Windows\ShellNoRoam\Bags\AllFolders
```
Or better the complete entry `[Folders View Settings *]`.

---

> ```
> neither option LangSecRef nor Section found in section Previous Java Installation Cleanup *
> ```

The Java.ini is only for use with winapp2ool: `; This ini contains meta instructions for winapp2ool to help construct a winapp2.ini entry to clean up after old java versions.`

**Comment by MoscaDotTo** [comment]
java.ini is likely fairly out of date as well, the keys for it were provided by someone else with an interest in it who hasn't been in contact for quite some time

**Comment by sirinath** [comment]
Is it possible to incorporate these additional settings into the `winapp2` file? Java, 7Z ZS, etc.

**Comment by sirinath** [comment]
What does the above settings do?

**Comment by sirinath** [comment]
Can Bleachbits be updated to supported these combinations?

**Comment by MoscaDotTo** [comment]
java.ini is used by winapp2ool to generate a custom entry to remove traces from the java installer with thousands of regkeys (over 2600), it's really not needed unless you have a special concern about these traces. And it's also not been kept up-to-date with newer java versions, so it'll only clean traces up to the version of java that was out when it was created. 

you can access the javamaker module in winapp2tool by typing m on the main menu. Items in the experimental minefield menu may be unstable, unfinished, or crash winapp2ool when run. YMMV.

**Comment by MoscaDotTo** [comment]
java.ini cannot on its own be used with bleachbit at all as it is formatted for use with winapp2ool and does not contain clean-up instructions on its own.
