### ISSUE TITLE
Missing LangSecRef in MATLAB entry

### ISSUE THREAD

**Issue by njascgil** [MoscaDotTo/Winapp2#851]
It appears that the MATLAB entry might be missing something like

`LangSecRef=3021`

**Comment by APMichael** [comment]
Good catch! Thank you.

It is also missing from the following entries:
```
[ABBYY Lingvo *]
LangSecRef=3021

[Cyber Privacy Suite *]
LangSecRef=3024

[Freemake Video Converter *]
LangSecRef=3023

[MATLAB *]
LangSecRef=3021
```
Maybe this could be added WinappDebug, so that each entry is checked if there is a `LangSecRef=` or `Section=`?

**Comment by njascgil** [comment]
After reading a bit more to try to answer your question, I noticed that the README.md states that, regarding `LangSecRef=` 

> If this key is not provided, CCleaner will append the entry to the bottom of the Applications tab.

However, I found out that the `LangSecRef=` was missing in the `[MATLAB *]` section precisely because it was being misplaced by CCleaner. Perhaps CCleaner has changed regarding this behaviour? It that's indeed the case, checking for the completeness of each entry seems a nice idea!

**Comment by MoscaDotTo** [comment]
Can do!

Line: 2731 - Error: Entries should have either a LangSecRef or a Section key.
Entry Name: [ABBYY Lingvo *]

Line: 7219 - Error: Entries should have either a LangSecRef or a Section key.
Entry Name: [Cyber Privacy Suite *]

Line: 9909 - Error: Entries should have either a LangSecRef or a Section key.
Entry Name: [Freemake Video Converter *]

Line: 13038 - Error: Entries should have either a LangSecRef or a Section key.
Entry Name: [MATLAB *]

This was the result, a new build will be available soon with this feature
