### ISSUE TITLE
Latest version deletes c:\temp !!!!!!!!

### ISSUE THREAD

**Issue by jvidalw** [MoscaDotTo/Winapp2#881]
Hi!

Some "genius" decided to add an entry to Winapp2.ini that causes deletion of c::\temp. This deleted about 30 GB of stuff I had there.
You should REALLY be more careful about what is added to the file. C:\temp is NOT an official temporary folder! those are \windows\temp and \users\username\appdata\local\temp. Plus, **this new location was enabled by default**, instead of  leaving the choice to the user, as is the usual with other additions.

I hope this can be reversed.
Fortunately I had most of my stuff backed up.

**Comment by jvidalw** [comment]
it should be fixed ASAP

**Comment by MoscaDotTo** [comment]
https://github.com/MoscaDotTo/Winapp2/commit/343b24421200176f9339a7a040477941f909ff9f

Sure thing :)

**Comment by jvidalw** [comment]
thanks!!
