### ISSUE TITLE
chrome/chromium difference

### ISSUE THREAD

**Issue by pwn0r** [MoscaDotTo/Winapp2#89]
I apologize if this is not a correct place to report this. I use beta BleachBit with community updates. 

There are some leftovers for chromium, as some items being cleaned for chrome only. 

one such issue is crashpads:

`FileKey2=%LocalAppData%\Google\Chrome\User Data\Crashpad\reports|*.*`

This obviously cleans these reports for Chrome only and there is no reference for Chromium crashpad otherwise in the file.

**Comment by MoscaDotTo** [comment]
If you can provide the paths for Chromium, I'll add them in.

**Comment by pwn0r** [comment]
`%localappdata%\Chromium\User Data\Crashpad\reports\`

for this case but there are more items which also have chromium folder not specified.

From looking into non-cc winapp2 file I can name e.g. [Google Cloud Messaging*] ; [Extensions State*] ; [History*] ; [Session Storage*] etc
But some items already have both chromium and chrome locations. And some items like e.g. updates do not exist on chromium, which is correct.

**Comment by MoscaDotTo** [comment]
See #91

**Comment by pwn0r** [comment]
thanks. Cannot try now though as I'm using Bleachbit.
