### ISSUE TITLE
WinApp2oolXP Download

### ISSUE THREAD

**Issue by Uzer999999999** [MoscaDotTo/Winapp2#900]
Where does one fine WinApp2oolXP to download?

**Comment by MoscaDotTo** [comment]
winapp2oolxp hasnt been maintained for a while and i cannot guarantee that it fully functions but you can find the download on the release page for winapp2ool 1.02 

https://github.com/MoscaDotTo/Winapp2/releases/download/v1.02/winapp2oolXP.exe
