### ISSUE TITLE
There will be no more winapp2 updates?

### ISSUE THREAD

**Issue by zekecarter** [MoscaDotTo/Winapp2#902]
I am sorry to give my opinion here I make the query because it has been 3 months without updates either additions deletions, or they have moved web page if so could you tell us which page to visit to check for updates?

**Comment by MoscaDotTo** [comment]
there's a very large set of changes pending a final review, unfortunately something in real-life came up which occupied the majority of my summer but I'm hoping to clean up the last little bits and push it forward soon. You can read more here: 
https://github.com/MoscaDotTo/Winapp2/pull/895

**Comment by MoscaDotTo** [comment]
notably some of these winapp2.ini changes have required winapp2ool changes as well which is most of the remaining work. you can download and use the latest winapp2.ini with all the upcoming changes here: https://raw.githubusercontent.com/MoscaDotTo/Winapp2/635b25ad37fd53a281d9daad1612f0f368c8e4c3/Winapp2.ini

**Comment by jvidalw** [comment]
thanks for the update, I was wondering the same thing

**Comment by unrealtitle99** [comment]
@MoscaDotTo 

Will there be any more updates for Winapp2.ini? Not that any of us probably want to, but if there are no more updates, where can we find a suitable alternative?

**Comment by Janaue** [comment]
> notably some of these winapp2.ini changes have required winapp2ool changes as well which is most of the remaining work. you can download and use the latest winapp2.ini with all the upcoming changes here: https://raw.githubusercontent.com/MoscaDotTo/Winapp2/635b25ad37fd53a281d9daad1612f0f368c8e4c3/Winapp2.ini

hello, what is the difference between the master branch and the ''branch1'' of Winapp2 ? is branch1 just the beta version ?
