### ISSUE TITLE
Some new entries for you to add.

### ISSUE THREAD

**Issue by jensdraht1999** [MoscaDotTo/Winapp2#910]
[Sandisk Installer*]
LangSecRef=3024
DetectFile1=%AppData%\com.sandisk.softwareInstaller
FileKey1=%AppData%\com.sandisk.softwareInstaller\Logs|*.*|REMOVESELF

[Stranded Deep*]
Section=Games
DetectFile1=%LocalLowAppData%\Beam Team Games\Stranded Deep
FileKey1=%LocalLowAppData%\Beam Team Games\Stranded Deep|*.log

[Topaz Video AI*]
LangSecRef=3023
Detect1=HKCU\SOFTWARE\Topaz Labs LLC\Topaz Video Enhance AI
Detect2=HKCU\SOFTWARE\Topaz Labs LLC\Topaz Video AI
Detect3=HKCU\SOFTWARE\Topaz Labs LLC\Video Enhance AI
FileKey1=%AppData%\Topaz Labs LLC\Topaz Video AI\logs|*.*|REMOVESELF

[Topaz Photo AI*]
LangSecRef=3023
Detect1=HKCU\SOFTWARE\Topaz Labs LLC\Topaz Photo AI
FileKey1=%CommonAppData%\Topaz Labs LLC\Topaz Photo AI\Logs|*.*|REMOVESELF

[Blackmagic Design DaVinci Resolve*]
LangSecRef=3023
Detect1=HKCU\SOFTWARE\Blackmagic Design\DaVinci Resolve
FileKey1=%CommonAppData%\Blackmagic Design\DaVinci Resolve\Support\logs|*.*|REMOVESELF
FileKey2=%AppData%\Blackmagic Design\DaVinci Resolve\Support\logs|*.*|REMOVESELF|RECURSE

[PageTech PCLReader*]
LangSecRef=3024
DetectFile1=%CommonAppData%\PageTech
Detect=HKLM\SOFTWARE\PageTech
FileKey1=%CommonAppData%\PageTech|*.log

[Proton VPN*]
LangSecRef=3024
DetectFile1=%ProgramFiles%\Proton Technologies\ProtonVPN
FileKey1=%CommonAppData%\ProtonVPN\Logs|*.*|REMOVESELF
FileKey2=%CommonAppData%\ProtonVPN\UpdaterLogs|*.*|REMOVESELF

[Samsung MSSCS*]
LangSecRef=3024
Detect1=HKLM\SOFTWARE\SAMSUNG
FileKey1=%CommonAppData%\Samsung\MSSCS|*.log

**Comment by APMichael** [comment]
Added in version 230217.
