### ISSUE TITLE
NVidia installer

### ISSUE THREAD

**Issue by pwn0r** [MoscaDotTo/Winapp2#92]
Up for consideration yet another junk (?) folder by NVidia. 

it is amazing how many different folder locations they use and then leave junk pretty much forever.
From real world cases (a few workstations) I have seen 2-3gb of apparent junk in this folder. The current record would be 6gb.

`%ProgramFiles%\NVIDIA Corporation\Installer2\`

It looks like this folder is yet another installer cache (for whatever reason) and the content can be simply deleted -- which I do manually. Cannot guarantee that it would not cause any consequences though I haven't seen any problems so far.  A somewhat safer option would be to delete all cached installs but the most recent version.

PS. This folder is wiped by nvidia itself during  new drivers installation but only for "clean install". Otherwise all that junk remains intact.

**Comment by MoscaDotTo** [comment]
IIRC that path used to be in winapp2.ini but was removed because deleting it rendered the user unable to simply uninstall the graphics drivers. Do you know if this behavior has changed?

**Comment by pwn0r** [comment]
I can try to run some experiments. In any case this does not prevent a user to install a new version. And by uninstall you mean uninstall from Programs and Features?

**Comment by TZocker** [comment]
When you want to reduce the file space from this folder, you can set in the Nvidia updater/ installation process in experience settings, the checkbox for driver reinstallation!

Its hard for us the clean it with wildcards, because you have the problem with the deinstallation of the driver (you need first a reinstallation). Only option it a script who detect witch version is installed an whats old. xD
Be free to creat a script who do this.

**Comment by pwn0r** [comment]
>  you can set in the Nvidia updater/ installation process in experience settings, the checkbox for driver reinstallation!

Sorry what? :)   And what kind of scripts are used?  what language?

**Comment by TZocker** [comment]
Language is international. 

Dont use quick installation!

http://s1.bild.me/bilder/110417/9428668nv.png

**Comment by ROCKNROLLKID** [comment]
Has this issue been resolved?

**Comment by TZocker** [comment]
No, but its only possible to solve it only with external scripts.

Because you can't delet the hole folder. When you do it you have to do a reinstall of the Driver if you want a removal.

greetz

**Comment by TZocker** [comment]
http://nvidia.custhelp.com/app/answers/detail/a_id/3333/~/disk-space-used-when-installing-nvidia-drivers

**Comment by ROCKNROLLKID** [comment]
Well I am going to go ahead and close this since this isn't a issue with Winapp2.

For the record, if you want a complete clean of Nvidia or even AMD, you can look up a tool called Display Driver Uninstaller. It is very good tool and I use it all the time when I update drivers.
