### ISSUE TITLE
update Razer cache cleaning

### ISSUE THREAD

**Issue by FuccDucc** [MoscaDotTo/Winapp2#920]
Entries `[Razer *]` misses cleaning the following paths:

C:\Users\[USERNAME]\AppData\Local\Razer\Razer Central\WebAppCache (delete all contents)
C:\Users\[USERNAME]\AppData\Local\Razer\Synapse3\Cache (delete all contents)
C:\Users\[USERNAME]\AppData\Local\Razer\Synapse3\Settings\GACache.bin (delete file)
C:\Users\[USERNAME]\AppData\Local\Razer\Synapse3\Log (delete all .log files in this and subfolders)

C:\ProgramData\Razer\BigDataSDK\Logs (delete all contents)
C:\ProgramData\Razer\GameManager\Logs (delete all contents)
C:\ProgramData\Razer\Installer\Logs (delete all contents)
C:\ProgramData\Razer\Razer Central\Logs (delete all contents)
C:\ProgramData\Razer\Razer Central\WebAppCache (delete all contents)
C:\ProgramData\Razer\Synapse3\Log (delete all .log files in this and subfolders)

**Comment by APMichael** [comment]
**Modified Entry:**

```
[Razer *]
LangSecRef=3024
DetectFile=%CommonAppData%\Razer
FileKey1=%CommonAppData%\Razer\*|DiagnoseReport*.txt
FileKey2=%CommonAppData%\Razer\*\*Cache|*
FileKey3=%CommonAppData%\Razer\*\Accounts\*\DataSync|SyncDate.txt
FileKey4=%CommonAppData%\Razer\*\Log|*.log|RECURSE
FileKey5=%CommonAppData%\Razer\*\Logs|*
FileKey6=%CommonAppData%\Razer\*\ProductUpdates\Downloads|*
FileKey7=%LocalAppData%\Razer\*\*Cache|*
FileKey8=%LocalAppData%\Razer\*\Log|*.log|RECURSE
FileKey9=%LocalAppData%\Razer\*\Logs|*
FileKey10=%LocalAppData%\Razer\*\Settings|GACache.bin
FileKey11=%ProgramFiles%\Razer\*|*.log
```

**Comment by MoscaDotTo** [comment]
fixed in a forthcoming update
