### ISSUE TITLE
Steam* deletes critical files in the cache directory 

### ISSUE THREAD

**Issue by biffzinker** [MoscaDotTo/Winapp2#922]
It causes Steam to do a self repair, and another download of packages.

**Comment by Feathered-Serpent** [comment]
Not only that, but there are also games which don't find their savegames anymore, after deleting the remotecache.vdf files. In my case it was **Unpacking**

**Comment by TZocker** [comment]
|remotecache.vdf shoud not be deleted ....

FileKey17=%ProgramFiles%\Steam\userdata\*\*|remotecache.vdf

But i have my games not on C: ...

**Comment by TZocker** [comment]
So I tested again on my Laptop. Here I have games on C:.

But I do not have the Problem with hat also deletes certain Steam settings.

I Think its the best way to seperate it with a warning for the remotecache. 
I think its only a Problem when you don't sync your savegames with the cloud.

**Comment by MoscaDotTo** [comment]
hi! this was caused by deleting the .ico file

**Comment by MoscaDotTo** [comment]
going to be pushing an update which addresses this shortly, please file a new bug if issues persist
