### ISSUE TITLE
Something in the recent update seems to brick Windows, will cause Error 2203 when trying to install programs

### ISSUE THREAD

**Issue by ghostmotley** [MoscaDotTo/Winapp2#923]
Something in the recent update seems to brick Windows, will cause Error 2203 when trying to install programs, I've replicated this on two machines and it will begin after running CCLeaner with latest Winapp2 installed.

From reading the error logs, I believe it related to something it cleans in the Windows Installer or one of the .NET Framework cleanups.

I've tested on two machines, both Windows 11 22H2 (Build version 22621.1413) with CCleaner version v6.10.10347, CCenhancer version 4.5.7 and winapp2 version 230301

**Comment by APMichael** [comment]
This is what happened: The entry `[Windows Temporary Files *]` not only cleaned up the temp folders, but also deleted the temp folders themselves. However, the new temp folders automatically recreated by Windows then no longer have their original permissions and owners. 

The latest version **230316** of Winapp2.ini should not corrupt the temp folders anymore (https://github.com/MoscaDotTo/Winapp2/commit/3d4640e905e490c591df98df11669730e31a374c).
