### ISSUE TITLE
Shellbags problem

### ISSUE THREAD

**Issue by Cybersm20** [MoscaDotTo/Winapp2#926]
Hi,in Windows 10,with current shellbags option,when i restart explorer,icons appears not at their size and position.
I found a simple solution that I tested and it works.

[Windows Shell - Folder View Settings *]
LangSecRef=3025
Detect=HKCU\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell
Warning=This will delete window size, window position and view setting of all folders.
RegKey1=HKCU\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\Bags
RegKey2=HKCU\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\BagMRU

This way you clean the shellbags without any anomaly.Tested with shellbag analyzer.

**Comment by APMichael** [comment]
JFYI, the entry "Folder View Settings" was not changed during the major overhaul, so it behaves as it has for years. The "problem" with the entry is that it covers all Windows versions (7-11). Therefore there was a discussion about it earlier and a suggestion to split it: https://github.com/MoscaDotTo/Winapp2/issues/289#issuecomment-402127308

**Comment by Cybersm20** [comment]
Itried so many ways to rescue every Shellbag delete with this  method,but everything is completely clean.Thank you.
