### ISSUE TITLE
VALORANT & Riot Vanguard

### ISSUE THREAD

**Issue by FeetChecker** [MoscaDotTo/Winapp2#927]
Vanguard leftover a lot of log files in there program files directory.

-- VALORANT --
%localappdata%\VALORANT\Saved\Logs => *.log files
%localappdata%\VALORANT\Saved\Crashes => Everything only on game crashes

-- Riot Vanguard --
C:\Program Files\Riot Vanguard\Logs => *.log files

**Comment by MoscaDotTo** [comment]
covered in the most recent update
