### ISSUE TITLE
Modified entries for winapp3.ini

### ISSUE THREAD

**Issue by aquila-XP** [MoscaDotTo/Winapp2#930]
`[Adobe Acrobat DC Languages *]`
...
`FileKey20=%ProgramFiles%\Adobe\Acrobat DC\Acrobat|nppdf32.*`
`FileKey21=%ProgramFiles%\Adobe\Acrobat DC\Acrobat\*App\*|*.aapp|REMOVESELF`
`FileKey22=%CommonProgramFiles%\Adobe\Acrobat\ActiveX|AcroPDF*.*;PDFShell.*`
`FileKey23=%CommonProgramFiles%\Adobe\HelpCfg\*|*.helpcfg|REMOVESELF`
`FileKey24=%ProgramFiles%\Adobe\Acrobat DC\Acrobat\Air|nppdf32.*`
`FileKey25=%ProgramFiles%\Adobe\Acrobat DC\Acrobat\Browser|nppdf32.*`
`FileKey26=%ProgramFiles%\Adobe\Acrobat DC\Acrobat\DocSettings\CombineFiles\*|coversheet.pdf|REMOVESELF`
`FileKey27=%ProgramFiles%\Adobe\Acrobat DC\Acrobat\DocTemplates\*|template*.pdf|REMOVESELF`
`FileKey28=%ProgramFiles%\Adobe\Acrobat DC\Acrobat\FileInfo|FileInfo_*.dat|REMOVESELF`
`FileKey29=%ProgramFiles%\Adobe\Acrobat DC\Acrobat\HostedServicesTemplates\*|template*.pdf|REMOVESELF`
`FileKey30=%ProgramFiles%\Adobe\Acrobat DC\Acrobat\IDTemplates\*|*ID.pdf|REMOVESELF`
`FileKey31=%ProgramFiles%\Adobe\Acrobat DC\Acrobat\Legal\*|eula.ini|REMOVESELF`
`FileKey32=%ProgramFiles%\Adobe\Acrobat DC\Acrobat\Locale\*|*.*|REMOVESELF`
`FileKey33=%ProgramFiles%\Adobe\Acrobat DC\Acrobat\plug_ins\Annotations\Stamps\*|*.pdf|REMOVESELF`
`FileKey34=%ProgramFiles%\Adobe\Acrobat DC\Acrobat\plug_ins\MSRMS\Resources|pagezerowrapper_*.pdf`
`FileKey35=%ProgramFiles%\Adobe\Acrobat DC\Acrobat\plug_ins\Multimedia\MPP|Flash.*;MCIMPP.*;WindowsMedia.*`
`FileKey36=%ProgramFiles%\Adobe\Acrobat DC\Acrobat\plug_ins\Preflight|PreflightLib.*|REMOVESELF`
`FileKey37=%ProgramFiles%\Adobe\Acrobat DC\Acrobat\plug_ins|PreFlight.*`
`FileKey38=%ProgramFiles%\Adobe\Acrobat DC\Acrobat\Sequences\*|Action*.sequ|REMOVESELF`
`FileKey39=%ProgramFiles%\Adobe\Acrobat DC\Acrobat\UICustomization\*|Custom*.aaui|REMOVESELF`
`FileKey40=%ProgramFiles%\Adobe\Acrobat DC\Acrobat\WebResources\Resource*\app*\dc-desktop-*-dropin\*|translations-*-json.js`
...
`ExcludeKey27=FILE|%CommonProgramFiles%\Adobe\Acrobat\ActiveX\|PDFShell.dll`
`ExcludeKey28=FILE|%ProgramFiles%\Adobe\Acrobat DC\Acrobat\Air\|nppdf32.dll`
`ExcludeKey29=FILE|%ProgramFiles%\Adobe\Acrobat DC\Acrobat\Browser\|nppdf32.dll`
`ExcludeKey30=FILE|%ProgramFiles%\Adobe\Acrobat DC\Acrobat\DocSettings\CombineFiles\ENU\|coversheet.pdf`
`ExcludeKey31=FILE|%ProgramFiles%\Adobe\Acrobat DC\Acrobat\Legal\ENU\|eula.ini`
`ExcludeKey32=FILE|%ProgramFiles%\Adobe\Acrobat DC\Acrobat\Locale\en_*\AcroForm\|FormsDataCollection.nav`
`ExcludeKey33=PATH|%CommonProgramFiles%\Adobe\Acrobat\ActiveX\|AcroPDF*.dll`
`ExcludeKey34=PATH|%CommonProgramFiles%\Adobe\Acrobat\ActiveX\|PDFShell.ME*`
`ExcludeKey35=PATH|%CommonProgramFiles%\Adobe\HelpCfg\en_*\|*.helpcfg`
`ExcludeKey36=PATH|%ProgramFiles%\Adobe\Acrobat DC\Acrobat\|nppdf32.dll`
`ExcludeKey37=PATH|%ProgramFiles%\Adobe\Acrobat DC\Acrobat\DocTemplates\ENU\|template*.pdf`
`ExcludeKey38=PATH|%ProgramFiles%\Adobe\Acrobat DC\Acrobat\HostedServicesTemplates\ENU\|template*.pdf`
`ExcludeKey39=PATH|%ProgramFiles%\Adobe\Acrobat DC\Acrobat\IDTemplates\ENU\|*ID.pdf`
`ExcludeKey40=PATH|%ProgramFiles%\Adobe\Acrobat DC\Acrobat\Locale\en_*\|*.ENU`
`ExcludeKey41=PATH|%ProgramFiles%\Adobe\Acrobat DC\Acrobat\Locale\en_*\|*.ME*`
`ExcludeKey42=PATH|%ProgramFiles%\Adobe\Acrobat DC\Acrobat\Locale\en_*\Acrobat Elements\|*.ME*`
`ExcludeKey43=PATH|%ProgramFiles%\Adobe\Acrobat DC\Acrobat\Locale\en_*\Adobe Send\|*.ME*`
`ExcludeKey44=PATH|%ProgramFiles%\Adobe\Acrobat DC\Acrobat\Locale\en_*\PDFMaker\|*.ME*`
`ExcludeKey45=PATH|%ProgramFiles%\Adobe\Acrobat DC\Acrobat\plug_ins\Annotations\Stamps\ENU\|*.pdf`
`ExcludeKey46=PATH|%ProgramFiles%\Adobe\Acrobat DC\Acrobat\plug_ins\Multimedia\MPP\|Flash.ME*`
`ExcludeKey47=PATH|%ProgramFiles%\Adobe\Acrobat DC\Acrobat\plug_ins\Multimedia\MPP\|MCIMPP.ME*`
`ExcludeKey48=PATH|%ProgramFiles%\Adobe\Acrobat DC\Acrobat\plug_ins\Multimedia\MPP\|WindowsMedia.ME*`
`ExcludeKey49=PATH|%ProgramFiles%\Adobe\Acrobat DC\Acrobat\Sequences\ENU\|Action*.sequ`
`ExcludeKey50=PATH|%ProgramFiles%\Adobe\Acrobat DC\Acrobat\UICustomization\ENU\|Custom*.aaui`
`ExcludeKey51=PATH|%ProgramFiles%\Adobe\Acrobat DC\Acrobat\WebResources\Resource*\app*\dc-desktop-*-dropin\*\|translations-en-*-json.js`
`ExcludeKey52=PATH|%ProgramFiles%\Adobe\Acrobat DC\Acrobat\*App\ENU\|*.aapp`

`[Bulk Image Downloader Languages *]`
...
Note: Please remove this entry. The program would give an error and won't start after removing the languages files.

**Comment by APMichael** [comment]
The changes have been added to version 230902.
