### ISSUE TITLE
Please add CentBrowser dir cleanup

### ISSUE THREAD

**Issue by vadimlitvinenko87** [MoscaDotTo/Winapp2#931]
Basic Winapp2 do not have this records, last seen in extended Winapp, but dont know why not to include it to basic. Thanks.

Chromium based browser

%LocalAppData%\CentBrowser\
%LocalAppData%\CentBrowser\Application\
%LocalAppData%\CentBrowser\User Data\

**Comment by MoscaDotTo** [comment]
addressed in a forthcoming version :)
