### ISSUE TITLE
Universal Windows Platform deletes WinGet settings

### ISSUE THREAD

**Issue by Virakal** [MoscaDotTo/Winapp2#932]
The Windows - Universal Windows Platform rule deletes the settings file for [WinGet](https://github.com/microsoft/winget-cli) which I don't believe is intentional. The settings file is at `%LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json` so presumably it's the `FileKey4=%LocalAppData%\Packages\Microsoft.DesktopAppInstaller_*\LocalState|*|RECURSE` line that gets it.

**Comment by MoscaDotTo** [comment]
fixed in an upcoming release through use of an ExcludeKey
