### ISSUE TITLE
is Winapp2 repository abandoned?

### ISSUE THREAD

**Issue by FuccDucc** [MoscaDotTo/Winapp2#934]
Hello,

Looking at the overall activity, previous statements from the maintainer, and trends (like: no PR's being merged, issues being ignored, lack of updates/any changes at all, that far outlast MoscaDotTo's own prediction of for how long until he would be back) im afraid that the Winapp2 project is this time abandoned for real.

Can i ask @MoscaDotTo if that's the case, or if there are actually plans for the future or causes. Also, if it is what i think it is, maybe he can consider appointing a new maintainer, as this is an awesome project that better not go to waste, for example i would say @APMichael or @aquila-XP (in case Michael doesn't want, maybe he wants) are the possible choices for new maintainer? I hope that can be done on MoscaDotTo's last breath of motivation, if he would also rather see his years of work to persist.

**Comment by APMichael** [comment]
I had to stop maintaining the project at the end of 2021, because I unfortunately didn't have enough free time for it. Unfortunately, nothing has changed (yet), so I still lack the free time for it. ☹️

I really hope that @MoscaDotTo is doing well and that she will soon be able to spend enough and regular time for the maintenance of the project again.

**Comment by MoscaDotTo** [comment]
short version: no 

longer version: I've been very sick with a metabolic illness for the last year and also hold a full time job which is entirely unrelated to this project. Unfortunately, I have not had the time I've wanted to commit to things here as I deal with work and my health. I have been working on winapp2ool when I can and have a substantial update ready for the Diff component which is necessary so as to even be able to quantify the changes made from V22XXXX -> V23XXXX and into the future, as there are more substantial changes required that I have not begun. As soon as I sort out an issue with my code signing certificate, I will be able to resume publishing builds of winapp2ool again. For now, I have been producing unsigned builds locally but I cannot distribute them or anti virus applications will flag as a false positive.

**Comment by Alexeilive** [comment]
MoscaDotTo:
Be careful with your health and take the time you need.

**Comment by FuccDucc** [comment]
Oh, i couldn't imagine that.. totally understandable, prioritize what matters most which is your life and health.
