### ISSUE TITLE
Gooolge Chrome WebApplications icons get removed

### ISSUE THREAD

**Issue by reloxx13** [MoscaDotTo/Winapp2#935]
Heya,
if you create a web application from a website from Google Chrome, there will be a .ico saved which gets removed.     
    
The problem is, it will never get re-saved when opening the webapp and remains with a white not found icon as shortcut.    

Its removed in the caches block, i would disable it, but it also deletes alot of other trash, so i would like to ask for an exclusion for the ico and md5 file.

Example:
%USERPROFILE%\AppData\Local\Google\Chrome\User Data\Default\Web Applications\_crx_efmjfjelnicpmdcmfikempdhlmainjcb\Chrome Remote Desktop.ico
there is also a md5 file next to it: Chrome Remote Desktop.ico.md5

**Comment by reloxx13** [comment]
The google chrome browser icon also gets remove if you stick it to the startmenu (win10)

**Comment by APMichael** [comment]
Maybe the web applications should get their own separate entry **\[xxx Web Applications \*\]** again?

`%LocalAppData%\xxx\User Data\*\Web Applications|*|REMOVESELF`

**Comment by MoscaDotTo** [comment]
Interesting problem. 

At first glance there doesn't appear to be anything that's actually "junk" in the web applications folder, but if you uninstall an app its files are left over in this directory. Seemingly their only particular use is displaying the favicon of the website if and only if the app is pinned to the taskbar (deleting the files without it pinned will still display the favicon, perhaps only if you also delete the corresponding IndexedDB folder but i didnt test this too much) 

Not really sure what the solution here is. Maybe the Web Application bits can be split off into winapp3.ini ? with the understanding that generally the only way files wind up here is if they are intentionally installed as a web application (requires clicking through multiple prompts) so most of the time that files exist here they're actually likely not junk?

**Comment by MoscaDotTo** [comment]
from what I can tell there's not really an expectation that if files are in this folder that they would be trash in any other context than things left behind after an uninstall, so im going to remove cleaning for this in the next update. we can always re-introduce a standalone entry but currently I do not see the need
