### ISSUE TITLE
Re-done: improvements for Firefox cache cleaning

### ISSUE THREAD

**Issue by FuccDucc** [MoscaDotTo/Winapp2#939]
Follow up for issue #912 

What's left to do (with all the latest changes as @MoscaDotTo referred to):

C:\Users[USER]\AppData\Roaming\Mozilla\Firefox\Profiles[profile id folder]\security_state > All contents
C:\Users[USER]\AppData\Roaming\Mozilla\Firefox\Profiles[profile id folder] > cert9.db
C:\Users[USER]\AppData\Roaming\Mozilla\Firefox\Profiles[profile id folder] > key4.db
C:\Users[USER]\AppData\Roaming\Mozilla\Firefox\Profiles[profile id folder] > ClientAuthRememberList.txt
C:\Users[USER]\AppData\Roaming\Mozilla\Firefox\Profiles[profile id folder] > credentialstate.sqlite
C:\Users[USER]\AppData\Roaming\Mozilla\Firefox\Profiles[profile id folder] > xulstore.json

**Comment by MoscaDotTo** [comment]
addressed in 20230901
