### ISSUE TITLE
Update Visual Studio

### ISSUE THREAD

**Issue by magol** [MoscaDotTo/Winapp2#94]
The entries around Visual Studio is quite old. Visual Studio 2015 and 2017 is missing.

Visual Studio 2017 have done some breaking changes compare to the older versions. One big change is that it not store most of it settings in the normal registry, it is storing it in a registry hive (see [Updating registry settings for Visual Studio 2017](https://blog.agchapman.com/updating-registry-settings-for-visual-studio-2017)). Is it possible to do cleaning in that with CCleaner?

**Comment by ROCKNROLLKID** [comment]
You would need to add the cleaning entry in order to clean VS 2015/2017.

**Comment by TZocker** [comment]
HKEY_CURRENT_USER\SOFTWARE\Microsoft\VisualStudio\14.0\LastLoadedSolution
C:\Users\AdminT\AppData\Local\Microsoft\VisualStudio\SettingsLogs       *.tsv
C:\Users\AdminT\AppData\Local\Microsoft\VisualStudio\14.0                     *lock,*.cache + subfolders
C:\Users\AdminT\AppData\Local\Microsoft\VisualStudio\14.0\MEFCacheBackup      Complete?

C:\Users\AdminT\AppData\Local\Microsoft\VisualStudio\vshub\Settings\SyncSettings    ????

i think there are the only interresting entries but i havent tested !!!

**Comment by magol** [comment]
@TZocker I have created a PR (#97) where I have started to update. I don't have VS2015, but help me fill in all that is missing.

**Comment by TZocker** [comment]
C:\Users\AdminT\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\*.cache
C:\Users\AdminT\AppData\Local\Microsoft\VisualStudio\SettingsLogs \*.tsv
C:\Users\AdminT\AppData\Local\Microsoft\VisualStudio\14.0\ComponentModelCache\*.cache 
C:\Users\AdminT\AppData\Local\Microsoft\VisualStudio\14.0\ImageLibrary\*.cache
C:\Users\AdminT\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\*.cache

C:\Users\AdminT\AppData\Local\Microsoft\VisualStudio\14.0\Notifications\*.*



works

**Comment by magol** [comment]
@TZocker I have added an entry for the cache files :-)

**Comment by TZocker** [comment]
https://github.com/MoscaDotTo/Winapp2/pull/122/files

lost

**Comment by ROCKNROLLKID** [comment]
Fixed.
