### ISSUE TITLE
Firefox Caches: xulstore.json stores window size and menu bar visibility

### ISSUE THREAD

**Issue by Feathered-Serpent** [MoscaDotTo/Winapp2#944]
Hi everyone,

deleting the xulstore.json file from the Firefox profile (currently listed at section "Firefox Caches *") causes my Firefox to loose not only the window position but also if certain menus are visible or not.

The content of the/my file is:
```
{"chrome://browser/content/browser.xhtml":{"main-window":{"screenX":"0","screenY":"168","width":"1960","height":"1232","sizemode":"normal"},"toolbar-menubar":{"autohide":"false"},"sidebar-box":{"sidebarcommand":"","style":""},"sidebar-title":{"value":""}}}
```

I am not sure, that should count as Cache.

**Comment by MoscaDotTo** [comment]
this has been fixed in the latest update
