### ISSUE TITLE
Firefox HTML5 Storage

### ISSUE THREAD

**Issue by ShaneGowland** [MoscaDotTo/Winapp2#95]
Several extensions that store data locally, such as Stylus, store their data in HTML5 storage. Perhaps a warning could be added to this entry.

**Comment by ShaneGowland** [comment]
dvdbane just [contributed ](https://singularlabs.com/forums/topic/ccenhancer-firefox-with-stylus-addon/)this which I suspect might fix the issue:

ExcludeKey1=PATH|%AppData%\Mozilla\Firefox\Profiles\*\storage\default\moz-extension*

**Comment by ROCKNROLLKID** [comment]
Thank you. This has been resolved in a previous commit.
