### ISSUE TITLE
download winapp2ool to my pc

### ISSUE THREAD

**Issue by xomn634** [MoscaDotTo/Winapp2#952]
download winapp2ool to my pc; in github under  winapp2ool in don't see such a file

**Comment by Shakil-Shahadat** [comment]
It's in the release section https://github.com/MoscaDotTo/Winapp2/releases

**Comment by APMichael** [comment]
You can find the latest release here:  https://github.com/MoscaDotTo/Winapp2/tree/master/winapp2ool/bin/Release
