### ISSUE TITLE
Issues with Lively Wallpaper

### ISSUE THREAD

**Issue by LinguaOccultus** [MoscaDotTo/Winapp2#953]
Hello,

just found the next issue with an application. It is quite the same as with GOG Galaxy before: it deletes user settings.

This time, the affected application is Lively Wallpaper. When I do setup a wallpaper and change its behaviour away from the default setting and the let CCleaner run with the rule activated, the manual settings for the wallpaper are reset to the default ones. At least the correct wallpaper is still selected and the general settings of Lively Wallpaper also do not seem to be affected.

However, I am not sure what exactly affects this or which files are causing this. I you cannot find out, I can ask in their repository here on GitHub, just wanted to report this in first ...

Wether this can be excluded (as it totally makes no sense to delete your desired settings as with the GOG Galaxy case) or not, but at least a warning should be implemented.

Best regards,

**_Tim_**

**Comment by TZocker** [comment]
Sry I can't find this app in the winapp2.ini

**Comment by APMichael** [comment]
Unfortunately, I can only speculate here. It is possible that one of these entries is causing the issue:

`[Windows Lock Screen *]`
`[Windows Shell - Theme Colors History *]`

**Comment by MoscaDotTo** [comment]
There is a `[Lively Wallpaper]` in winapp.ini but that is built into ccleaner and not something we have control over

**Comment by LinguaOccultus** [comment]
> There is a `[Lively Wallpaper]` in winapp.ini but that is built into ccleaner and not something we have control over

Yepp, correct. My fault. Can be closed.

**Comment by CSGalloway** [comment]
There was a way to export the internal INIs - "CCleaner.exe /EXPORT" I
think it was, which I just tried and it doesn't seem to work any more.
Does anyone recall the correct syntax?
===============
Charles S Galloway

**Comment by APMichael** [comment]
@CSGalloway This still works. It is important that the command line is started as administrator. Then navigate to the CCleaner directory and execute the command: `CCleaner64.exe /export`

**Comment by CSGalloway** [comment]
`[Lively Wallpaper]
ID=3026
LangSecRef=3024
LangRef=9226
Default=False
DetectFile1=%LocalAppData%\Lively Wallpaper
DetectFile2=%LocalAppData%\Packages\12030rocksdanister.LivelyWallpaper_97hta09mmv6hy
FileKey1=%LocalAppData%\Packages\12030rocksdanister.LivelyWallpaper_97hta09mmv6hy\LocalCache\Local\Lively Wallpaper\UI|*.*|RECURSE
FileKey2=%LocalAppData%\Packages\12030rocksdanister.LivelyWallpaper_97hta09mmv6hy\LocalCache\Local\Lively Wallpaper\Library\SaveData\wpdata|*.*|RECURSE
FileKey3=%LocalAppData%\Lively Wallpaper\Library\SaveData\wpdata|*.*|RECURSE
FileKey4=%LocalAppData%\Packages\12030rocksdanister.LivelyWallpaper_97hta09mmv6hy\LocalCache\Local\Lively Wallpaper\logs|*.*|RECURSE
FileKey5=%LocalAppData%\Lively Wallpaper\logs|*.*|RECURSE
`

I don't have the app but that is what it is in CCleaner.

**Comment by CSGalloway** [comment]
i have reached out to the support about where the user setitng are stored...
